# Experiment 7: AutoGluon Tabular with categorical cleaning

This reruns the strong tabular AutoGluon ensemble after the shared `RentalPreprocessor` categorical cleaning update. Validation is chronological, and test categories remain strings rather than being restricted to a train-only category vocabulary.

In [2]:
# If needed: pip install autogluon.tabular
from pathlib import Path
import os
import sys
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

configured_root = os.environ.get('KDDM_PROJECT_ROOT')
candidate_roots = ([Path(configured_root)] if configured_root else []) + [
    Path.cwd(), *Path.cwd().parents, Path('/content/KDDM-project'),
    Path('/content/drive/MyDrive/KDDM-project'),
]
project_root = next((p for p in candidate_roots if (p / 'exploration/metul/preprocessing.py').exists()), None)
if project_root is None:
    raise FileNotFoundError('Set KDDM_PROJECT_ROOT to the project directory.')
experiment_dir = project_root / 'exploration' / 'metul'
sys.path.insert(0, str(experiment_dir))

from autogluon.common import space
from autogluon.tabular import TabularPredictor
from preprocessing import RentalPreprocessor, load_datasets

RANDOM_STATE = 42
TARGET = 'MONTHLY_RENT'
TIME_LIMIT_SECONDS = int(os.environ.get('AUTOGLUON_TIME_LIMIT', '1800'))
HPO_TRIALS_PER_MODEL = 25
HPO_KWARGS = {'num_trials': HPO_TRIALS_PER_MODEL, 'scheduler': 'local', 'searcher': 'random'}
HPO_HYPERPARAMETERS = {
    'GBM': {
        'num_leaves': space.Int(16, 128),
        'num_boost_round': space.Int(200, 1500),
        'max_depth': space.Int(3, 12),
        'learning_rate': space.Real(0.01, 0.20, log=True),
        'min_data_in_leaf': space.Int(10, 150),
        'feature_fraction': space.Real(0.60, 1.00),
        'bagging_fraction': space.Real(0.60, 1.00),
    },
    'CAT': {
        'iterations': space.Int(200, 1500),
        'depth': space.Int(4, 10),
        'learning_rate': space.Real(0.01, 0.20, log=True),
        'l2_leaf_reg': space.Real(1.0, 30.0, log=True),
    },
}

In [3]:
data_dir, datasets = load_datasets(project_root / 'data')
raw_train = datasets['train'].copy()
raw_test = datasets['test'].copy()
raw_train['period'] = pd.to_datetime(raw_train['RENT_APPROVAL_DATE'] + '-01')
raw_test['period'] = pd.to_datetime(raw_test['RENT_APPROVAL_DATE'] + '-01')

# Same 80% chronological split convention as the earlier tabular AutoGluon experiment.
periods = np.sort(raw_train['period'].unique())
validation_cutoff = pd.Timestamp(periods[int(len(periods) * 0.80)])
raw_fit = raw_train[raw_train['period'] < validation_cutoff].drop(columns='period').copy()
raw_valid = raw_train[raw_train['period'] >= validation_cutoff].drop(columns='period').copy()

# The preprocessor prints every categorical field's before/after unique counts.
validation_preprocessor = RentalPreprocessor(datasets)
fit_df = validation_preprocessor.fit_transform(raw_fit)
valid_df = validation_preprocessor.transform(raw_valid)

final_preprocessor = RentalPreprocessor(datasets)
full_train_df = final_preprocessor.fit_transform(raw_train.drop(columns='period'))
test_df = final_preprocessor.transform(raw_test.drop(columns='period'))

print(f'Validation cutoff: {validation_cutoff:%Y-%m}')
print(f'Fit rows: {fit_df.shape}; validation rows: {valid_df.shape}')
print(f'Full train: {full_train_df.shape}; test: {test_df.shape}')

[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2585 -> 2585 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1109 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2720 -> 2720 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1146 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2720 -> 2720 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1146 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2660 -> 2660 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1129 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
Validation cutoff: 2024-05
Fit rows: (117988, 32); validation rows: (32012, 32)
Full train: (150000, 32); test: (50000, 31)

In [4]:
def prepare_features(frame):
    result = frame.drop(columns=[TARGET], errors='ignore').copy()
    result['RENT_APPROVAL_DATE'] = pd.to_datetime(result['RENT_APPROVAL_DATE'] + '-01')
    return result

X_fit = prepare_features(fit_df)
X_valid = prepare_features(valid_df)
X_full = prepare_features(full_train_df)
X_test = prepare_features(test_df)
y_fit = fit_df[TARGET].astype(float)
y_valid = valid_df[TARGET].astype(float)
y_full = full_train_df[TARGET].astype(float)

categorical_columns = X_fit.select_dtypes(include=['object', 'string', 'category']).columns.tolist()
category_summary = pd.DataFrame([
    {
        'feature': column, 'fit_unique': X_fit[column].nunique(dropna=False),
        'validation_unique': X_valid[column].nunique(dropna=False),
        'test_unique': X_test[column].nunique(dropna=False),
        'unseen_test_values': len(set(X_test[column].dropna()) - set(X_full[column].dropna())),
    }
    for column in categorical_columns
]).sort_values('feature')
display(category_summary)
assert len(X_test) == len(raw_test)
print('Test categorical values are retained as strings; no train-only category vocabulary is imposed.')

      feature  fit_unique  validation_unique  test_unique  unseen_test_values
1       BLOCK        2699               2585         2660                  11
4  FLAT_MODEL          19                 20           19                   0
3   FLAT_TYPE           6                  6            6                   0
5      REGION           5                  5            5                   0
2      STREET         574                573          573                   0
0        TOWN          26                 26           26                   0

Test categorical values are retained as strings; no train-only category vocabulary is imposed.

In [5]:
validation_predictor = TabularPredictor(
    label=TARGET, problem_type='regression', eval_metric='root_mean_squared_error',
    path=str(experiment_dir / 'ag_exp7_categorical_validation'),
).fit(
    train_data=X_fit.assign(**{TARGET: y_fit.to_numpy()}),
    tuning_data=X_valid.assign(**{TARGET: y_valid.to_numpy()}),
    hyperparameters=HPO_HYPERPARAMETERS, hyperparameter_tune_kwargs=HPO_KWARGS,
    presets='medium_quality', time_limit=TIME_LIMIT_SECONDS, verbosity=2,
)

valid_predictions = validation_predictor.predict(X_valid).astype(float)
validation_metrics = pd.DataFrame([{
    'RMSE': mean_squared_error(y_valid, valid_predictions) ** 0.5,
    'MAE': mean_absolute_error(y_valid, valid_predictions),
    'R2': r2_score(y_valid, valid_predictions),
}])
display(validation_metrics)
display(validation_predictor.leaderboard(X_valid.assign(**{TARGET: y_valid.to_numpy()}), silent=True, extra_info=True))

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp7_categorical_validation"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.57 GB / 16.00 GB (22.3%)
Disk Space Avail:   194.22 GB / 460.38 GB (42.2%)
===================================================
Presets specified: ['medium_quality']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp7_categorical_validation"
Train Data Rows:    117988
Train Data Columns: 31
Tuning Data Rows:    32012
Tuning Data Columns: 31
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3722.92 MB
	Train Data (Original)  Memory Usage: 79.00 MB (2.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 4 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('datetime', [])     :  1 | ['RENT_APPROVAL_DATE']
		('float', [])        : 12 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'MAX_FLOOR', 'YEAR_COMPLETED', ...]
		('int', [])          : 12 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('object', ['text']) :  1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('category', ['text_as_category'])  :  1 | ['STREET']
		('float', [])                       : 12 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'MAX_FLOOR', 'YEAR_COMPLETED', ...]
		('int', [])                         : 12 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('int', ['binned', 'text_special']) :  6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['datetime_as_int'])        :  2 | ['RENT_APPROVAL_DATE', 'RENT_APPROVAL_DATE.dayofweek']
		('int', ['text_ngram'])             :  5 | ['__nlp__.avenue', '__nlp__.drive', '__nlp__.road', '__nlp__.street', '__nlp__._total_']
	1.5s = Fit runtime
	31 features in original data used to generate 43 features in processed data.
	Train Data (Processed) Memory Usage: 33.19 MB (0.9% of available memory)
Data preprocessing and feature engineering runtime = 1.52s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=16, upper=128, 'num_boost_round': Int: lower=200, upper=1500, 'max_depth': Int: lower=3, upper=12, 'learning_rate': Real: lower=0.01, upper=0.2, 'min_data_in_leaf': Int: lower=10, upper=150, 'feature_fraction': Real: lower=0.6, upper=1.0, 'bagging_fraction': Real: lower=0.6, upper=1.0}],
	'CAT': [{'iterations': Int: lower=200, upper=1500, 'depth': Int: lower=4, upper=10, 'learning_rate': Real: lower=0.01, upper=0.2, 'l2_leaf_reg': Real: lower=1.0, upper=30.0}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 809.32s of the 1798.48s of remaining time.
/Users/metul/Desktop/KDDM-project/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
 24%|██▍       | 6/25 [00:12<00:43,  2.30s/it]

[1000]	valid_set's rmse: 473.216

 36%|███▌      | 9/25 [00:24<00:46,  2.90s/it]

[1000]	valid_set's rmse: 472.933

 40%|████      | 10/25 [00:31<01:03,  4.21s/it]

[1000]	valid_set's rmse: 474.358

 52%|█████▏    | 13/25 [00:46<00:52,  4.40s/it]

[1000]	valid_set's rmse: 471.675

 56%|█████▌    | 14/25 [00:52<00:51,  4.71s/it]

[1000]	valid_set's rmse: 473.703

 72%|███████▏  | 18/25 [01:11<00:33,  4.82s/it]

[1000]	valid_set's rmse: 471.461

100%|██████████| 25/25 [01:42<00:00,  4.10s/it]
Fitted model: LightGBM/T1 ...
	-538.5148	 = Validation score   (-root_mean_squared_error)
	0.65s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-473.52	 = Validation score   (-root_mean_squared_error)
	2.46s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-475.6079	 = Validation score   (-root_mean_squared_error)
	1.78s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-473.865	 = Validation score   (-root_mean_squared_error)
	3.75s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-473.6929	 = Validation score   (-root_mean_squared_error)
	0.71s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-474.1384	 = Validation score   (-root_mean_squared_error)
	2.94s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-473.05	 = Validation score   (-root_mean_squared_error)
	6.64s	 = Training   runtime
	0.4s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-473.4152	 = Validation score   (-root_mean_squared_error)
	2.44s	 = Training   runtime
	0.1s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-473.9993	 = Validation score   (-root_mean_squared_error)
	1.61s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-472.7004	 = Validation score   (-root_mean_squared_error)
	6.82s	 = Training   runtime
	0.27s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-474.3122	 = Validation score   (-root_mean_squared_error)
	8.11s	 = Training   runtime
	0.3s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-474.2486	 = Validation score   (-root_mean_squared_error)
	4.77s	 = Training   runtime
	0.13s	 = Validation runtime
Fitted model: LightGBM/T13 ...
	-471.6449	 = Validation score   (-root_mean_squared_error)
	2.13s	 = Training   runtime
	0.12s	 = Validation runtime
Fitted model: LightGBM/T14 ...
	-476.1447	 = Validation score   (-root_mean_squared_error)
	5.19s	 = Training   runtime
	0.2s	 = Validation runtime
Fitted model: LightGBM/T15 ...
	-473.3454	 = Validation score   (-root_mean_squared_error)
	4.85s	 = Training   runtime
	0.22s	 = Validation runtime
Fitted model: LightGBM/T16 ...
	-471.7549	 = Validation score   (-root_mean_squared_error)
	2.86s	 = Training   runtime
	0.14s	 = Validation runtime
Fitted model: LightGBM/T17 ...
	-474.989	 = Validation score   (-root_mean_squared_error)
	8.11s	 = Training   runtime
	0.22s	 = Validation runtime
Fitted model: LightGBM/T18 ...
	-474.2052	 = Validation score   (-root_mean_squared_error)
	3.08s	 = Training   runtime
	0.11s	 = Validation runtime
Fitted model: LightGBM/T19 ...
	-471.3322	 = Validation score   (-root_mean_squared_error)
	2.51s	 = Training   runtime
	0.14s	 = Validation runtime
Fitted model: LightGBM/T20 ...
	-475.9757	 = Validation score   (-root_mean_squared_error)
	2.08s	 = Training   runtime
	0.11s	 = Validation runtime
Fitted model: LightGBM/T21 ...
	-475.499	 = Validation score   (-root_mean_squared_error)
	4.03s	 = Training   runtime
	0.12s	 = Validation runtime
Fitted model: LightGBM/T22 ...
	-474.6641	 = Validation score   (-root_mean_squared_error)
	2.35s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T23 ...
	-474.9542	 = Validation score   (-root_mean_squared_error)
	8.91s	 = Training   runtime
	0.28s	 = Validation runtime
Fitted model: LightGBM/T24 ...
	-474.1748	 = Validation score   (-root_mean_squared_error)
	6.1s	 = Training   runtime
	0.1s	 = Validation runtime
Fitted model: LightGBM/T25 ...
	-489.8798	 = Validation score   (-root_mean_squared_error)
	3.52s	 = Training   runtime
	0.11s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 809.32s of the 1695.73s of remaining time.
100%|██████████| 25/25 [09:03<00:00, 21.72s/it]
Fitted model: CatBoost/T1 ...
	-529.2425	 = Validation score   (-root_mean_squared_error)
	1.85s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-471.1667	 = Validation score   (-root_mean_squared_error)
	17.04s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-471.859	 = Validation score   (-root_mean_squared_error)
	24.65s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-470.4059	 = Validation score   (-root_mean_squared_error)
	32.96s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-474.7178	 = Validation score   (-root_mean_squared_error)
	39.16s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-472.4089	 = Validation score   (-root_mean_squared_error)
	5.13s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-472.2144	 = Validation score   (-root_mean_squared_error)
	14.08s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-470.1109	 = Validation score   (-root_mean_squared_error)
	30.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-470.67	 = Validation score   (-root_mean_squared_error)
	26.75s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-478.5706	 = Validation score   (-root_mean_squared_error)
	9.96s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-473.2563	 = Validation score   (-root_mean_squared_error)
	30.97s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-471.4914	 = Validation score   (-root_mean_squared_error)
	41.04s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: CatBoost/T13 ...
	-475.9978	 = Validation score   (-root_mean_squared_error)
	8.73s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T14 ...
	-487.7999	 = Validation score   (-root_mean_squared_error)
	5.9s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T15 ...
	-470.7818	 = Validation score   (-root_mean_squared_error)
	34.73s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T16 ...
	-477.8417	 = Validation score   (-root_mean_squared_error)
	7.82s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T17 ...
	-472.6849	 = Validation score   (-root_mean_squared_error)
	5.91s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T18 ...
	-471.1444	 = Validation score   (-root_mean_squared_error)
	39.1s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: CatBoost/T19 ...
	-470.3497	 = Validation score   (-root_mean_squared_error)
	66.92s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: CatBoost/T20 ...
	-475.3973	 = Validation score   (-root_mean_squared_error)
	20.22s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T21 ...
	-476.3866	 = Validation score   (-root_mean_squared_error)
	21.45s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T22 ...
	-473.4674	 = Validation score   (-root_mean_squared_error)
	20.26s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T23 ...
	-470.7544	 = Validation score   (-root_mean_squared_error)
	20.91s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T24 ...
	-478.508	 = Validation score   (-root_mean_squared_error)
	7.34s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T25 ...
	-471.6976	 = Validation score   (-root_mean_squared_error)
	8.31s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1146.39s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.3 GB
	Ensemble Weights: {'LightGBM/T7': 0.357, 'CatBoost/T8': 0.214, 'CatBoost/T9': 0.143, 'CatBoost/T15': 0.143, 'LightGBM/T19': 0.071, 'CatBoost/T19': 0.071}
	-466.4323	 = Validation score   (-root_mean_squared_error)
	0.03s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 653.75s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 42578.8 rows/s (32012 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp7_categorical_validation")

         RMSE        MAE       R2
0  466.432303  345.73183  0.49597

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,...,hyperparameters,hyperparameters_fit,ag_args_fit,features,compile_time,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
0,WeightedEnsemble_L2,-466.432303,-466.432303,root_mean_squared_error,0.919113,0.751830,168.109143,0.001571,0.000329,0.027096,...,"{'use_orig_features': False, 'valid_stacker': ...",{},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[LightGBM/T7, CatBoost/T8, CatBoost/T19, CatBo...",None,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 14},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[LightGBM/T7, CatBoost/T8, CatBoost/T19, CatBo...",[]
1,CatBoost/T8,-470.110903,-470.110903,root_mean_squared_error,0.044971,0.049467,30.525833,0.044971,0.049467,30.525833,...,"{'iterations': 859, 'learning_rate': 0.0866093...",{'iterations': 816},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
2,CatBoost/T19,-470.349685,-470.349685,root_mean_squared_error,0.059685,0.059240,66.919558,0.059685,0.059240,66.919558,...,"{'iterations': 1367, 'learning_rate': 0.064744...",{'iterations': 1004},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
3,CatBoost/T4,-470.405895,-470.405895,root_mean_squared_error,0.046911,0.039414,32.963205,0.046911,0.039414,32.963205,...,"{'iterations': 800, 'learning_rate': 0.0418269...",{'iterations': 799},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
4,CatBoost/T9,-470.669978,-470.669978,root_mean_squared_error,0.047169,0.051203,26.753069,0.047169,0.051203,26.753069,...,"{'iterations': 1489, 'learning_rate': 0.097046...",{'iterations': 1488},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
5,CatBoost/T23,-470.754395,-470.754395,root_mean_squared_error,0.037438,0.041544,20.908365,0.037438,0.041544,20.908365,...,"{'iterations': 568, 'learning_rate': 0.0915807...",{'iterations': 564},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
6,CatBoost/T15,-470.781847,-470.781847,root_mean_squared_error,0.047518,0.052167,34.734976,0.047518,0.052167,34.734976,...,"{'iterations': 1343, 'learning_rate': 0.029239...",{'iterations': 1343},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
7,CatBoost/T18,-471.144351,-471.144351,root_mean_squared_error,0.054839,0.057518,39.101503,0.054839,0.057518,39.101503,...,"{'iterations': 1355, 'learning_rate': 0.057148...",{'iterations': 1351},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
8,CatBoost/T2,-471.166742,-471.166742,root_mean_squared_error,0.036063,0.033337,17.040858,0.036063,0.033337,17.040858,...,"{'iterations': 759, 'learning_rate': 0.0608433...",{'iterations': 754},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
9,LightGBM/T19,-471.332182,-471.332182,root_mean_squared_error,0.207763,0.142733,2.506999,0.207763,0.142733,2.506999,...,"{'learning_rate': 0.09047101764422108, 'num_le...",{'num_boost_round': 1188},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
10,CatBoost/T12,-471.491430,-471.491430,root_mean_squared_error,0.052628,0.067165,41.043523,0.052628,0.067165,41.043523,...,"{'iterations': 1277, 'learning_rate': 0.019464...",{'iterations': 1277},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
11,LightGBM/T13,-471.644874,-471.644874,root_mean_squared_error,0.176637,0.116270,2.132810,0.176637,0.116270,2.132810,...,"{'learning_rate': 0.07277250537261028, 'num_le...",{'num_boost_round': 991},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
12,CatBoost/T25,-471.697623,-471.697623,root_mean_squared_error,0.023266,0.028697,8.311604,0.023266,0.028697,8.311604,...,"{'iterations': 330, 'learning_rate': 0.1398059...",{'iterations': 318},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
13,LightGBM/T16,-471.754867,-471.754867,root_mean_squared_error,0.223853,0.144108,2.864778,0.223853,0.144108,2.864778,...,"{'learning_rate': 0.054596586124474676, 'num_l...",{'num_boost_round': 982},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
14,CatBoost/T3,-471.858978,-471.858978,root_mean_squared_error,0.042601,0.038460,24.649769,0.042601,0.038460,24.649769,...,"{'iterations': 1233, 'learning_rate': 0.031629...",{'iterations': 1233},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
15,CatBoost/T7,-472.214408,-472.214408,root_mean_squared_error,0.031239,0.035877,14.080934,0.031239,0.035877,14.080934,...,"{'iterations': 1050, 'learning_rate': 0.110156...",{'iterations': 1048},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
16,CatBoost/T6,-472.408904,-472.408904,root_mean_squared_error,0.021038,0.024191,5.127781,0.021038,0.024191,5.127781,...,"{'iterations': 315, 'learning_rate': 0.1759088...",{'iterations': 314},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
17,CatBoost/T17,-472.684866,-472.684866,root_mean_squared_error,0.021963,0.027075,5.909190,0.021963,0.027075,5.909190,...,"{'iterations': 284, 'learning_rate': 0.1768568...",{'iterations': 283},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
18,LightGBM/T10,-472.700431,-472.700431,root_mean_squared_error,0.438575,0.268290,6.817957,0.438575,0.268290,6.817957,...,"{'learning_rate': 0.014714211033798401, 'num_l...",{'num_boost_round': 1108},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
19,LightGBM/T7,-473.049968,-473.049968,root_mean_squared_error,0.510436,0.396691,6.641613,0.510436,0.396691,6.641613,...,"{'learning_rate': 0.034632801362530156, 'num_l...",{'num_boost_round': 1407},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
20,CatBoost/T11,-473.256303,-473.256303,root_mean_squared_error,0.042867,0.050332,30.967278,0.042867,0.050332,30.967278,...,"{'iterations': 1407, 'learning_rate': 0.014994...",{'iterations': 1406},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
21,LightGBM/T15,-473.345398,-473.345398,root_mean_squared_error,0.341800,0.223381,4.850619,0.341800,0.223381,4.850619,...,"{'learning_rate': 0.014271457340253242, 'num_l...",{'num_boost_round': 1130},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
22,LightGBM/T8,-473.415204,-473.415204,root_mean_squared_error,0.147310,0.095264,2.437814,0.147310,0.095264,2.437814,...,"{'learning_rate': 0.06361540670994398, 'num_le...",{'num_boost_round': 528},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
23,CatBoost/T22,-473.467373,-473.467373,root_mean_squared_error,0.037796,0.036114,20.256005,0.037796,0.036114,20.256005,...,"{'iterations': 1016, 'learning_rate': 0.040712...",{'iterations': 1015},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
24,LightGBM/T2,-473.519962,-473.519962,root_mean_squared_error,0.072436,0.075478,2.464265,0.072436,0.075478,2.464265,...,"{'learning_rate': 0.060843366042818384, 'num_l...",{'num_boost_round': 336},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
25,LightGBM/T5,-473.692889,-473.692889,root_mean_squared_error,0.037481,0.033075,0.706228,0.037481,0.033075,0.706228,...,"{'learning_rate': 0.12113325685093146, 'num_le...",{'num_boost_round': 298},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
26,LightGBM/T4,-473.864963,-473.864963,root_mean_squared_error,0.079383,0.071532,3.746548,0.079383,0.071532,3.746548,...,"{'learning_rate': 0.05483312693790952, 'num_le...",{'num_boost_round': 242},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
27,LightGBM/T9,-473.999299,-473.999299,root_mean_squared_error,0.108398,0.070959,1.612928,0.108398,0.070959,1.612928,...,"{'learning_rate': 0.03703323754998522, 'num_le...",{'num_boost_round': 491},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
28,LightGBM/T6,-474.138422,-474.138422,root_mean_squared_error,0.072689,0.056478,2.937980,0.072689,0.056478,2.937980,...,"{'learning_rate': 0.0764262643436005, 'num_lea...",{'num_boost_round': 173},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
29,LightGBM/T24,-474.174832,-474.174832,root_mean_squared_error,0.144886,0.098446,6.096675,0.144886,0.098446,6.096675,...,"{'learning_rate': 0.03612775217504794, 'num_le...",{'num_boost_round': 281},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
30,LightGBM/T18,-474.205198,-474.205198,root_mean_squared_error,0.158260,0.108267,3.078169,0.158260,0.108267,3.078169,...,"{'learning_rate': 0.022101506860254506, 'num_l...",{'num_boost_round': 486},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
31,LightGBM/T12,-474.248620,-474.248620,root_mean_squared_error,0.203986,0.133023,4.771832,0.203986,0.133023,4.771832,...,"{'learning_rate': 0.04145679169093252, 'num_le...",{'num_boost_round': 372},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
32,LightGBM/T11,-474.312232,-474.312232,root_mean_squared_error,0.482819,0.295862,8.112412,0.482819,0.295862,8.112412,...,"{'learning_rate': 0.013575735243004695, 'num_l...",{'num_boost_round': 1030},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
33,LightGBM/T22,-474.664107,-474.664107,root_mean_squared_error,0.068991,0.049281,2.350260,0.068991,0.049281,2.350260,...,"{'learning_rate': 0.0878167929116211, 'num_lea...",{'num_boost_round': 162},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
34,CatBoost/T5,-474.717808,-474.717808,root_mean_squared_error,0.046914,0.047153,39.158452,0.046914,0.047153,39.158452,...,"{'iterations': 1049, 'learning_rate': 0.012371...",{'iterations': 1047},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
35,LightGBM/T23,-474.954195,-474.954195,root_mean_squared_error,0.387378,0.279600,8.912872,0.387378,0.279600,8.912872,...,"{'learning_rate': 0.010591828171692784, 'num_l...",{'num_boost_round': 723},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
36,LightGBM/T17,-474.989031,-474.989031,root_mean_squared_error,0.318338,0.219676,8.111517,0.318338,0.219676,8.111517,...,"{'learning_rate': 0.02297842081277621, 'num_le...",{'num_boost_round': 534},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
37,CatBoost/T20,-475.397333,-475.397333,root_mean_squared_error,0.033913,0.037743,20.219231,0.033913,0.037743,20.219231,...,"{'iterations': 573, 'learning_rate': 0.0151279...",{'iterations': 573},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
38,LightGBM/T21,-475.499017,-475.499017,root_mean_squared_error,0.173172,0.123604,4.028517,0.173172,0.123604,4.028517,...,"{'learning_rate': 0.032799397210704205, 'num_l...",{'num_boost_round': 334},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
39,LightGBM/T3,-475.607906,-475.607906,root_mean_squared_error,0.041740,0.037733,1.782522,0.041740,0.037733,1.782522,...,"{'learning_rate': 0.14461835703563009, 'num_le...",{'num_boost_round': 107},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
40,LightGBM/T20,-475.975706,-475.975706,root_mean_squared_error,0.167563,0.112944,2.084524,0.167563,0.112944,2.084524,...,"{'learning_rate': 0.019509039836980442, 'num_l...",{'num_boost_round': 949},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
41,CatBoost/T13,-475.997801,-475.997801,root_mean_squared_error,0.025814,0.026877,8.729326,0.025814,0.026877,8.729326,...,"{'iterations': 535, 'learning_rate': 0.0384944...",{'iterations': 534},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
42,LightGBM/T14,-476.144683,-476.144683,root_mean_squared_error,0.294955,0.196024,5.191573,0.294955,0.196024,5.191573,...,"{'learning_rate': 0.011816435472502053, 'num_l...",{'num_boost_round': 570},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
43,CatBoost/T21,-476.386602,-476.386602,root_mean_squared_error,0.035588,0.035310,21.445489,0.035588,0.035310,21.445489,...,"{'iterations': 1319, 'learning_rate': 0.013376...",{'iterations': 1313},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
44,CatBoost/T16,-477.841749,-477.841749,root_mean_squared_error,0.022898,0.024578,7.821140,0.022898,0.024578,7.821140,...,"{'iterations': 598, 'learning_rate': 0.0264786...",{'iterations': 598},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
45,CatBoost/T24,-478.507972,-478.507972,root_mean_squared_error,0.021852,0.025678,7.339455,0.021852,0.025678,7.339455,...,"{'iterations': 570, 'learning_rate': 0.0293526...",{'iterations': 570},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
46,CatBoost/T10,-478.570583,-478.570583,root_mean_squared_error,0.024535,0.030059,9.956776,0.024535,0.030059,9.956776,...,"{'iterations': 444, 'learning_rate': 0.0174752...",{'iterations': 444},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
47,CatBoost/T14,-487.799853,-487.799853,root_mean_squared_error,0.020445,0.022606,5.902993,0.020445,0.022606,5.902993,...,"{'iterations': 457, 'learning_rate': 0.0119771...",{'iterations': 457},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
48,LightGBM/T25,-489.879770,-489.879770,root_mean_squared_error,0.158520,0.112879,3.516109,0.158520,0.112879,3.516109,...,"{'learning_rate': 0.011059799535949847, 'num_l...",{'num_boost_round': 224},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
49,CatBoost/T1,-529.242480,-529.242480,root_mean_squared_error,0.016195,0.013061,1.846384,0.016195,0.013061,1.846384,...,"{'iterations': 200, 'learning_rate': 0.01, 'al...",{'iterations': 200},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
50,LightGBM/T1,-538.514791,-538.514791,root_mean_squared_error,0.023248,0.024309,0.654332,0.023248,0.024309,0.654332,...,"{'learning_rate': 0.01, 'num_leaves': 16, 'num...",{'num_boost_round': 200},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]

In [6]:
final_predictor = TabularPredictor(
    label=TARGET, problem_type='regression', eval_metric='root_mean_squared_error',
    path=str(experiment_dir / 'ag_exp7_categorical_final'),
).fit(
    train_data=X_full.assign(**{TARGET: y_full.to_numpy()}),
    hyperparameters=HPO_HYPERPARAMETERS, hyperparameter_tune_kwargs=HPO_KWARGS,
    presets='medium_quality', time_limit=TIME_LIMIT_SECONDS, verbosity=2,
)

test_predictions = final_predictor.predict(X_test).astype(float).clip(lower=0)
diagnostic_output = test_df.copy()
diagnostic_output['PREDICTED_MONTHLY_RENT'] = test_predictions.to_numpy()
diagnostic_path = experiment_dir / 'exp_7_autogluon_categorical_clean_predictions.csv'
diagnostic_output.to_csv(diagnostic_path, index=False)

competition_submission = pd.DataFrame({'Id': raw_test.index, 'Predicted': test_predictions.to_numpy()})
assert competition_submission['Id'].is_unique and competition_submission['Predicted'].notna().all()
submission_path = experiment_dir / 'exp_7_autogluon_categorical_clean_submission.csv'
competition_submission.to_csv(submission_path, index=False)
print(f'Saved diagnostics to {diagnostic_path}')
print(f'Saved {len(competition_submission):,} competition predictions to {submission_path}')
display(competition_submission.head())

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp7_categorical_final"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.35 GB / 16.00 GB (21.0%)
Disk Space Avail:   194.02 GB / 460.38 GB (42.1%)
===================================================
Presets specified: ['medium_quality']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp7_categorical_final"
Train Data Rows:    150000
Train Data Columns: 31
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3453.84 MB
	Train Data (Original)  Memory Usage: 79.00 MB (2.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 3 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('datetime', [])     :  1 | ['RENT_APPROVAL_DATE']
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', ...]
		('int', [])          : 14 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('object', ['text']) :  1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('category', ['text_as_category'])  :  1 | ['STREET']
		('float', [])                       : 10 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', ...]
		('int', [])                         : 14 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('int', ['binned', 'text_special']) :  6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['datetime_as_int'])        :  2 | ['RENT_APPROVAL_DATE', 'RENT_APPROVAL_DATE.dayofweek']
		('int', ['text_ngram'])             :  4 | ['__nlp__.avenue', '__nlp__.road', '__nlp__.street', '__nlp__._total_']
	1.6s = Fit runtime
	31 features in original data used to generate 42 features in processed data.
	Train Data (Processed) Memory Usage: 32.91 MB (1.0% of available memory)
Data preprocessing and feature engineering runtime = 1.59s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0333, Train Rows: 145004, Val Rows: 4996
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=16, upper=128, 'num_boost_round': Int: lower=200, upper=1500, 'max_depth': Int: lower=3, upper=12, 'learning_rate': Real: lower=0.01, upper=0.2, 'min_data_in_leaf': Int: lower=10, upper=150, 'feature_fraction': Real: lower=0.6, upper=1.0, 'bagging_fraction': Real: lower=0.6, upper=1.0}],
	'CAT': [{'iterations': Int: lower=200, upper=1500, 'depth': Int: lower=4, upper=10, 'learning_rate': Real: lower=0.01, upper=0.2, 'l2_leaf_reg': Real: lower=1.0, upper=30.0}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 809.28s of the 1798.41s of remaining time.
 24%|██▍       | 6/25 [00:20<01:09,  3.65s/it]

[1000]	valid_set's rmse: 473.777

 36%|███▌      | 9/25 [00:32<00:57,  3.62s/it]

[1000]	valid_set's rmse: 474.906

 40%|████      | 10/25 [00:41<01:16,  5.10s/it]

[1000]	valid_set's rmse: 475.762

 52%|█████▏    | 13/25 [01:01<01:07,  5.64s/it]

[1000]	valid_set's rmse: 472.926

 56%|█████▌    | 14/25 [01:08<01:04,  5.87s/it]

[1000]	valid_set's rmse: 475.333

 72%|███████▏  | 18/25 [01:31<00:40,  5.75s/it]

[1000]	valid_set's rmse: 473.414

100%|██████████| 25/25 [02:06<00:00,  5.07s/it]
Fitted model: LightGBM/T1 ...
	-517.6578	 = Validation score   (-root_mean_squared_error)
	0.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-474.5714	 = Validation score   (-root_mean_squared_error)
	4.26s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-477.1751	 = Validation score   (-root_mean_squared_error)
	2.91s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-476.102	 = Validation score   (-root_mean_squared_error)
	6.19s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-475.4445	 = Validation score   (-root_mean_squared_error)
	0.88s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-476.0031	 = Validation score   (-root_mean_squared_error)
	4.82s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-473.7189	 = Validation score   (-root_mean_squared_error)
	7.81s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-474.4201	 = Validation score   (-root_mean_squared_error)
	2.86s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-475.6732	 = Validation score   (-root_mean_squared_error)
	1.96s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-474.7393	 = Validation score   (-root_mean_squared_error)
	8.28s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-475.693	 = Validation score   (-root_mean_squared_error)
	10.27s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-475.3452	 = Validation score   (-root_mean_squared_error)
	7.0s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T13 ...
	-472.8699	 = Validation score   (-root_mean_squared_error)
	2.84s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T14 ...
	-476.9756	 = Validation score   (-root_mean_squared_error)
	6.33s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T15 ...
	-475.059	 = Validation score   (-root_mean_squared_error)
	6.16s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T16 ...
	-473.2973	 = Validation score   (-root_mean_squared_error)
	3.72s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T17 ...
	-476.528	 = Validation score   (-root_mean_squared_error)
	9.38s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T18 ...
	-475.5723	 = Validation score   (-root_mean_squared_error)
	3.78s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T19 ...
	-473.0535	 = Validation score   (-root_mean_squared_error)
	3.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T20 ...
	-476.5808	 = Validation score   (-root_mean_squared_error)
	2.77s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T21 ...
	-476.8401	 = Validation score   (-root_mean_squared_error)
	4.29s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T22 ...
	-476.9617	 = Validation score   (-root_mean_squared_error)
	2.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T23 ...
	-476.4425	 = Validation score   (-root_mean_squared_error)
	10.46s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: LightGBM/T24 ...
	-476.7159	 = Validation score   (-root_mean_squared_error)
	7.02s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T25 ...
	-484.4475	 = Validation score   (-root_mean_squared_error)
	4.3s	 = Training   runtime
	0.03s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 809.28s of the 1671.44s of remaining time.
100%|██████████| 25/25 [09:49<00:00, 23.58s/it]
Fitted model: CatBoost/T1 ...
	-511.2366	 = Validation score   (-root_mean_squared_error)
	2.83s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-472.7694	 = Validation score   (-root_mean_squared_error)
	26.38s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-473.0831	 = Validation score   (-root_mean_squared_error)
	36.45s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-472.6047	 = Validation score   (-root_mean_squared_error)
	46.87s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-474.5096	 = Validation score   (-root_mean_squared_error)
	51.05s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-474.54	 = Validation score   (-root_mean_squared_error)
	6.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-473.3369	 = Validation score   (-root_mean_squared_error)
	16.43s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-472.5977	 = Validation score   (-root_mean_squared_error)
	27.81s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-471.6632	 = Validation score   (-root_mean_squared_error)
	29.93s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-477.8318	 = Validation score   (-root_mean_squared_error)
	10.06s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-474.8031	 = Validation score   (-root_mean_squared_error)
	34.19s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-473.3299	 = Validation score   (-root_mean_squared_error)
	44.11s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T13 ...
	-476.751	 = Validation score   (-root_mean_squared_error)
	9.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T14 ...
	-484.4406	 = Validation score   (-root_mean_squared_error)
	6.62s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T15 ...
	-472.8946	 = Validation score   (-root_mean_squared_error)
	39.02s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T16 ...
	-477.7851	 = Validation score   (-root_mean_squared_error)
	8.84s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T17 ...
	-473.6195	 = Validation score   (-root_mean_squared_error)
	6.87s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T18 ...
	-472.321	 = Validation score   (-root_mean_squared_error)
	45.1s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T19 ...
	-472.6809	 = Validation score   (-root_mean_squared_error)
	28.94s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T20 ...
	-475.3244	 = Validation score   (-root_mean_squared_error)
	22.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T21 ...
	-476.4972	 = Validation score   (-root_mean_squared_error)
	24.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T22 ...
	-474.377	 = Validation score   (-root_mean_squared_error)
	23.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T23 ...
	-472.1787	 = Validation score   (-root_mean_squared_error)
	23.25s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T24 ...
	-477.8388	 = Validation score   (-root_mean_squared_error)
	8.83s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T25 ...
	-473.4929	 = Validation score   (-root_mean_squared_error)
	9.46s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1080.26s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.2 GB
	Ensemble Weights: {'CatBoost/T9': 0.35, 'LightGBM/T13': 0.3, 'CatBoost/T23': 0.2, 'LightGBM/T19': 0.15}
	-469.4418	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 719.78s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 55181.1 rows/s (4996 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp7_categorical_final")

Saved diagnostics to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_7_autogluon_categorical_clean_predictions.csv
Saved 50,000 competition predictions to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_7_autogluon_categorical_clean_submission.csv

   Id    Predicted
0   0  2733.381836
1   1  3624.259277
2   2  3196.371582
3   3  3165.918213
4   4  3300.301270