# Experiment 7: AutoGluon feature-subset comparison

This experiment compares the full shared-preprocessor feature set against correlation-guided subsets. Every model uses the same chronological validation split and the same untuned GBM plus CatBoost AutoGluon ensemble. Each subset is then refit on all labelled rows, and the final cell compares their modified-test proxy RMSE.

In [1]:
# If needed: pip install autogluon.tabular
from pathlib import Path
import os
import sys
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

configured_root = os.environ.get('KDDM_PROJECT_ROOT')
candidate_roots = ([Path(configured_root)] if configured_root else []) + [
    Path.cwd(), *Path.cwd().parents, Path('/content/KDDM-project'),
    Path('/content/drive/MyDrive/KDDM-project'),
]
project_root = next((p for p in candidate_roots if (p / 'exploration/metul/preprocessing.py').exists()), None)
if project_root is None:
    raise FileNotFoundError('Set KDDM_PROJECT_ROOT to the project directory.')
experiment_dir = project_root / 'exploration' / 'metul'
sys.path.insert(0, str(experiment_dir))

from autogluon.tabular import TabularPredictor
from preprocessing import RentalPreprocessor, load_datasets

RANDOM_STATE = 42
TARGET = 'MONTHLY_RENT'
TIME_LIMIT_SECONDS = int(os.environ.get('AUTOGLUON_TIME_LIMIT', '600'))
RUN_ID = os.environ.get('AUTOGLUON_RUN_ID', pd.Timestamp.now().strftime('%Y%m%d_%H%M%S'))

# Deliberately no hyperparameter tuning: use AutoGluon's default GBM/CatBoost settings.
MODEL_HYPERPARAMETERS = {'GBM': {}, 'CAT': {}}

In [2]:
data_dir, datasets = load_datasets(project_root / 'data')
raw_train = datasets['train'].copy()
raw_test = datasets['test'].copy()
raw_train['period'] = pd.to_datetime(raw_train['RENT_APPROVAL_DATE'] + '-01')
raw_test['period'] = pd.to_datetime(raw_test['RENT_APPROVAL_DATE'] + '-01')

# Same 80/20 chronological validation convention as the earlier AutoGluon experiments.
periods = np.sort(raw_train['period'].unique())
validation_cutoff = pd.Timestamp(periods[int(len(periods) * 0.80)])
raw_fit = raw_train.loc[raw_train['period'] < validation_cutoff].drop(columns='period').copy()
raw_valid = raw_train.loc[raw_train['period'] >= validation_cutoff].drop(columns='period').copy()

# Fit preprocessing only on the earlier validation period, then fit separately on all train rows for test predictions.
validation_preprocessor = RentalPreprocessor(datasets)
fit_df = validation_preprocessor.fit_transform(raw_fit)
valid_df = validation_preprocessor.transform(raw_valid)

final_preprocessor = RentalPreprocessor(datasets)
full_train_df = final_preprocessor.fit_transform(raw_train.drop(columns='period'))
test_df = final_preprocessor.transform(raw_test.drop(columns='period'))

print(f'Validation cutoff: {validation_cutoff:%Y-%m}')
print(f'Fit rows: {fit_df.shape}; validation rows: {valid_df.shape}')
print(f'Full train: {full_train_df.shape}; test: {test_df.shape}')

[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2585 -> 2585 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1109 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2720 -> 2720 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1146 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2720 -> 2720 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1146 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2660 -> 2660 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1129 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
Validation cutoff: 2024-05
Fit rows: (117988, 32); validation rows: (32012, 32)
Full train: (150000, 32); test: (50000, 31)

In [3]:
def prepare_subset(frame, feature_columns):
    result = frame.loc[:, feature_columns].copy()
    if 'RENT_APPROVAL_DATE' in result.columns:
        result['RENT_APPROVAL_DATE'] = pd.to_datetime(result['RENT_APPROVAL_DATE'] + '-01')
    return result

all_preprocessed_features = [column for column in full_train_df.columns if column != TARGET]

# Retains the strongest, non-duplicative signals from the correlation audit.
compact_nonredundant_features = [
    'TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL',
    'FLOOR_AREA_SQM', 'approval_date_num', 'approval_month',
    'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR',
    'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', 'mall_dist_nearest_km',
]

# Future-only ablations: approval_month is retained for recurring seasonality.
compact_no_approval_date_features = [
    column for column in compact_nonredundant_features
    if column != 'approval_date_num'
]
compact_no_coordinates_features = [
    column for column in compact_nonredundant_features
    if column not in {'LATITUDE', 'LONGITUDE'}
]

# Adds weaker but plausible candidates as one group, so their net validation effect is measurable.
compact_plus_candidates_features = compact_nonredundant_features + [
    'REGION', 'stock_close_mean', 'stock_volume_mean',
    'mrt_within_1km', 'mrt_within_2km',
    'mall_within_1km', 'mall_within_2km',
    'school_dist_nearest_km', 'school_within_1km', 'school_within_2km',
]

FEATURE_SUBSETS = {
    'full_preprocessed': all_preprocessed_features,
    'compact_nonredundant': compact_nonredundant_features,
    # 'compact_no_approval_date': compact_no_approval_date_features,
    'compact_no_coordinates': compact_no_coordinates_features,
    'compact_plus_candidates': compact_plus_candidates_features,
}

for subset_name, columns in FEATURE_SUBSETS.items():
    missing = set(columns) - set(full_train_df.columns) - {TARGET}
    if missing:
        raise ValueError(f'{subset_name} references missing preprocessed features: {sorted(missing)}')
    if len(columns) != len(set(columns)):
        raise ValueError(f'{subset_name} contains duplicate feature names.')

subset_summary = pd.DataFrame([
    {'feature_subset': name, 'feature_count': len(columns), 'features': ', '.join(columns)}
    for name, columns in FEATURE_SUBSETS.items()
])
display(subset_summary)

y_fit = fit_df[TARGET].astype(float)
y_valid = valid_df[TARGET].astype(float)
y_full = full_train_df[TARGET].astype(float)

,feature_subset,feature_count,features
0,full_preprocessed,31,"RENT_APPROVAL_DATE, TOWN, BLOCK, STREET, FLAT_..."
1,compact_nonredundant,15,"TOWN, BLOCK, STREET, FLAT_TYPE, FLAT_MODEL, FL..."
2,compact_no_coordinates,13,"TOWN, BLOCK, STREET, FLAT_TYPE, FLAT_MODEL, FL..."
3,compact_plus_candidates,25,"TOWN, BLOCK, STREET, FLAT_TYPE, FLAT_MODEL, FL..."

In [4]:
validation_results = []
validation_predictors = {}

for subset_name, columns in FEATURE_SUBSETS.items():
    X_fit = prepare_subset(fit_df, columns)
    X_valid = prepare_subset(valid_df, columns)
    predictor = TabularPredictor(
        label=TARGET,
        problem_type='regression',
        eval_metric='root_mean_squared_error',
        path=str(experiment_dir / 'ag_feature_subset_models' / RUN_ID / f'validation_{subset_name}'),
    ).fit(
        train_data=X_fit.assign(**{TARGET: y_fit.to_numpy()}),
        tuning_data=X_valid.assign(**{TARGET: y_valid.to_numpy()}),
        hyperparameters=MODEL_HYPERPARAMETERS,
        presets='medium_quality',
        time_limit=TIME_LIMIT_SECONDS,
        verbosity=2,
    )
    predictions = predictor.predict(X_valid).astype(float).clip(lower=0)
    validation_predictors[subset_name] = predictor
    validation_results.append({
        'feature_subset': subset_name,
        'feature_count': len(columns),
        'RMSE': mean_squared_error(y_valid, predictions) ** 0.5,
        'MAE': mean_absolute_error(y_valid, predictions),
        'R2': r2_score(y_valid, predictions),
    })

validation_metrics = pd.DataFrame(validation_results).sort_values('RMSE').reset_index(drop=True)
display(validation_metrics)
print('Select the preferred subset from chronological validation before interpreting modified-test proxy RMSE.')

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.03 GB / 16.00 GB (25.2%)
Disk Space Avail:   191.18 GB / 460.38 GB (41.5%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/validation_full_preprocessed"
Train Data Rows:    117988
Train Data Columns: 31
Tuning Data Rows:    32012
Tuning Data Columns: 31
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4209.73 MB
	Train Data (Original)  Memory Usage: 79.00 MB (1.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 5 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('datetime', [])     :  1 | ['RENT_APPROVAL_DATE']
		('float', [])        : 12 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'MAX_FLOOR', 'YEAR_COMPLETED', ...]
		('int', [])          : 12 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('object', ['text']) :  1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('category', ['text_as_category'])  :  1 | ['STREET']
		('float', [])                       : 12 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'MAX_FLOOR', 'YEAR_COMPLETED', ...]
		('int', [])                         : 12 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('int', ['binned', 'text_special']) :  6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['datetime_as_int'])        :  2 | ['RENT_APPROVAL_DATE', 'RENT_APPROVAL_DATE.dayofweek']
		('int', ['text_ngram'])             :  6 | ['__nlp__.avenue', '__nlp__.drive', '__nlp__.road', '__nlp__.street', '__nlp__.west', ...]
	1.5s = Fit runtime
	31 features in original data used to generate 44 features in processed data.
	Train Data (Processed) Memory Usage: 33.48 MB (0.8% of available memory)
Data preprocessing and feature engineering runtime = 1.53s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 598.47s of the 598.47s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.2/4.0 GB
	-475.5137	 = Validation score   (-root_mean_squared_error)
	2.49s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 595.89s of the 595.89s of remaining time.
	Fitting with cpus=10, gpus=0
	-468.9608	 = Validation score   (-root_mean_squared_error)
	99.48s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 496.26s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.9 GB
	Ensemble Weights: {'CatBoost': 0.7, 'LightGBM': 0.3}
	-467.5071	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 103.86s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 158877.7 rows/s (32012 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/validation_full_preprocessed")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.92 GB / 16.00 GB (24.5%)
Disk Space Avail:   191.10 GB / 460.38 GB (41.5%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/validation_compact_nonredundant"
Train Data Rows:    117988
Train Data Columns: 15
Tuning Data Rows:    32012
Tuning Data Columns: 15
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4060.96 MB
	Train Data (Original)  Memory Usage: 52.93 MB (1.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 3 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'LATITUDE', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('object', ['text']) : 1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('category', ['text_as_category'])  : 1 | ['STREET']
		('float', [])                       : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'LATITUDE', ...]
		('int', [])                         : 2 | ['approval_date_num', 'approval_month']
		('int', ['binned', 'text_special']) : 6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['text_ngram'])             : 4 | ['__nlp__.avenue', '__nlp__.road', '__nlp__.street', '__nlp__._total_']
	1.5s = Fit runtime
	15 features in original data used to generate 25 features in processed data.
	Train Data (Processed) Memory Usage: 14.45 MB (0.4% of available memory)
Data preprocessing and feature engineering runtime = 1.55s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 598.45s of the 598.45s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/3.9 GB
	-475.3257	 = Validation score   (-root_mean_squared_error)
	2.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 596.33s of the 596.33s of remaining time.
	Fitting with cpus=10, gpus=0
	-469.2816	 = Validation score   (-root_mean_squared_error)
	92.66s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 503.51s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.9 GB
	Ensemble Weights: {'CatBoost': 0.68, 'LightGBM': 0.32}
	-467.48	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 96.51s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 156396.4 rows/s (32012 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/validation_compact_nonredundant")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.81 GB / 16.00 GB (23.8%)
Disk Space Avail:   191.05 GB / 460.38 GB (41.5%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/validation_compact_no_coordinates"
Train Data Rows:    117988
Train Data Columns: 13
Tuning Data Rows:    32012
Tuning Data Columns: 13
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3957.39 MB
	Train Data (Original)  Memory Usage: 50.64 MB (1.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 3 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('object', ['text']) : 1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('category', ['text_as_category'])  : 1 | ['STREET']
		('float', [])                       : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                         : 2 | ['approval_date_num', 'approval_month']
		('int', ['binned', 'text_special']) : 6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['text_ngram'])             : 4 | ['__nlp__.avenue', '__nlp__.road', '__nlp__.street', '__nlp__._total_']
	1.4s = Fit runtime
	13 features in original data used to generate 23 features in processed data.
	Train Data (Processed) Memory Usage: 12.16 MB (0.3% of available memory)
Data preprocessing and feature engineering runtime = 1.46s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 598.54s of the 598.54s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/3.8 GB
	-475.1032	 = Validation score   (-root_mean_squared_error)
	2.53s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 595.90s of the 595.90s of remaining time.
	Fitting with cpus=10, gpus=0
	-469.583	 = Validation score   (-root_mean_squared_error)
	76.14s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 519.63s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.9 GB
	Ensemble Weights: {'CatBoost': 0.647, 'LightGBM': 0.353}
	-467.2304	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 80.39s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 160062.6 rows/s (32012 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/validation_compact_no_coordinates")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.91 GB / 16.00 GB (24.4%)
Disk Space Avail:   191.00 GB / 460.38 GB (41.5%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/validation_compact_plus_candidates"
Train Data Rows:    117988
Train Data Columns: 25
Tuning Data Rows:    32012
Tuning Data Columns: 25
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4046.01 MB
	Train Data (Original)  Memory Usage: 72.13 MB (1.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 3 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 11 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'LATITUDE', ...]
		('int', [])          :  8 | ['approval_date_num', 'approval_month', 'mrt_within_1km', 'mrt_within_2km', 'mall_within_1km', ...]
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('object', ['text']) :  1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('category', ['text_as_category'])  :  1 | ['STREET']
		('float', [])                       : 11 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'LATITUDE', ...]
		('int', [])                         :  8 | ['approval_date_num', 'approval_month', 'mrt_within_1km', 'mrt_within_2km', 'mall_within_1km', ...]
		('int', ['binned', 'text_special']) :  6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['text_ngram'])             :  4 | ['__nlp__.avenue', '__nlp__.road', '__nlp__.street', '__nlp__._total_']
	1.5s = Fit runtime
	25 features in original data used to generate 35 features in processed data.
	Train Data (Processed) Memory Usage: 24.89 MB (0.6% of available memory)
Data preprocessing and feature engineering runtime = 1.51s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'

            feature_subset  feature_count        RMSE         MAE        R2
0   compact_no_coordinates             13  467.230403  345.659305  0.494243
1     compact_nonredundant             15  467.480018  345.786155  0.493703
2        full_preprocessed             31  467.507114  346.646881  0.493644
3  compact_plus_candidates             25  468.303867  348.313518  0.491917

Select the preferred subset from chronological validation before interpreting modified-test proxy RMSE.

In [5]:
test_prediction_frame = pd.DataFrame({'Id': raw_test.index})
competition_submissions = {}

for subset_name, columns in FEATURE_SUBSETS.items():
    X_full = prepare_subset(full_train_df, columns)
    X_test = prepare_subset(test_df, columns)
    predictor = TabularPredictor(
        label=TARGET,
        problem_type='regression',
        eval_metric='root_mean_squared_error',
        path=str(experiment_dir / 'ag_feature_subset_models' / RUN_ID / f'final_{subset_name}'),
    ).fit(
        train_data=X_full.assign(**{TARGET: y_full.to_numpy()}),
        hyperparameters=MODEL_HYPERPARAMETERS,
        presets='medium_quality',
        time_limit=TIME_LIMIT_SECONDS,
        verbosity=2,
    )
    predictions = predictor.predict(X_test).astype(float).clip(lower=0)
    test_prediction_frame[subset_name] = predictions.to_numpy()
    submission = pd.DataFrame({'Id': raw_test.index, 'Predicted': predictions.to_numpy()})
    competition_submissions[subset_name] = submission
    submission_path = experiment_dir / f'exp_7_autogluon_{subset_name}_submission.csv'
    submission.to_csv(submission_path, index=False)
    print(f'Saved {subset_name} submission to {submission_path}')

comparison_prediction_path = experiment_dir / 'exp_7_autogluon_feature_subset_test_predictions.csv'
test_prediction_frame.to_csv(comparison_prediction_path, index=False)
display(test_prediction_frame.head())

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.72 GB / 16.00 GB (23.3%)
Disk Space Avail:   190.95 GB / 460.38 GB (41.5%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_full_preprocessed"
Train Data Rows:    150000
Train Data Columns: 31
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3878.11 MB
	Train Data (Original)  Memory Usage: 79.00 MB (2.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 2 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('datetime', [])     :  1 | ['RENT_APPROVAL_DATE']
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', ...]
		('int', [])          : 14 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('object', ['text']) :  1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('category', ['text_as_category'])  :  1 | ['STREET']
		('float', [])                       : 10 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', ...]
		('int', [])                         : 14 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('int', ['binned', 'text_special']) :  6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['datetime_as_int'])        :  2 | ['RENT_APPROVAL_DATE', 'RENT_APPROVAL_DATE.dayofweek']
		('int', ['text_ngram'])             :  3 | ['__nlp__.avenue', '__nlp__.street', '__nlp__._total_']
	1.5s = Fit runtime
	31 features in original data used to generate 41 features in processed data.
	Train Data (Processed) Memory Usage: 32.62 MB (0.8% of available memory)
Data preprocessing and feature engineering runtime = 1.52s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0167, Train Rows: 147495, Val Rows: 2505
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 598.48s of the 598.48s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.2/3.6 GB
	-452.4554	 = Validation score   (-root_mean_squared_error)
	2.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 595.73s of the 595.73s of remaining time.
	Fitting with cpus=10, gpus=0
	-450.2387	 = Validation score   (-root_mean_squared_error)
	169.25s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 426.41s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.6 GB
	Ensemble Weights: {'CatBoost': 0.6, 'LightGBM': 0.4}
	-448.4327	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 173.62s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 78110.6 rows/s (2505 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_full_preprocessed")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.58 GB / 16.00 GB (22.4%)
Disk Space Avail:   190.87 GB / 460.38 GB (41.5%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_compact_nonredundant"
Train Data Rows:    150000
Train Data Columns: 15
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3721.32 MB
	Train Data (Original)  Memory Usage: 52.93 MB (1.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...

Saved full_preprocessed submission to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_7_autogluon_full_preprocessed_submission.csv

	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 3 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', ...]
		('int', [])          : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('object', [])       : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('object', ['text']) : 1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('category', ['text_as_category'])  : 1 | ['STREET']
		('float', [])                       : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', ...]
		('int', [])                         : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('int', ['binned', 'text_special']) : 6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['text_ngram'])             : 4 | ['__nlp__.avenue', '__nlp__.road', '__nlp__.street', '__nlp__._total_']
	1.5s = Fit runtime
	15 features in original data used to generate 25 features in processed data.
	Train Data (Processed) Memory Usage: 14.45 MB (0.4% of available memory)
Data preprocessing and feature engineering runtime = 1.51s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0167, Train Rows: 147495, Val Rows: 2505
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 598.49s of the 598.49s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/3.6 GB
	-451.9251	 = Validation score   (-root_mean_squared_error)
	4.85s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 593.60s of the 593.60s of remaining time.
	Fitting with cpus=10, gpus=0
	-450.0674	 = Validation score   (-root_mean_squared_error)
	234.14s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 359.26s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.2 GB
	Ensemble Weights: {'CatBoost': 0.579, 'LightGBM': 0.421}
	-447.8399	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 240.77s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 45139.4 rows/s (2505 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_compact_nonredundant")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.22 GB / 16.00 GB (20.1%)
Disk Space Avail:   190.74 GB / 460.38 GB (41.4%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_compact_no_coordinates"
Train Data Rows:    150000
Train Data Columns: 13
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3315.11 MB
	Train Data (Original)  Memory Usage: 50.64 MB (1.5% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.

Saved compact_nonredundant submission to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_7_autogluon_compact_nonredundant_submission.csv

	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 3 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 4 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km']
		('int', [])          : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('object', [])       : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('object', ['text']) : 1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    : 4 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL']
		('category', ['text_as_category'])  : 1 | ['STREET']
		('float', [])                       : 4 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km']
		('int', [])                         : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('int', ['binned', 'text_special']) : 6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['text_ngram'])             : 4 | ['__nlp__.avenue', '__nlp__.road', '__nlp__.street', '__nlp__._total_']
	1.6s = Fit runtime
	13 features in original data used to generate 23 features in processed data.
	Train Data (Processed) Memory Usage: 12.16 MB (0.4% of available memory)
Data preprocessing and feature engineering runtime = 1.61s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0167, Train Rows: 147495, Val Rows: 2505
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 598.39s of the 598.39s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/3.2 GB
	-452.8631	 = Validation score   (-root_mean_squared_error)
	3.33s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 595.03s of the 595.03s of remaining time.
	Fitting with cpus=10, gpus=0
	-451.8064	 = Validation score   (-root_mean_squared_error)
	224.45s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 370.35s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.5 GB
	Ensemble Weights: {'CatBoost': 0.542, 'LightGBM': 0.458}
	-449.2634	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 229.68s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 54179.6 rows/s (2505 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_compact_no_coordinates")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.54 GB / 16.00 GB (22.1%)
Disk Space Avail:   190.62 GB / 460.38 GB (41.4%)
===================================================
Presets specified: ['medium_quality']
Beginning AutoGluon training ... Time limit = 600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_compact_plus_candidates"
Train Data Rows:    150000
Train Data Columns: 25
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3694.27 MB
	Train Data (Original)  Memory Usage: 72.13 MB (2.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.

Saved compact_no_coordinates submission to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_7_autogluon_compact_no_coordinates_submission.csv

	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting TextSpecialFeatureGenerator...
			Fitting BinnedFeatureGenerator...
			Fitting DropDuplicatesFeatureGenerator...
		Fitting TextNgramFeatureGenerator...
			Fitting CountVectorizer for text features: ['STREET']
			CountVectorizer fit with vocabulary size = 9
		Warning: Due to memory constraints, ngram feature count is being reduced. Allocate more memory to maximize model quality.
		Reducing Vectorizer vocab size from 9 to 2 to avoid OOM error
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        :  9 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', ...]
		('int', [])          : 10 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_within_1km', ...]
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('object', ['text']) :  1 | ['STREET']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                    :  5 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'REGION']
		('category', ['text_as_category'])  :  1 | ['STREET']
		('float', [])                       :  9 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', ...]
		('int', [])                         : 10 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_within_1km', ...]
		('int', ['binned', 'text_special']) :  6 | ['STREET.char_count', 'STREET.word_count', 'STREET.lower_ratio', 'STREET.digit_ratio', 'STREET.special_ratio', ...]
		('int', ['text_ngram'])             :  3 | ['__nlp__.avenue', '__nlp__.street', '__nlp__._total_']
	1.6s = Fit runtime
	25 features in original data used to generate 34 features in processed data.
	Train Data (Processed) Memory Usage: 24.61 MB (0.7% of available memory)
Data preprocessing and feature engineering runtime = 1.64s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0167, Train Rows: 147495, Val Rows: 2505
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 598.36s of the 598.36s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.2/3.4 GB
	-452.2221	 = Validation score   (-root_mean_squared_error)
	3.62s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 594.71s of the 594.71s of remaining time.
	Fitting with cpus=10, gpus=0
	-449.8263	 = Validation score   (-root_mean_squared_error)
	159.95s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 434.70s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.4 GB
	Ensemble Weights: {'CatBoost': 0.609, 'LightGBM': 0.391}
	-448.093	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 165.33s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 77594.9 rows/s (2505 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_feature_subset_models/20260922_171439/final_compact_plus_candidates")

Saved compact_plus_candidates submission to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_7_autogluon_compact_plus_candidates_submission.csv

,Id,full_preprocessed,compact_nonredundant,compact_no_coordinates,compact_plus_candidates
0,0,2790.023438,2773.601807,2765.013672,2759.389404
1,1,3642.981445,3644.737061,3618.741455,3669.272949
2,2,3185.030029,3211.164307,3230.654297,3226.633057
3,3,3134.428223,3149.320801,3131.618408,3162.478760
4,4,3268.248291,3253.361572,3240.814453,3281.963623