# Experiment 15 — Flat-type segmented AutoGluon residual models

Layer 1 is the saved Exp 14 AutoGluon rent ensemble. OOF residuals are deterministically divided into four observable flat-type segments: executive, 5-room, 4-room, and 1–3-room. Each segment receives its own AutoGluon GBM + CatBoost residual ensemble. Segment-specific residual weights are selected on the latest OOF fold, then the experts are refit on all OOF residual rows and evaluated on untouched outer validation.

In [1]:
from pathlib import Path
import json,os,sys
import numpy as np
import pandas as pd
from autogluon.tabular import TabularPredictor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import TimeSeriesSplit
configured_root=os.environ.get('KDDM_PROJECT_ROOT')
roots=([Path(configured_root)] if configured_root else [])+[Path.cwd(),*Path.cwd().parents]
project_root=next((root for root in roots if (root/'exploration/metul/preprocessing.py').exists()),None)
if project_root is None:raise FileNotFoundError('Set KDDM_PROJECT_ROOT to the project directory.')
sys.path.insert(0,str(project_root/'exploration'/'metul'))
from preprocessing import RentalPreprocessor,load_datasets
TARGET='MONTHLY_RENT';RESIDUAL_TARGET='layer1_residual';N_SPLITS=3
TIME_LIMIT=int(os.environ.get('EXP15_TIME_LIMIT','300'))
RUN_ID=os.environ.get('EXP15_RUN_ID',pd.Timestamp.now().strftime('%Y%m%d_%H%M%S'))
HYPERPARAMETERS={'GBM':{},'CAT':{}}
source_nb=json.loads((project_root/'exploration'/'metul'/'exp_14_resale_features_lgbm.ipynb').read_text())
source_cells={cell.get('metadata',{}).get('id'):''.join(cell.get('source',[])) for cell in source_nb['cells']}
exec(source_cells['setup'],globals());exec(source_cells['exp9-best-feature-transformer'],globals())
model_root=project_root/'exploration'/'metul'/'ag_exp_14_ag_residual_models'
requested_run=os.environ.get('EXP15_SOURCE_RUN_ID')
if requested_run:source_run=model_root/requested_run
else:
    candidates=sorted(path for path in model_root.iterdir() if (path/'layer1_full').exists() and (path/'layer1_oof_3').exists())
    if not candidates:raise FileNotFoundError('No completed Exp 14 run found.')
    source_run=candidates[-1]
output_root=project_root/'exploration'/'metul'/'ag_exp_15_flat_type_residuals'/RUN_ID
print(f'Loading Layer 1 from {source_run.name}; saving residual experts to {output_root}')

Loading Layer 1 from 20261015_144824; saving residual experts to /Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615

In [2]:
_,datasets=load_datasets(project_root/'data')
raw=datasets['train'].copy();raw['period']=pd.to_datetime(raw['RENT_APPROVAL_DATE']+'-01').dt.to_period('M')
periods=np.sort(raw.period.unique());outer_cutoff=periods[int(len(periods)*.80)]
raw_fit,raw_valid=raw.loc[raw.period<outer_cutoff].copy(),raw.loc[raw.period>=outer_cutoff].copy()
def best_features(history,future):
    processor=RentalPreprocessor(datasets)
    history_base=processor.fit_transform(history.drop(columns=['period',TARGET],errors='ignore'))
    future_base=processor.transform(future.drop(columns=['period',TARGET],errors='ignore'))
    return make_exp9_best_features(history,future,history_base,future_base)
def predictions_and_disagreement(predictor,frame):
    prediction=predictor.predict(frame).astype(float).to_numpy()
    names=[name for name in predictor.model_names() if ('LightGBM' in name or 'CatBoost' in name) and 'WeightedEnsemble' not in name]
    components=np.vstack([predictor.predict(frame,model=name).astype(float).to_numpy() for name in names])
    disagreement=components.max(axis=0)-components.min(axis=0) if len(components)>1 else np.zeros(len(frame))
    return prediction,disagreement
def residual_segment(flat_type):
    value=str(flat_type).strip().lower()
    if value=='executive':return 'executive'
    if value=='5 room':return '5_room'
    if value=='4 room':return '4_room'
    return '1_to_3_room'
fit_periods=np.sort(raw_fit.period.unique());parts=[]
for fold,(early_index,later_index) in enumerate(TimeSeriesSplit(n_splits=N_SPLITS).split(fit_periods),1):
    early=raw_fit.loc[raw_fit.period.isin(fit_periods[early_index])].copy();later=raw_fit.loc[raw_fit.period.isin(fit_periods[later_index])].copy()
    _,later_x=best_features(early,later);model=TabularPredictor.load(str(source_run/f'layer1_oof_{fold}'))
    prediction,disagreement=predictions_and_disagreement(model,later_x)
    part=later_x.copy();part['layer1_prediction']=prediction;part['layer1_disagreement']=disagreement;part[RESIDUAL_TARGET]=later[TARGET].to_numpy()-prediction;part['fold']=fold;part['segment']=part.FLAT_TYPE.map(residual_segment)
    parts.append(part);print(f'Fold {fold}: {len(part):,} residual rows')
oof=pd.concat(parts,ignore_index=True)
fit_x,valid_x=best_features(raw_fit,raw_valid);layer1=TabularPredictor.load(str(source_run/'layer1_full'))
valid_prediction,valid_disagreement=predictions_and_disagreement(layer1,valid_x)
valid_meta=valid_x.copy();valid_meta['layer1_prediction']=valid_prediction;valid_meta['layer1_disagreement']=valid_disagreement;valid_meta['segment']=valid_meta.FLAT_TYPE.map(residual_segment)
valid_y=raw_valid[TARGET].astype(float).reset_index(drop=True)
display(oof.groupby('segment').agg(rows=(RESIDUAL_TARGET,'size'),mean_residual=(RESIDUAL_TARGET,'mean'),residual_RMSE=(RESIDUAL_TARGET,lambda values:np.sqrt(np.mean(values**2)))))

[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2432 -> 2432 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1086 -> 563 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2432 -> 2432 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1086 -> 563 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2426 -> 2426 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1092 -> 563 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
Fold 1: 28,514 residual rows
[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2569 -> 2569 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1117 -> 568 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2569 -> 2569 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1117 -> 568 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2498 -> 2498 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1089 -> 567 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
Fold 2: 27,858 residual rows
[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2651 -> 2651 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1130 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2651 -> 2651 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1130 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2558 -> 2558 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1105 -> 570 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
Fold 3: 30,051 residual rows
[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2585 -> 2585 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1109 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces

              rows  mean_residual  residual_RMSE
segment
1_to_3_room  30131     171.397193     544.818609
4_room       31148     221.210220     628.698645
5_room       20469     261.662051     653.382544
executive     4675     288.241122     720.336394

In [3]:
meta_features=BEST_FEATURES+['layer1_prediction','layer1_disagreement']
train_oof=oof.loc[oof.fold<oof.fold.max()].reset_index(drop=True);tune_oof=oof.loc[oof.fold.eq(oof.fold.max())].reset_index(drop=True)
def fit_residual_expert(frame,segment,path):
    subset=frame.loc[frame.segment.eq(segment)]
    return TabularPredictor(label=RESIDUAL_TARGET,problem_type='regression',eval_metric='root_mean_squared_error',path=str(path)).fit(train_data=subset[meta_features+[RESIDUAL_TARGET]],hyperparameters=HYPERPARAMETERS,presets=['medium_quality','ignore_text'],time_limit=TIME_LIMIT,verbosity=2)
segments=['executive','5_room','4_room','1_to_3_room'];tuning_models={};segment_weights={};weight_rows=[]
for segment in segments:
    model=fit_residual_expert(train_oof,segment,output_root/f'tuning_{segment}');tuning_models[segment]=model
    tune_subset=tune_oof.loc[tune_oof.segment.eq(segment)];residual_prediction=model.predict(tune_subset[meta_features]).astype(float).to_numpy();actual_residual=tune_subset[RESIDUAL_TARGET].to_numpy()
    denominator=np.dot(residual_prediction,residual_prediction);analytic=0.0 if denominator==0 else np.dot(actual_residual,residual_prediction)/denominator
    candidates=np.unique(np.concatenate([np.linspace(0,1.5,151),[np.clip(analytic,0,1.5)]]));scores=[mean_squared_error(actual_residual,weight*residual_prediction)**.5 for weight in candidates]
    weight=float(candidates[np.argmin(scores)]);segment_weights[segment]=weight
    weight_rows.append({'segment':segment,'train_rows':int(train_oof.segment.eq(segment).sum()),'tune_rows':len(tune_subset),'weight':weight,'uncorrected_residual_RMSE':mean_squared_error(actual_residual,np.zeros_like(actual_residual))**.5,'corrected_residual_RMSE':min(scores)})
display(pd.DataFrame(weight_rows))

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.86 GB / 16.00 GB (30.4%)
Disk Space Avail:   166.91 GB / 460.38 GB (36.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_executive"
Train Data Rows:    3104
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4969.79 MB
	Train Data (Original)  Memory Usage: 1.87 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['FLAT_TYPE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('object', ['text']) :  2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('category', ['text_as_category']) :  2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.0s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 0.31 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.05s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1611, Train Rows: 2603, Val Rows: 501
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.95s of the 299.95s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/4.8 GB
	-631.8412	 = Validation score   (-root_mean_squared_error)
	1.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 298.77s of the 298.77s of remaining time.
	Fitting with cpus=10, gpus=0
	-626.3323	 = Validation score   (-root_mean_squared_error)
	0.68s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.95s of the 298.09s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.9 GB
	Ensemble Weights: {'CatBoost': 0.909, 'LightGBM': 0.091}
	-626.2762	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.93s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 100466.0 rows/s (501 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_executive")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.90 GB / 16.00 GB (30.6%)
Disk Space Avail:   166.91 GB / 460.38 GB (36.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_5_room"
Train Data Rows:    13463
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5025.63 MB
	Train Data (Original)  Memory Usage: 8.06 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['FLAT_TYPE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('object', ['text']) :  2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('category', ['text_as_category']) :  2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 1.35 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.06s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 12116, Val Rows: 1347
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.94s of the 299.94s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/4.9 GB
	-551.2276	 = Validation score   (-root_mean_squared_error)
	1.11s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 298.82s of the 298.82s of remaining time.
	Fitting with cpus=10, gpus=0
	-551.8945	 = Validation score   (-root_mean_squared_error)
	1.55s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.94s of the 297.26s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.0 GB
	Ensemble Weights: {'LightGBM': 0.545, 'CatBoost': 0.455}
	-549.6594	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2.75s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 215006.6 rows/s (1347 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_5_room")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.98 GB / 16.00 GB (31.1%)
Disk Space Avail:   167.61 GB / 460.38 GB (36.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_4_room"
Train Data Rows:    20219
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5109.15 MB
	Train Data (Original)  Memory Usage: 12.04 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['FLAT_TYPE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('object', ['text']) :  2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('category', ['text_as_category']) :  2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 2.05 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.08s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 18197, Val Rows: 2022
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.92s of the 299.92s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/5.0 GB
	-564.7126	 = Validation score   (-root_mean_squared_error)
	0.83s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 299.09s of the 299.09s of remaining time.
	Fitting with cpus=10, gpus=0
	-559.8398	 = Validation score   (-root_mean_squared_error)
	1.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.92s of the 297.67s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.0 GB
	Ensemble Weights: {'CatBoost': 0.81, 'LightGBM': 0.19}
	-559.5379	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2.34s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 295882.6 rows/s (2022 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_4_room")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.99 GB / 16.00 GB (31.2%)
Disk Space Avail:   167.61 GB / 460.38 GB (36.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_1_to_3_room"
Train Data Rows:    19586
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5124.24 MB
	Train Data (Original)  Memory Usage: 11.61 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) :  1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) :  1 | ['nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	20 features in original data used to generate 20 features in processed data.
	Train Data (Processed) Memory Usage: 1.98 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.07s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 17627, Val Rows: 1959
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.93s of the 299.93s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/5.0 GB
	-502.4932	 = Validation score   (-root_mean_squared_error)
	0.86s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 299.06s of the 299.06s of remaining time.
	Fitting with cpus=10, gpus=0
	-492.2073	 = Validation score   (-root_mean_squared_error)
	3.53s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.93s of the 295.52s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.1 GB
	Ensemble Weights: {'CatBoost': 1.0}
	-492.2073	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 4.49s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 357930.0 rows/s (1959 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/tuning_1_to_3_room")

,segment,train_rows,tune_rows,weight,uncorrected_residual_RMSE,corrected_residual_RMSE
0,executive,3104,1571,0.199229,663.948554,653.967174
1,5_room,13463,7006,0.114456,584.588826,580.007565
2,4_room,20219,10929,0.110620,571.904488,569.590199
3,1_to_3_room,19586,10545,0.086726,521.661177,520.685990

In [4]:
final_models={};unweighted_correction=np.zeros(len(valid_meta));weighted_correction=np.zeros(len(valid_meta))
for segment in segments:
    model=fit_residual_expert(oof,segment,output_root/f'final_{segment}');final_models[segment]=model
    mask=valid_meta.segment.eq(segment).to_numpy();prediction=model.predict(valid_meta.loc[mask,meta_features]).astype(float).to_numpy()
    unweighted_correction[mask]=prediction;weighted_correction[mask]=segment_weights[segment]*prediction
unweighted_prediction=np.clip(valid_prediction+unweighted_correction,a_min=0,a_max=None);weighted_prediction=np.clip(valid_prediction+weighted_correction,a_min=0,a_max=None)
def metric(name,prediction):return {'model':name,'RMSE':mean_squared_error(valid_y,prediction)**.5,'MAE':mean_absolute_error(valid_y,prediction),'R2':r2_score(valid_y,prediction)}
comparison=pd.DataFrame([metric('Layer 1 AutoGluon',valid_prediction),metric('Unweighted flat-type residual experts',unweighted_prediction),metric('Weighted flat-type residual experts',weighted_prediction)])
display(comparison.sort_values('RMSE'))
rows=[]
for segment in segments:
    mask=valid_meta.segment.eq(segment).to_numpy();rows.append({'segment':segment,'rows':int(mask.sum()),'Layer1_RMSE':mean_squared_error(valid_y[mask],valid_prediction[mask])**.5,'Weighted_RMSE':mean_squared_error(valid_y[mask],weighted_prediction[mask])**.5,'weight':segment_weights[segment]})
display(pd.DataFrame(rows).sort_values('Weighted_RMSE'))

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       5.11 GB / 16.00 GB (31.9%)
Disk Space Avail:   167.60 GB / 460.38 GB (36.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_executive"
Train Data Rows:    4675
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5144.33 MB
	Train Data (Original)  Memory Usage: 2.82 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['FLAT_TYPE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('object', ['text']) :  2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('category', ['text_as_category']) :  2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.0s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 0.47 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.107, Train Rows: 4174, Val Rows: 501
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.96s of the 299.96s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/5.0 GB
	-655.5317	 = Validation score   (-root_mean_squared_error)
	1.18s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 298.77s of the 298.77s of remaining time.
	Fitting with cpus=10, gpus=0
	-652.1823	 = Validation score   (-root_mean_squared_error)
	0.56s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.96s of the 298.21s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.0 GB
	Ensemble Weights: {'CatBoost': 0.789, 'LightGBM': 0.211}
	-651.9258	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 1.8s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 111833.2 rows/s (501 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_executive")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       5.15 GB / 16.00 GB (32.2%)
Disk Space Avail:   167.60 GB / 460.38 GB (36.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_5_room"
Train Data Rows:    20469
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5292.79 MB
	Train Data (Original)  Memory Usage: 12.26 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['FLAT_TYPE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('object', ['text']) :  2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('category', ['text_as_category']) :  2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 2.05 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.07s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 18422, Val Rows: 2047
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.93s of the 299.93s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/5.2 GB
	-560.158	 = Validation score   (-root_mean_squared_error)
	0.83s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 299.09s of the 299.09s of remaining time.
	Fitting with cpus=10, gpus=0
	-556.8983	 = Validation score   (-root_mean_squared_error)
	1.63s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.93s of the 297.45s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.1 GB
	Ensemble Weights: {'CatBoost': 0.727, 'LightGBM': 0.273}
	-556.3688	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2.56s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 297135.8 rows/s (2047 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_5_room")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       5.11 GB / 16.00 GB (32.0%)
Disk Space Avail:   167.59 GB / 460.38 GB (36.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_4_room"
Train Data Rows:    31148
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5255.08 MB
	Train Data (Original)  Memory Usage: 18.54 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['FLAT_TYPE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('object', ['text']) :  2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  5 | ['TOWN', 'BLOCK', 'FLAT_MODEL', 'nearest_tourist_attraction_name', 'nearest_monument_name']
		('category', ['text_as_category']) :  2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	19 features in original data used to generate 19 features in processed data.
	Train Data (Processed) Memory Usage: 3.15 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.1s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0803, Train Rows: 28646, Val Rows: 2502
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.90s of the 299.90s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/5.1 GB
	-553.6668	 = Validation score   (-root_mean_squared_error)
	0.67s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 299.23s of the 299.23s of remaining time.
	Fitting with cpus=10, gpus=0
	-547.7619	 = Validation score   (-root_mean_squared_error)
	1.96s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.90s of the 297.25s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.1 GB
	Ensemble Weights: {'CatBoost': 0.864, 'LightGBM': 0.136}
	-547.6119	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2.76s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 288364.2 rows/s (2502 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_4_room")
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       5.06 GB / 16.00 GB (31.6%)
Disk Space Avail:   167.59 GB / 460.38 GB (36.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_1_to_3_room"
Train Data Rows:    30131
Train Data Columns: 20
Label Column:       layer1_residual
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5198.53 MB
	Train Data (Original)  Memory Usage: 17.87 MB (0.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          :  2 | ['approval_date_num', 'approval_month']
		('object', [])       :  7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) :  1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   :  7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) :  1 | ['nearest_mrt_name']
		('float', [])                      : 10 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        :  2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	20 features in original data used to generate 20 features in processed data.
	Train Data (Processed) Memory Usage: 3.05 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.083, Train Rows: 27630, Val Rows: 2501
User-specified model hyperparameters to be fit:
{
	'GBM': [{}],
	'CAT': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM ... Training model for up to 299.89s of the 299.89s of remaining time.
	Fitting with cpus=10, gpus=0, mem=0.1/5.1 GB
	-487.143	 = Validation score   (-root_mean_squared_error)
	0.7s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 299.18s of the 299.18s of remaining time.
	Fitting with cpus=10, gpus=0
	-481.1704	 = Validation score   (-root_mean_squared_error)
	1.6s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 299.89s of the 297.57s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.1 GB
	Ensemble Weights: {'CatBoost': 0.933, 'LightGBM': 0.067}
	-481.1374	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2.44s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 356971.2 rows/s (2501 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_15_flat_type_residuals/20261016_182615/final_1_to_3_room")

                                   model        RMSE         MAE        R2
2    Weighted flat-type residual experts  468.067517  339.893324  0.492429
0                      Layer 1 AutoGluon  468.271759  340.986810  0.491986
1  Unweighted flat-type residual experts  472.508584  337.031600  0.482752

       segment   rows  Layer1_RMSE  Weighted_RMSE    weight
3  1_to_3_room  11450   437.079647     436.856808  0.086726
2       4_room  11678   472.380743     472.007092  0.110620
1       5_room   7270   481.633730     481.994464  0.114456
0    executive   1614   578.341630     577.109151  0.199229

Each row is routed only by its cleaned `FLAT_TYPE`, which is known at inference. The saved segment weights must travel with the four expert predictors for production use. Unknown categories fall back to the `1_to_3_room` segment in this first experiment.