# Experiment 17 — HPO AutoGluon with two residual layers

This experiment applies bounded hyperparameter optimization to the final two-residual-layer design. Every layer is an AutoGluon ensemble restricted to LightGBM and CatBoost and receives the active 18-feature Experiment 9 representation.

The outer validation period is May 2024 onward. It is not used for model fitting, HPO, out-of-fold residual construction, or residual-weight selection. Within the earlier history, expanding chronological folds generate predictions for the next layer. Each fold has its own earlier-month HPO split.

Final prediction = base prediction + w1 × residual-layer-1 prediction + w2 × residual-layer-2 prediction. Both weights are estimated from chronological OOF predictions only.

**Executed result:** the HPO base ensemble scored **RMSE 470.232**, **MAE 343.271**, and **R² 0.4877**. OOF weight selection chose **w1 = 0.956** and **w2 = 0.000**; applying residual layer 1 worsened validation to **474.426 RMSE**, and layer 2 was consequently ignored. HPO and residual stacking did not improve the default 18-feature ensemble, so this run is not used as the reported best result.

In [1]:
from pathlib import Path
import json
import os
import sys

import numpy as np
import pandas as pd
from autogluon.common import space
from autogluon.tabular import TabularPredictor
from scipy.spatial import cKDTree
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import TimeSeriesSplit

configured_root = os.environ.get('KDDM_PROJECT_ROOT')
candidate_roots = ([Path(configured_root)] if configured_root else []) + [
    Path.cwd(), *Path.cwd().parents, Path('/content/KDDM-project'),
    Path('/content/drive/MyDrive/KDDM-project'),
]
project_root = next(
    (path for path in candidate_roots if (path / 'exploration/metul/preprocessing.py').exists()),
    None,
)
if project_root is None:
    raise FileNotFoundError('Set KDDM_PROJECT_ROOT to the project directory.')
experiment_dir = project_root / 'exploration' / 'metul'
sys.path.insert(0, str(experiment_dir))
from preprocessing import RentalPreprocessor, load_datasets

TARGET = 'MONTHLY_RENT'
N_SPLITS = int(os.environ.get('EXP17_OOF_SPLITS', '3'))
OOF_TRIALS_PER_MODEL = int(os.environ.get('EXP17_OOF_TRIALS_PER_MODEL', '12'))
FINAL_TRIALS_PER_MODEL = int(os.environ.get('EXP17_FINAL_TRIALS_PER_MODEL', '30'))
OOF_TIME_LIMIT = int(os.environ.get('EXP17_OOF_TIME_LIMIT', '900'))
FINAL_TIME_LIMIT = int(os.environ.get('EXP17_FINAL_TIME_LIMIT', '1800'))
RUN_ID = os.environ.get('AUTOGLUON_RUN_ID', pd.Timestamp.now().strftime('%Y%m%d_%H%M%S'))
MODEL_ROOT = experiment_dir / 'ag_exp_17_two_residual_hpt' / RUN_ID

COMPACT_FEATURES = [
    'TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', 'FLOOR_AREA_SQM',
    'approval_date_num', 'approval_month', 'coe_quota_premium_mean',
    'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', 'mall_dist_nearest_km',
]
TARGET_FEATURES = [
    'monthly_target_lag', 'town_flat_type_target_mean', 'nearest_mrt_name',
    'nearest_tourist_attraction_name', 'nearest_monument_name',
]
BEST_FEATURES = COMPACT_FEATURES + TARGET_FEATURES

print(f'Project root: {project_root}')
print(f'Model output: {MODEL_ROOT}')
print(
    f'OOF HPO: {OOF_TRIALS_PER_MODEL} trials/model, {OOF_TIME_LIMIT}s per fit; '
    f'final HPO: {FINAL_TRIALS_PER_MODEL} trials/model, {FINAL_TIME_LIMIT}s per layer.'
)

Project root: /Users/metul/Desktop/KDDM-project
Model output: /Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932
OOF HPO: 12 trials/model, 900s per fit; final HPO: 30 trials/model, 1800s per layer.

## HPO search space

The ranges are deliberately bounded. They cover shallow through moderately complex trees and short through long boosting schedules without allowing extreme depths or leaf counts that are unlikely to generalize chronologically. Learning rate and regularization are searched logarithmically. `num_iterations` is tuned for LightGBM and `iterations` for CatBoost.

In [2]:
HPO_HYPERPARAMETERS = {
    'GBM': {
        'num_leaves': space.Int(24, 500),
        'num_iterations': space.Int(100, 1000),
        'learning_rate': space.Real(0.01, 0.12, log=True),
        'min_data_in_leaf': space.Int(20, 250),
        'feature_fraction': space.Real(0.70, 1.00),
        'bagging_fraction': space.Real(0.70, 1.00),
        'bagging_freq': 1,
        'lambda_l1': space.Real(1e-4, 20.0, log=True),
        'lambda_l2': space.Real(1e-4, 20.0, log=True),
    },
    'CAT': {
        'depth': space.Int(5, 10),
        'iterations': space.Int(100, 1000),
        'learning_rate': space.Real(0.01, 0.12, log=True),
        'l2_leaf_reg': space.Real(1.0, 30.0, log=True),
        'random_strength': space.Real(1e-3, 10.0, log=True),
        'bagging_temperature': space.Real(0.0, 1.5),
    },
}

def hpo_kwargs(trials_per_model):
    return {
        'num_trials': trials_per_model,
        'scheduler': 'local',
        'searcher': 'random',
    }

display(pd.DataFrame({
    'setting': ['OOF folds', 'OOF trials per model', 'final trials per model', 'OOF seconds per fit', 'final seconds per layer'],
    'value': [N_SPLITS, OOF_TRIALS_PER_MODEL, FINAL_TRIALS_PER_MODEL, OOF_TIME_LIMIT, FINAL_TIME_LIMIT],
}))

                   setting  value
0                OOF folds      3
1     OOF trials per model     12
2   final trials per model     30
3      OOF seconds per fit    900
4  final seconds per layer   1800

## Leakage-safe feature construction

The 24-month global lag and town × flat-type mean use labelled history only. Training rows use prior months; future rows use mappings fitted on the complete permitted history. Nearest-place names are deterministic functions of fitted coordinates and external point files.

In [3]:
class RentalTargetFeatureTransformer:
    def fit(self, history):
        self.global_mean_ = float(history[TARGET].mean())
        self.group_mean_ = history.groupby(['TOWN', 'FLAT_TYPE'])[TARGET].mean()
        self.monthly_mean_ = history.groupby('period')[TARGET].mean()
        return self

    def transform(self, frame):
        result = frame[['TOWN', 'FLAT_TYPE', 'period']].copy()
        result['monthly_target_lag'] = (
            (result['period'] - 24).map(self.monthly_mean_).fillna(self.global_mean_)
        )
        keys = result.set_index(['TOWN', 'FLAT_TYPE']).index
        group_mean = pd.Series(keys.map(self.group_mean_), index=result.index)
        result['town_flat_type_target_mean'] = group_mean.fillna(self.global_mean_)
        return result[['monthly_target_lag', 'town_flat_type_target_mean']]

    def fit_transform_train(self, history):
        self.fit(history)
        grouped = (
            history.groupby(['TOWN', 'FLAT_TYPE', 'period'], as_index=False)[TARGET]
            .agg(['sum', 'count']).reset_index()
            .sort_values(['TOWN', 'FLAT_TYPE', 'period'])
        )
        grouped['prior_sum'] = grouped.groupby(['TOWN', 'FLAT_TYPE'])['sum'].cumsum() - grouped['sum']
        grouped['prior_count'] = grouped.groupby(['TOWN', 'FLAT_TYPE'])['count'].cumsum() - grouped['count']
        grouped['town_flat_type_target_mean'] = (
            grouped['prior_sum'] / grouped['prior_count'].replace(0, np.nan)
        )
        monthly = history.groupby('period')[TARGET].agg(['sum', 'count']).sort_index()
        global_prior = (
            (monthly['sum'].cumsum() - monthly['sum'])
            / (monthly['count'].cumsum() - monthly['count']).replace(0, np.nan)
        )
        result = history[['TOWN', 'FLAT_TYPE', 'period']].merge(
            grouped[['TOWN', 'FLAT_TYPE', 'period', 'town_flat_type_target_mean']],
            on=['TOWN', 'FLAT_TYPE', 'period'], how='left',
        )
        result['town_flat_type_target_mean'] = (
            result['town_flat_type_target_mean'].fillna(result['period'].map(global_prior))
        )
        result['monthly_target_lag'] = (
            (result['period'] - 24).map(self.monthly_mean_).fillna(result['period'].map(global_prior))
        )
        return result[['monthly_target_lag', 'town_flat_type_target_mean']]

def nearest_mrt_name(base, datasets):
    stations = datasets['mrt'][['NAME', 'LATITUDE', 'LONGITUDE']].dropna()
    _, index = cKDTree(
        stations[['LATITUDE', 'LONGITUDE']].to_numpy() * [111.0, 110.96]
    ).query(base[['LATITUDE', 'LONGITUDE']].to_numpy() * [111.0, 110.96])
    return pd.Series(stations['NAME'].astype(object).to_numpy()[index], name='nearest_mrt_name')

def nearest_geojson_name(base, filename, field, output_name):
    path = project_root / 'data' / 'possible_additional_features' / filename
    with path.open() as handle:
        geojson = json.load(handle)
    points = pd.DataFrame([
        {
            'longitude': item['geometry']['coordinates'][0],
            'latitude': item['geometry']['coordinates'][1],
            output_name: item['properties'][field],
        }
        for item in geojson['features']
        if item.get('geometry', {}).get('type') == 'Point'
    ]).dropna()
    _, index = cKDTree(
        points[['longitude', 'latitude']].to_numpy() * [110.96, 111.0]
    ).query(base[['LONGITUDE', 'LATITUDE']].to_numpy() * [110.96, 111.0])
    return pd.Series(points[output_name].astype(object).to_numpy()[index], name=output_name)

def make_best_features(raw_history, raw_future, datasets):
    preprocessor = RentalPreprocessor(datasets)
    history_base = preprocessor.fit_transform(
        raw_history.drop(columns=['period', TARGET], errors='ignore')
    )
    future_base = preprocessor.transform(
        raw_future.drop(columns=['period', TARGET], errors='ignore')
    )
    history = history_base[['TOWN', 'FLAT_TYPE']].reset_index(drop=True).assign(
        period=raw_history['period'].to_numpy(),
        **{TARGET: raw_history[TARGET].to_numpy()},
    )
    future = future_base[['TOWN', 'FLAT_TYPE']].reset_index(drop=True).assign(
        period=raw_future['period'].to_numpy(),
    )
    target_transformer = RentalTargetFeatureTransformer()
    history_target = target_transformer.fit_transform_train(history)
    future_target = target_transformer.transform(future)

    def combine(base, target_features):
        result = pd.concat([
            base[COMPACT_FEATURES].reset_index(drop=True),
            target_features.reset_index(drop=True),
            nearest_mrt_name(base, datasets).reset_index(drop=True),
            nearest_geojson_name(
                base, 'TouristAttractions.geojson', 'PAGETITLE',
                'nearest_tourist_attraction_name',
            ).reset_index(drop=True),
            nearest_geojson_name(
                base, 'MonumentsGEOJSON.geojson', 'NAME',
                'nearest_monument_name',
            ).reset_index(drop=True),
        ], axis=1)
        return result[BEST_FEATURES]

    return combine(history_base, history_target), combine(future_base, future_target)

## Nested chronological HPO and stacking helpers

`fit_hpo_predictor` reserves the latest part of the supplied history as an inner HPO window and refits the selected model on all supplied rows. `chronological_oof_hpo` then predicts later months from earlier months only. The same mechanism is used for the base and both residual targets.

In [11]:
def fit_hpo_predictor(x, y, periods, label, path, trials_per_model, time_limit):
    x = x.reset_index(drop=True)
    y = pd.Series(y).astype(float).reset_index(drop=True)
    periods = pd.Series(periods).reset_index(drop=True)
    unique_periods = np.sort(periods.unique())
    if len(unique_periods) < 3:
        raise ValueError(
            f'Need at least 3 months for chronological HPO; found {len(unique_periods)}.'
        )
    # Later residual layers contain fewer OOF months. Keep at least two months
    # for fitting and use an adaptive final-month tuning window. A single
    # tuning month still contains many listing rows in this dataset.
    tune_months = min(12, max(1, len(unique_periods) // 5))
    tune_periods = unique_periods[-tune_months:]
    tune_mask = periods.isin(tune_periods).to_numpy()
    train_data = x.loc[~tune_mask].assign(**{label: y.loc[~tune_mask].to_numpy()})
    tuning_data = x.loc[tune_mask].assign(**{label: y.loc[tune_mask].to_numpy()})
    predictor = TabularPredictor(
        label=label, problem_type='regression', eval_metric='root_mean_squared_error',
        path=str(path),
    ).fit(
        train_data=train_data,
        tuning_data=tuning_data,
        hyperparameters=HPO_HYPERPARAMETERS,
        hyperparameter_tune_kwargs=hpo_kwargs(trials_per_model),
        presets=['medium_quality', 'ignore_text'],
        time_limit=time_limit,
        verbosity=2,
    )
    predictor.refit_full(model='best')
    return predictor

def chronological_oof_hpo(x, y, periods, label, stage_name):
    x = x.reset_index(drop=True)
    y = pd.Series(y).astype(float).reset_index(drop=True)
    periods = pd.Series(periods).reset_index(drop=True)
    unique_periods = np.sort(periods.unique())
    splitter = TimeSeriesSplit(n_splits=N_SPLITS)
    parts = []
    for fold, (early_period_index, later_period_index) in enumerate(splitter.split(unique_periods), 1):
        early_periods = unique_periods[early_period_index]
        later_periods = unique_periods[later_period_index]
        early_mask = periods.isin(early_periods).to_numpy()
        later_mask = periods.isin(later_periods).to_numpy()
        predictor = fit_hpo_predictor(
            x.loc[early_mask], y.loc[early_mask], periods.loc[early_mask], label,
            MODEL_ROOT / stage_name / f'oof_{fold}',
            OOF_TRIALS_PER_MODEL, OOF_TIME_LIMIT,
        )
        later_index = np.flatnonzero(later_mask)
        prediction = predictor.predict(x.loc[later_mask]).astype(float).to_numpy()
        parts.append(pd.DataFrame({
            'row_index': later_index,
            'period': periods.loc[later_mask].to_numpy(),
            'target': y.loc[later_mask].to_numpy(),
            'prediction': prediction,
            'fold': fold,
        }))
        print(
            f'{stage_name} fold {fold}: fit through {early_periods[-1]}, '
            f'predicted {later_periods[0]} to {later_periods[-1]} ({later_mask.sum():,} rows)'
        )
    return pd.concat(parts, ignore_index=True).sort_values(['period', 'row_index']).reset_index(drop=True)

def calibrated_weight(oof_frame, upper=1.5):
    unique_periods = np.sort(oof_frame['period'].unique())
    calibration_periods = unique_periods[:max(1, len(unique_periods) // 2)]
    calibration = oof_frame.loc[oof_frame['period'].isin(calibration_periods)]
    prediction = calibration['prediction'].to_numpy()
    denominator = float(np.dot(prediction, prediction))
    raw_weight = 0.0 if denominator == 0 else float(
        np.dot(calibration['target'].to_numpy(), prediction) / denominator
    )
    return float(np.clip(raw_weight, 0.0, upper)), raw_weight, calibration_periods

def metric_row(name, actual, prediction):
    return {
        'model': name,
        'RMSE': mean_squared_error(actual, prediction) ** 0.5,
        'MAE': mean_absolute_error(actual, prediction),
        'R2': r2_score(actual, prediction),
    }

## Load data and create the untouched outer holdout

In [5]:
_, datasets = load_datasets(project_root / 'data')
raw = datasets['train'].copy()
raw['period'] = pd.to_datetime(raw['RENT_APPROVAL_DATE'] + '-01').dt.to_period('M')
all_periods = np.sort(raw['period'].unique())
outer_cutoff = all_periods[int(len(all_periods) * 0.80)]
raw_fit = raw.loc[raw['period'] < outer_cutoff].copy()
raw_valid = raw.loc[raw['period'] >= outer_cutoff].copy()
assert raw_fit['period'].max() < raw_valid['period'].min()
print(
    f'Outer cutoff={outer_cutoff}; fit={len(raw_fit):,} rows through {raw_fit.period.max()}; '
    f'validation={len(raw_valid):,} rows from {raw_valid.period.min()} to {raw_valid.period.max()}.'
)
print(f'Active features ({len(BEST_FEATURES)}): {BEST_FEATURES}')

Outer cutoff=2024-05; fit=117,988 rows through 2024-04; validation=32,012 rows from 2024-05 to 2025-03.
Active features (18): ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', 'FLOOR_AREA_SQM', 'approval_date_num', 'approval_month', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', 'town_flat_type_target_mean', 'nearest_mrt_name', 'nearest_tourist_attraction_name', 'nearest_monument_name']

## Layer 1: HPO base ensemble and chronological base OOF predictions

In [6]:
fit_periods = np.sort(raw_fit['period'].unique())
base_parts = []
for fold, (early_period_index, later_period_index) in enumerate(
    TimeSeriesSplit(n_splits=N_SPLITS).split(fit_periods), 1
):
    early_periods = fit_periods[early_period_index]
    later_periods = fit_periods[later_period_index]
    early = raw_fit.loc[raw_fit['period'].isin(early_periods)].copy()
    later = raw_fit.loc[raw_fit['period'].isin(later_periods)].copy()
    early_x, later_x = make_best_features(early, later, datasets)
    predictor = fit_hpo_predictor(
        early_x, early[TARGET], early['period'], TARGET,
        MODEL_ROOT / 'base' / f'oof_{fold}',
        OOF_TRIALS_PER_MODEL, OOF_TIME_LIMIT,
    )
    part = later_x.copy()
    part['period'] = later['period'].to_numpy()
    part['actual'] = later[TARGET].astype(float).to_numpy()
    part['base_prediction'] = predictor.predict(later_x).astype(float).clip(lower=0).to_numpy()
    part['base_fold'] = fold
    base_parts.append(part)
    print(
        f'Base fold {fold}: fit through {early_periods[-1]}, predicted '
        f'{later_periods[0]} to {later_periods[-1]} ({len(later):,} rows)'
    )
base_oof = pd.concat(base_parts, ignore_index=True).sort_values('period').reset_index(drop=True)
base_oof['residual_1_target'] = base_oof['actual'] - base_oof['base_prediction']
print(f'Base OOF rows: {len(base_oof):,}; RMSE={mean_squared_error(base_oof.actual, base_oof.base_prediction) ** 0.5:.3f}')
display(base_oof[['period', 'actual', 'base_prediction', 'residual_1_target']].describe(include='all'))

[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2432 -> 2432 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1086 -> 563 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2432 -> 2432 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1086 -> 563 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2426 -> 2426 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1092 -> 563 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces

Verbosity: 2 (Standard Logging)

[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces

=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.19 GB / 16.00 GB (26.2%)
Disk Space Avail:   172.39 GB / 460.38 GB (37.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/oof_1"
Train Data Rows:    22421
Train Data Columns: 18
Tuning Data Rows:    9144
Tuning Data Columns: 18
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4295.76 MB
	Train Data (Original)  Memory Usage: 18.30 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])          : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('object', [])       : 6 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'nearest_tourist_attraction_name', ...]
		('object', ['text']) : 2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 6 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'nearest_tourist_attraction_name', ...]
		('category', ['text_as_category']) : 2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])                        : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
	0.1s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 2.74 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.94s of the 899.86s of remaining time.
/Users/metul/Desktop/KDDM-project/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████| 12/12 [00:39<00:00,  3.27s/it]
Fitted model: LightGBM/T1 ...
	-318.1318	 = Validation score   (-root_mean_squared_error)
	0.48s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-297.4241	 = Validation score   (-root_mean_squared_error)
	8.63s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-297.5166	 = Validation score   (-root_mean_squared_error)
	1.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-297.1171	 = Validation score   (-root_mean_squared_error)
	3.05s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-297.7853	 = Validation score   (-root_mean_squared_error)
	9.04s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-298.1326	 = Validation score   (-root_mean_squared_error)
	1.39s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-296.4647	 = Validation score   (-root_mean_squared_error)
	2.02s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-297.0358	 = Validation score   (-root_mean_squared_error)
	2.09s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-297.7383	 = Validation score   (-root_mean_squared_error)
	3.44s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-296.6682	 = Validation score   (-root_mean_squared_error)
	2.9s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-297.7908	 = Validation score   (-root_mean_squared_error)
	1.85s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-297.3981	 = Validation score   (-root_mean_squared_error)
	2.35s	 = Training   runtime
	0.01s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.94s of the 860.57s of remaining time.
100%|██████████| 12/12 [00:44<00:00,  3.71s/it]
Fitted model: CatBoost/T1 ...
	-323.6215	 = Validation score   (-root_mean_squared_error)
	0.32s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-294.0902	 = Validation score   (-root_mean_squared_error)
	3.43s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-294.3666	 = Validation score   (-root_mean_squared_error)
	4.1s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-294.9807	 = Validation score   (-root_mean_squared_error)
	3.63s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-293.1693	 = Validation score   (-root_mean_squared_error)
	3.89s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-294.0524	 = Validation score   (-root_mean_squared_error)
	6.78s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-293.762	 = Validation score   (-root_mean_squared_error)
	2.63s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-293.6392	 = Validation score   (-root_mean_squared_error)
	8.96s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-294.4958	 = Validation score   (-root_mean_squared_error)
	2.24s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-295.1105	 = Validation score   (-root_mean_squared_error)
	0.33s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-294.2134	 = Validation score   (-root_mean_squared_error)
	5.3s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-294.4562	 = Validation score   (-root_mean_squared_error)
	2.66s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 815.60s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.0 GB
	Ensemble Weights: {'CatBoost/T5': 0.542, 'CatBoost/T7': 0.167, 'CatBoost/T8': 0.125, 'LightGBM/T7': 0.083, 'LightGBM/T10': 0.083}
	-292.7875	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 84.51s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 99945.6 rows/s (9144 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/oof_1")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T7_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.0 GB
	6.79s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T10_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.1 GB
	10.14s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T5_FULL ...
	Fitting with cpus=10, gpus=0
	3.28s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T7_FULL ...
	Fitting with cpus=10, gpus=0
	2.97s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T8_FULL ...
	Fitting with cpus=10, gpus=0
	7.35s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T5': 0.542, 'CatBoost/T7': 0.167, 'CatBoost/T8': 0.125, 'LightGBM/T7': 0.083, 'LightGBM/T10': 0.083}
	0.0s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 30.74s ... Best model: "WeightedEnsemble_L2_FULL"

Base fold 1: fit through 2021-10, predicted 2021-11 to 2022-08 (28,514 rows)
[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2569 -> 2569 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1117 -> 568 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2569 -> 2569 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1117 -> 568 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 18 -> 18 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2498 -> 2498 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1089 -> 567 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.04 GB / 16.00 GB (25.3%)
Disk Space Avail:   172.27 GB / 460.38 GB (37.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/oof_2"
Train Data Rows:    49389
Train Data Columns: 18
Tuning Data Rows:    10690
Tuning Data Columns: 18
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4175.40 MB
	Train Data (Original)  Memory Usage: 34.85 MB (0.8% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])          : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])                        : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
	0.1s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 5.22 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.15s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.93s of the 899.85s of remaining time.
100%|██████████| 12/12 [01:07<00:00,  5.59s/it]
Fitted model: LightGBM/T1 ...
	-570.0072	 = Validation score   (-root_mean_squared_error)
	0.48s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-510.3634	 = Validation score   (-root_mean_squared_error)
	9.34s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-508.6622	 = Validation score   (-root_mean_squared_error)
	3.0s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-511.7831	 = Validation score   (-root_mean_squared_error)
	5.43s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-511.0954	 = Validation score   (-root_mean_squared_error)
	11.55s	 = Training   runtime
	0.14s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-510.6118	 = Validation score   (-root_mean_squared_error)
	3.19s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-508.4583	 = Validation score   (-root_mean_squared_error)
	4.25s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-509.2713	 = Validation score   (-root_mean_squared_error)
	5.0s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-509.9132	 = Validation score   (-root_mean_squared_error)
	7.74s	 = Training   runtime
	0.15s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-509.1609	 = Validation score   (-root_mean_squared_error)
	9.25s	 = Training   runtime
	0.11s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-508.7649	 = Validation score   (-root_mean_squared_error)
	2.82s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-511.6797	 = Validation score   (-root_mean_squared_error)
	3.98s	 = Training   runtime
	0.02s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.93s of the 832.7s of remaining time.
100%|██████████| 12/12 [01:28<00:00,  7.39s/it]
Fitted model: CatBoost/T1 ...
	-575.4811	 = Validation score   (-root_mean_squared_error)
	0.3s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-511.3159	 = Validation score   (-root_mean_squared_error)
	6.86s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-506.1733	 = Validation score   (-root_mean_squared_error)
	7.51s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-508.2941	 = Validation score   (-root_mean_squared_error)
	7.59s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-510.4837	 = Validation score   (-root_mean_squared_error)
	7.22s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-508.6605	 = Validation score   (-root_mean_squared_error)
	13.95s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-505.3545	 = Validation score   (-root_mean_squared_error)
	5.47s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-507.0963	 = Validation score   (-root_mean_squared_error)
	18.26s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-508.041	 = Validation score   (-root_mean_squared_error)
	4.76s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-508.5702	 = Validation score   (-root_mean_squared_error)
	0.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-509.6594	 = Validation score   (-root_mean_squared_error)
	10.85s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-508.6328	 = Validation score   (-root_mean_squared_error)
	4.91s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 742.86s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.1 GB
	Ensemble Weights: {'CatBoost/T7': 0.647, 'LightGBM/T11': 0.353}
	-503.9033	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 157.16s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 252080.8 rows/s (10690 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/oof_2")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T11_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.1 GB
	10.42s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T7_FULL ...
	Fitting with cpus=10, gpus=0
	6.22s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T7': 0.647, 'LightGBM/T11': 0.353}
	0.01s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 16.76s ... Best model: "WeightedEnsemble_L2_FULL"

Base fold 2: fit through 2022-08, predicted 2022-09 to 2023-06 (27,858 rows)
[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2651 -> 2651 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1130 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2651 -> 2651 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1130 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2558 -> 2558 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1105 -> 570 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.06 GB / 16.00 GB (25.4%)
Disk Space Avail:   172.13 GB / 460.38 GB (37.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/oof_3"
Train Data Rows:    70183
Train Data Columns: 18
Tuning Data Rows:    17754
Tuning Data Columns: 18
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4208.91 MB
	Train Data (Original)  Memory Usage: 51.02 MB (1.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])          : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])                        : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
	0.2s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 7.64 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 0.19s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.91s of the 899.8s of remaining time.
100%|██████████| 12/12 [01:22<00:00,  6.87s/it]
Fitted model: LightGBM/T1 ...
	-758.8452	 = Validation score   (-root_mean_squared_error)
	0.53s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-650.026	 = Validation score   (-root_mean_squared_error)
	9.11s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-655.8053	 = Validation score   (-root_mean_squared_error)
	3.63s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-657.1724	 = Validation score   (-root_mean_squared_error)
	6.58s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-648.3074	 = Validation score   (-root_mean_squared_error)
	12.37s	 = Training   runtime
	0.15s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-650.3495	 = Validation score   (-root_mean_squared_error)
	4.81s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-648.6446	 = Validation score   (-root_mean_squared_error)
	4.25s	 = Training   runtime
	0.1s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-652.7322	 = Validation score   (-root_mean_squared_error)
	6.38s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-645.3384	 = Validation score   (-root_mean_squared_error)
	11.95s	 = Training   runtime
	0.26s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-649.816	 = Validation score   (-root_mean_squared_error)
	12.34s	 = Training   runtime
	0.16s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-649.8067	 = Validation score   (-root_mean_squared_error)
	3.81s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-659.376	 = Validation score   (-root_mean_squared_error)
	5.29s	 = Training   runtime
	0.02s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.91s of the 817.22s of remaining time.
100%|██████████| 12/12 [01:54<00:00,  9.52s/it]
Fitted model: CatBoost/T1 ...
	-823.7857	 = Validation score   (-root_mean_squared_error)
	0.48s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-773.6196	 = Validation score   (-root_mean_squared_error)
	11.16s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-750.7111	 = Validation score   (-root_mean_squared_error)
	4.36s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-718.0772	 = Validation score   (-root_mean_squared_error)
	12.36s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-724.19	 = Validation score   (-root_mean_squared_error)
	6.72s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-740.9174	 = Validation score   (-root_mean_squared_error)
	23.23s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-749.4066	 = Validation score   (-root_mean_squared_error)
	8.5s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-778.4632	 = Validation score   (-root_mean_squared_error)
	14.85s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-728.9342	 = Validation score   (-root_mean_squared_error)
	7.38s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-756.8188	 = Validation score   (-root_mean_squared_error)
	1.01s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-748.5208	 = Validation score   (-root_mean_squared_error)
	16.61s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-748.5	 = Validation score   (-root_mean_squared_error)
	7.16s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 701.38s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.9 GB
	Ensemble Weights: {'LightGBM/T9': 0.696, 'LightGBM/T7': 0.217, 'LightGBM/T5': 0.043, 'LightGBM/T11': 0.043}
	-644.8543	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 198.65s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 31415.9 rows/s (17754 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/oof_3")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T5_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/3.9 GB
	13.83s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T7_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.0 GB
	9.76s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T9_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.0 GB
	15.46s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T11_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/3.9 GB
	12.0s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBM/T9': 0.696, 'LightGBM/T7': 0.217, 'LightGBM/T5': 0.043, 'LightGBM/T11': 0.043}
	0.01s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 51.52s ... Best model: "WeightedEnsemble_L2_FULL"

Base fold 3: fit through 2023-06, predicted 2023-07 to 2024-04 (30,051 rows)
Base OOF rows: 86,423; RMSE=619.071

         period        actual  base_prediction  residual_1_target
count     86423  86423.000000     86423.000000       86423.000000
unique       30           NaN              NaN                NaN
top     2022-01           NaN              NaN                NaN
freq       3278           NaN              NaN                NaN
mean        NaN   2791.240549      2578.917515         212.323034
std         NaN    743.320096       533.399890         581.524935
min         NaN    300.000000      1150.351807       -3936.496582
25%         NaN   2200.000000      2159.628906        -140.819824
50%         NaN   2800.000000      2506.989990         192.915283
75%         NaN   3300.000000      2933.670288         584.072632
max         NaN   7600.000000      5066.439453        3846.137451

## Residual layer 1

The first residual model is tuned on earlier base-model OOF errors. Its shrinkage weight is calibrated using only the earlier half of its own chronological OOF predictions.

In [7]:
residual_1_oof = chronological_oof_hpo(
    base_oof[BEST_FEATURES],
    base_oof['residual_1_target'],
    base_oof['period'],
    'residual_1_target',
    'residual_1',
)
weight_1, raw_weight_1, calibration_periods_1 = calibrated_weight(residual_1_oof)
print(
    f'Residual layer 1 weight={weight_1:.6f} (raw={raw_weight_1:.6f}); '
    f'calibration through {calibration_periods_1[-1]}.'
)
display(residual_1_oof.groupby('fold').agg(
    rows=('target', 'size'),
    target_mean=('target', 'mean'),
    prediction_mean=('prediction', 'mean'),
))

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.02 GB / 16.00 GB (25.1%)
Disk Space Avail:   171.96 GB / 460.38 GB (37.4%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_1/oof_1"
Train Data Rows:    17824
Train Data Columns: 18
Tuning Data Rows:    8274
Tuning Data Columns: 18
Label Column:       residual_1_target
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4143.77 MB
	Train Data (Original)  Memory Usage: 15.16 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 1): ['monthly_target_lag']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 7 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 7 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        : 2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 2.07 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.95s of the 899.88s of remaining time.
100%|██████████| 12/12 [00:38<00:00,  3.18s/it]
Fitted model: LightGBM/T1 ...
	-496.669	 = Validation score   (-root_mean_squared_error)
	0.44s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-495.5924	 = Validation score   (-root_mean_squared_error)
	8.32s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-493.6318	 = Validation score   (-root_mean_squared_error)
	1.5s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-495.3677	 = Validation score   (-root_mean_squared_error)
	3.21s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-496.5714	 = Validation score   (-root_mean_squared_error)
	8.57s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-494.8793	 = Validation score   (-root_mean_squared_error)
	1.37s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-494.3254	 = Validation score   (-root_mean_squared_error)
	2.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-493.7277	 = Validation score   (-root_mean_squared_error)
	2.53s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-494.8021	 = Validation score   (-root_mean_squared_error)
	2.38s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-493.6363	 = Validation score   (-root_mean_squared_error)
	2.68s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-494.364	 = Validation score   (-root_mean_squared_error)
	2.0s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-494.5158	 = Validation score   (-root_mean_squared_error)
	2.59s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.95s of the 861.67s of remaining time.
100%|██████████| 12/12 [01:02<00:00,  5.17s/it]
Fitted model: CatBoost/T1 ...
	-495.7096	 = Validation score   (-root_mean_squared_error)
	0.22s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-485.4392	 = Validation score   (-root_mean_squared_error)
	5.47s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-485.3281	 = Validation score   (-root_mean_squared_error)
	5.71s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-486.8924	 = Validation score   (-root_mean_squared_error)
	5.2s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-484.4652	 = Validation score   (-root_mean_squared_error)
	6.41s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-485.1544	 = Validation score   (-root_mean_squared_error)
	9.89s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-485.8243	 = Validation score   (-root_mean_squared_error)
	3.44s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-484.5272	 = Validation score   (-root_mean_squared_error)
	11.46s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-486.2091	 = Validation score   (-root_mean_squared_error)
	2.88s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-487.1444	 = Validation score   (-root_mean_squared_error)
	0.44s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-485.8146	 = Validation score   (-root_mean_squared_error)
	7.16s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-486.1056	 = Validation score   (-root_mean_squared_error)
	3.44s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 799.14s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.1 GB
	Ensemble Weights: {'CatBoost/T5': 0.538, 'CatBoost/T8': 0.462}
	-484.2917	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 100.88s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 182218.4 rows/s (8274 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_1/oof_1")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T5_FULL ...
	Fitting with cpus=10, gpus=0
	4.92s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T8_FULL ...
	Fitting with cpus=10, gpus=0
	8.89s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T5': 0.538, 'CatBoost/T8': 0.462}
	0.01s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 13.86s ... Best model: "WeightedEnsemble_L2_FULL"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.00 GB / 16.00 GB (25.0%)
Disk Space Avail:   171.87 GB / 460.38 GB (37.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_1/oof_2"
Train Data Rows:    35929
Train Data Columns: 18
Tuning Data Rows:    8255
Tuning Data Columns: 18
Label Column:       residual_1_target
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4126.95 MB
	Train Data (Original)  Memory Usage: 25.66 MB (0.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...

residual_1 fold 1: fit through 2022-07, predicted 2022-08 to 2023-02 (18,086 rows)

	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        : 2 | ['approval_date_num', 'approval_month']
	0.2s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 3.84 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.17s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.92s of the 899.83s of remaining time.
100%|██████████| 12/12 [00:38<00:00,  3.18s/it]
Fitted model: LightGBM/T1 ...
	-681.3542	 = Validation score   (-root_mean_squared_error)
	0.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-680.8701	 = Validation score   (-root_mean_squared_error)
	6.08s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-676.0449	 = Validation score   (-root_mean_squared_error)
	2.06s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-680.4072	 = Validation score   (-root_mean_squared_error)
	3.57s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-686.102	 = Validation score   (-root_mean_squared_error)
	3.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-681.6323	 = Validation score   (-root_mean_squared_error)
	2.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-674.6468	 = Validation score   (-root_mean_squared_error)
	2.16s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-674.069	 = Validation score   (-root_mean_squared_error)
	3.22s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-676.2363	 = Validation score   (-root_mean_squared_error)
	4.9s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-675.1868	 = Validation score   (-root_mean_squared_error)
	3.69s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-676.381	 = Validation score   (-root_mean_squared_error)
	2.3s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-679.5237	 = Validation score   (-root_mean_squared_error)
	2.97s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.92s of the 861.57s of remaining time.
100%|██████████| 12/12 [01:29<00:00,  7.48s/it]
Fitted model: CatBoost/T1 ...
	-671.3947	 = Validation score   (-root_mean_squared_error)
	0.31s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-656.6422	 = Validation score   (-root_mean_squared_error)
	8.07s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-656.5636	 = Validation score   (-root_mean_squared_error)
	7.28s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-654.1865	 = Validation score   (-root_mean_squared_error)
	7.59s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-647.6795	 = Validation score   (-root_mean_squared_error)
	7.24s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-661.0602	 = Validation score   (-root_mean_squared_error)
	13.8s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-647.8291	 = Validation score   (-root_mean_squared_error)
	5.46s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-650.3982	 = Validation score   (-root_mean_squared_error)
	19.27s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-660.1752	 = Validation score   (-root_mean_squared_error)
	4.34s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-653.9956	 = Validation score   (-root_mean_squared_error)
	0.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-661.0959	 = Validation score   (-root_mean_squared_error)
	10.71s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-658.3995	 = Validation score   (-root_mean_squared_error)
	4.65s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 771.32s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.1 GB
	Ensemble Weights: {'CatBoost/T5': 0.565, 'CatBoost/T7': 0.435}
	-647.4599	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 128.7s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 215186.8 rows/s (8255 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_1/oof_2")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T5_FULL ...
	Fitting with cpus=10, gpus=0
	5.41s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T7_FULL ...
	Fitting with cpus=10, gpus=0
	5.95s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T5': 0.565, 'CatBoost/T7': 0.435}
	0.01s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 11.4s ... Best model: "WeightedEnsemble_L2_FULL"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.01 GB / 16.00 GB (25.1%)
Disk Space Avail:   171.77 GB / 460.38 GB (37.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_1/oof_3"
Train Data Rows:    53337
Train Data Columns: 18
Tuning Data Rows:    11963
Tuning Data Columns: 18
Label Column:       residual_1_target
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4148.96 MB
	Train Data (Original)  Memory Usage: 37.90 MB (0.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.

residual_1 fold 2: fit through 2023-02, predicted 2023-03 to 2023-09 (21,116 rows)

	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        : 2 | ['approval_date_num', 'approval_month']
	0.2s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 5.67 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.23s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.9s of the 899.77s of remaining time.
100%|██████████| 12/12 [00:22<00:00,  1.86s/it]
Fitted model: LightGBM/T1 ...
	-674.9934	 = Validation score   (-root_mean_squared_error)
	0.34s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-676.1547	 = Validation score   (-root_mean_squared_error)
	2.96s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-679.0791	 = Validation score   (-root_mean_squared_error)
	1.5s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-679.2333	 = Validation score   (-root_mean_squared_error)
	3.5s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-675.2197	 = Validation score   (-root_mean_squared_error)
	2.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-678.4817	 = Validation score   (-root_mean_squared_error)
	1.77s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-675.9146	 = Validation score   (-root_mean_squared_error)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-677.7009	 = Validation score   (-root_mean_squared_error)
	2.07s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-675.1451	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-675.6621	 = Validation score   (-root_mean_squared_error)
	1.61s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-678.5817	 = Validation score   (-root_mean_squared_error)
	1.23s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-682.0718	 = Validation score   (-root_mean_squared_error)
	2.91s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.9s of the 877.47s of remaining time.
100%|██████████| 12/12 [00:12<00:00,  1.06s/it]
Fitted model: CatBoost/T1 ...
	-674.7152	 = Validation score   (-root_mean_squared_error)
	0.25s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-673.4154	 = Validation score   (-root_mean_squared_error)
	1.82s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-677.9305	 = Validation score   (-root_mean_squared_error)
	1.39s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-674.7574	 = Validation score   (-root_mean_squared_error)
	0.64s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-678.2873	 = Validation score   (-root_mean_squared_error)
	0.98s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-674.1442	 = Validation score   (-root_mean_squared_error)
	1.23s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-675.2297	 = Validation score   (-root_mean_squared_error)
	0.65s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-675.0272	 = Validation score   (-root_mean_squared_error)
	1.51s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-673.7712	 = Validation score   (-root_mean_squared_error)
	0.89s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-675.8048	 = Validation score   (-root_mean_squared_error)
	0.36s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-674.2018	 = Validation score   (-root_mean_squared_error)
	1.19s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-673.431	 = Validation score   (-root_mean_squared_error)
	1.52s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 864.53s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.1 GB
	Ensemble Weights: {'CatBoost/T2': 1.0}
	-673.4154	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 35.49s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 627943.6 rows/s (11963 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_1/oof_3")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T2_FULL ...
	Fitting with cpus=10, gpus=0
	0.05s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T2': 1.0}
	0.01s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 0.06s ... Best model: "WeightedEnsemble_L2_FULL"

residual_1 fold 3: fit through 2023-09, predicted 2023-10 to 2024-04 (21,123 rows)
Residual layer 1 weight=0.956195 (raw=0.956195); calibration through 2023-05.

       rows  target_mean  prediction_mean
fold
1     18086   321.528904       391.683266
2     21116   321.851981       433.685471
3     21123    30.157078       273.096356

## Residual layer 2

Layer 2 predicts what remains after the OOF base prediction and the shrunken Layer-1 residual correction. Only rows with a genuine Layer-1 OOF prediction are eligible.

In [12]:
residual_2_rows = base_oof.iloc[residual_1_oof['row_index'].to_numpy()].reset_index(drop=True)
residual_2_rows['residual_1_oof_prediction'] = residual_1_oof['prediction'].to_numpy()
residual_2_rows['residual_2_target'] = (
    residual_1_oof['target'].to_numpy()
    - weight_1 * residual_1_oof['prediction'].to_numpy()
)
residual_2_oof = chronological_oof_hpo(
    residual_2_rows[BEST_FEATURES],
    residual_2_rows['residual_2_target'],
    residual_2_rows['period'],
    'residual_2_target',
    'residual_2',
)
weight_2, raw_weight_2, calibration_periods_2 = calibrated_weight(residual_2_oof)
print(
    f'Residual layer 2 weight={weight_2:.6f} (raw={raw_weight_2:.6f}); '
    f'calibration through {calibration_periods_2[-1]}.'
)
display(residual_2_oof.groupby('fold').agg(
    rows=('target', 'size'),
    target_mean=('target', 'mean'),
    prediction_mean=('prediction', 'mean'),
))

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.98 GB / 16.00 GB (24.9%)
Disk Space Avail:   171.76 GB / 460.38 GB (37.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_2/oof_1"
Train Data Rows:    12520
Train Data Columns: 18
Tuning Data Rows:    2622
Tuning Data Columns: 18
Label Column:       residual_2_target
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4104.22 MB
	Train Data (Original)  Memory Usage: 8.78 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        : 2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 1.32 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.07s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.97s of the 899.93s of remaining time.
100%|██████████| 12/12 [00:30<00:00,  2.52s/it]
Fitted model: LightGBM/T1 ...
	-669.5433	 = Validation score   (-root_mean_squared_error)
	0.39s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-672.6752	 = Validation score   (-root_mean_squared_error)
	7.18s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-662.1674	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-660.4246	 = Validation score   (-root_mean_squared_error)
	2.86s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-675.242	 = Validation score   (-root_mean_squared_error)
	6.33s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-672.5047	 = Validation score   (-root_mean_squared_error)
	0.83s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-666.9953	 = Validation score   (-root_mean_squared_error)
	1.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-672.0101	 = Validation score   (-root_mean_squared_error)
	1.8s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-680.1981	 = Validation score   (-root_mean_squared_error)
	1.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-668.0704	 = Validation score   (-root_mean_squared_error)
	2.43s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-667.5989	 = Validation score   (-root_mean_squared_error)
	1.38s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-659.7478	 = Validation score   (-root_mean_squared_error)
	2.15s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.97s of the 869.66s of remaining time.
100%|██████████| 12/12 [00:36<00:00,  3.06s/it]
Fitted model: CatBoost/T1 ...
	-687.3771	 = Validation score   (-root_mean_squared_error)
	0.16s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-673.8498	 = Validation score   (-root_mean_squared_error)
	2.71s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-679.514	 = Validation score   (-root_mean_squared_error)
	4.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-678.1679	 = Validation score   (-root_mean_squared_error)
	2.61s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-652.1653	 = Validation score   (-root_mean_squared_error)
	3.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-675.203	 = Validation score   (-root_mean_squared_error)
	5.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-673.0314	 = Validation score   (-root_mean_squared_error)
	1.81s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-670.4977	 = Validation score   (-root_mean_squared_error)
	8.09s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-684.3248	 = Validation score   (-root_mean_squared_error)
	1.51s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-682.035	 = Validation score   (-root_mean_squared_error)
	0.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-670.2333	 = Validation score   (-root_mean_squared_error)
	4.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-685.114	 = Validation score   (-root_mean_squared_error)
	2.06s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 832.71s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.9 GB
	Ensemble Weights: {'CatBoost/T5': 0.826, 'LightGBM/T4': 0.174}
	-651.7872	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 67.3s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 235602.7 rows/s (2622 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_2/oof_1")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T4_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/3.9 GB
	6.33s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T5_FULL ...
	Fitting with cpus=10, gpus=0
	2.19s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T5': 0.826, 'LightGBM/T4': 0.174}
	0.0s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 8.6s ... Best model: "WeightedEnsemble_L2_FULL"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.95 GB / 16.00 GB (24.7%)
Disk Space Avail:   171.68 GB / 460.38 GB (37.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_2/oof_2"
Train Data Rows:    24261
Train Data Columns: 18
Tuning Data Rows:    6013
Tuning Data Columns: 18
Label Column:       residual_2_target
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4055.49 MB
	Train Data (Original)  Memory Usage: 17.55 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        : 2 | ['approval_date_num', 'approval_month']
	0.1s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 2.63 MB (0.1% of available memory)

residual_2 fold 1: fit through 2023-01, predicted 2023-02 to 2023-06 (15,132 rows)

Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.94s of the 899.87s of remaining time.
100%|██████████| 12/12 [00:30<00:00,  2.51s/it]
Fitted model: LightGBM/T1 ...
	-622.1519	 = Validation score   (-root_mean_squared_error)
	0.46s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-623.7495	 = Validation score   (-root_mean_squared_error)
	6.35s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-622.0849	 = Validation score   (-root_mean_squared_error)
	1.39s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-624.0563	 = Validation score   (-root_mean_squared_error)
	3.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-624.5789	 = Validation score   (-root_mean_squared_error)
	5.3s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-624.0165	 = Validation score   (-root_mean_squared_error)
	1.6s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-622.1214	 = Validation score   (-root_mean_squared_error)
	1.58s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-622.5055	 = Validation score   (-root_mean_squared_error)
	2.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-622.7549	 = Validation score   (-root_mean_squared_error)
	2.01s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-621.931	 = Validation score   (-root_mean_squared_error)
	1.98s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-622.8563	 = Validation score   (-root_mean_squared_error)
	1.65s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-623.6527	 = Validation score   (-root_mean_squared_error)
	2.47s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.94s of the 869.7s of remaining time.
100%|██████████| 12/12 [00:27<00:00,  2.29s/it]
Fitted model: CatBoost/T1 ...
	-621.2697	 = Validation score   (-root_mean_squared_error)
	0.2s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-617.7093	 = Validation score   (-root_mean_squared_error)
	3.29s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-618.1836	 = Validation score   (-root_mean_squared_error)
	1.95s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-618.0814	 = Validation score   (-root_mean_squared_error)
	1.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-618.9262	 = Validation score   (-root_mean_squared_error)
	2.18s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-618.0034	 = Validation score   (-root_mean_squared_error)
	3.82s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-618.3697	 = Validation score   (-root_mean_squared_error)
	1.35s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-618.0759	 = Validation score   (-root_mean_squared_error)
	3.37s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-618.0438	 = Validation score   (-root_mean_squared_error)
	1.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-618.0903	 = Validation score   (-root_mean_squared_error)
	0.42s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-618.0861	 = Validation score   (-root_mean_squared_error)
	4.6s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-618.3736	 = Validation score   (-root_mean_squared_error)
	2.64s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 841.99s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.1 GB
	Ensemble Weights: {'CatBoost/T2': 0.857, 'CatBoost/T9': 0.095, 'LightGBM/T7': 0.048}
	-617.6934	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 58.02s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 223820.8 rows/s (6013 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_2/oof_2")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T7_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.1 GB
	7.02s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T2_FULL ...
	Fitting with cpus=10, gpus=0
	0.58s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T9_FULL ...
	Fitting with cpus=10, gpus=0
	0.43s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T2': 0.857, 'CatBoost/T9': 0.095, 'LightGBM/T7': 0.048}
	0.0s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 8.11s ... Best model: "WeightedEnsemble_L2_FULL"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.10 GB / 16.00 GB (25.6%)
Disk Space Avail:   171.63 GB / 460.38 GB (37.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 900s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_2/oof_3"
Train Data Rows:    36455
Train Data Columns: 18
Tuning Data Rows:    8711
Tuning Data Columns: 18
Label Column:       residual_2_target
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4232.74 MB
	Train Data (Original)  Memory Usage: 26.21 MB (0.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...

residual_2 fold 2: fit through 2023-06, predicted 2023-07 to 2023-11 (14,892 rows)

			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        : 2 | ['approval_date_num', 'approval_month']
	0.2s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 3.92 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.17s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 404.92s of the 899.83s of remaining time.
100%|██████████| 12/12 [00:25<00:00,  2.11s/it]
Fitted model: LightGBM/T1 ...
	-603.7608	 = Validation score   (-root_mean_squared_error)
	0.51s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-618.0874	 = Validation score   (-root_mean_squared_error)
	4.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-601.3015	 = Validation score   (-root_mean_squared_error)
	1.61s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-601.1449	 = Validation score   (-root_mean_squared_error)
	3.39s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-621.4536	 = Validation score   (-root_mean_squared_error)
	2.74s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-616.2809	 = Validation score   (-root_mean_squared_error)
	1.76s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-605.6777	 = Validation score   (-root_mean_squared_error)
	1.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-615.0298	 = Validation score   (-root_mean_squared_error)
	2.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-621.388	 = Validation score   (-root_mean_squared_error)
	1.2s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-606.6272	 = Validation score   (-root_mean_squared_error)
	2.17s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-602.6129	 = Validation score   (-root_mean_squared_error)
	1.65s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-600.2575	 = Validation score   (-root_mean_squared_error)
	2.75s	 = Training   runtime
	0.0s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 404.92s of the 874.48s of remaining time.
100%|██████████| 12/12 [00:12<00:00,  1.03s/it]
Fitted model: CatBoost/T1 ...
	-621.4265	 = Validation score   (-root_mean_squared_error)
	0.25s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-622.0409	 = Validation score   (-root_mean_squared_error)
	1.86s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-623.7405	 = Validation score   (-root_mean_squared_error)
	1.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-621.4733	 = Validation score   (-root_mean_squared_error)
	0.55s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-596.4718	 = Validation score   (-root_mean_squared_error)
	1.26s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-621.3247	 = Validation score   (-root_mean_squared_error)
	1.07s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-622.049	 = Validation score   (-root_mean_squared_error)
	0.58s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-621.7457	 = Validation score   (-root_mean_squared_error)
	1.47s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-621.6703	 = Validation score   (-root_mean_squared_error)
	0.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-622.6764	 = Validation score   (-root_mean_squared_error)
	0.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-621.0699	 = Validation score   (-root_mean_squared_error)
	1.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-622.1139	 = Validation score   (-root_mean_squared_error)
	1.55s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 861.85s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.2 GB
	Ensemble Weights: {'CatBoost/T5': 0.76, 'CatBoost/T6': 0.12, 'LightGBM/T12': 0.08, 'LightGBM/T4': 0.04}
	-595.4126	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 38.17s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 286285.2 rows/s (8711 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_2/oof_3")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T4_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.1 GB
	24.09s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T12_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/4.1 GB
	24.2s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T5_FULL ...
	Fitting with cpus=10, gpus=0
	0.14s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T6_FULL ...
	Fitting with cpus=10, gpus=0
	0.04s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T5': 0.76, 'CatBoost/T6': 0.12, 'LightGBM/T12': 0.08, 'LightGBM/T4': 0.04}
	0.01s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 48.84s ... Best model: "WeightedEnsemble_L2_FULL"

residual_2 fold 3: fit through 2023-11, predicted 2023-12 to 2024-04 (15,159 rows)
Residual layer 2 weight=0.000000 (raw=-0.440466); calibration through 2023-08.

       rows  target_mean  prediction_mean
fold
1     15132   121.728153        54.372135
2     14892  -317.904617        30.863673
3     15159  -227.859564      -166.590805

## Final HPO fits and untouched validation comparison

The three final predictors are independently tuned and refitted. Residual models learn only from OOF errors; the untouched validation labels are used once, below, for reporting.

In [13]:
fit_x, valid_x = make_best_features(raw_fit, raw_valid, datasets)
base_model = fit_hpo_predictor(
    fit_x, raw_fit[TARGET], raw_fit['period'], TARGET,
    MODEL_ROOT / 'base' / 'final',
    FINAL_TRIALS_PER_MODEL, FINAL_TIME_LIMIT,
)
residual_1_model = fit_hpo_predictor(
    base_oof[BEST_FEATURES], base_oof['residual_1_target'], base_oof['period'],
    'residual_1_target', MODEL_ROOT / 'residual_1' / 'final',
    FINAL_TRIALS_PER_MODEL, FINAL_TIME_LIMIT,
)
residual_2_model = fit_hpo_predictor(
    residual_2_rows[BEST_FEATURES], residual_2_rows['residual_2_target'],
    residual_2_rows['period'], 'residual_2_target',
    MODEL_ROOT / 'residual_2' / 'final',
    FINAL_TRIALS_PER_MODEL, FINAL_TIME_LIMIT,
)

actual = raw_valid[TARGET].astype(float).to_numpy()
base_prediction = base_model.predict(valid_x).astype(float).clip(lower=0).to_numpy()
residual_1_prediction = residual_1_model.predict(valid_x).astype(float).to_numpy()
residual_2_prediction = residual_2_model.predict(valid_x).astype(float).to_numpy()
stage_1_prediction = np.clip(base_prediction + weight_1 * residual_1_prediction, 0, None)
stage_2_prediction = np.clip(
    base_prediction
    + weight_1 * residual_1_prediction
    + weight_2 * residual_2_prediction,
    0, None,
)
comparison = pd.DataFrame([
    metric_row('HPO base AutoGluon', actual, base_prediction),
    metric_row(f'+ residual 1 (weight={weight_1:.3f})', actual, stage_1_prediction),
    metric_row(f'+ residual 2 (weight={weight_2:.3f})', actual, stage_2_prediction),
]).sort_values('RMSE').reset_index(drop=True)
display(comparison)
print(f'Best validation stage: {comparison.iloc[0].model}; RMSE={comparison.iloc[0].RMSE:.6f}')

[categorical_clean] HDB lookup | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | BLOCK: 2735 -> 2735 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | STREET: 576 -> 576 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | POSTAL_CODE: 9180 -> 9180 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | SUBZONE: 156 -> 156 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | PLANNING_AREA: 31 -> 31 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] HDB lookup | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2699 -> 2699 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1138 -> 574 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 11 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 19 -> 19 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | TOWN: 26 -> 26 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | BLOCK: 2585 -> 2585 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | STREET: 1109 -> 573 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_TYPE: 6 -> 6 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FLAT_MODEL: 20 -> 20 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] rental input | FURNISHED: 1 -> 1 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces
[categorical_clean] derived HDB feature | REGION: 5 -> 5 unique values | lowercase, trim, collapse whitespace, and replace hyphen/underscore/slash separators with spaces

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.13 GB / 16.00 GB (25.8%)
Disk Space Avail:   171.60 GB / 460.38 GB (37.3%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/final"
Train Data Rows:    94118
Train Data Columns: 18
Tuning Data Rows:    23870
Tuning Data Columns: 18
Label Column:       MONTHLY_RENT
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4297.86 MB
	Train Data (Original)  Memory Usage: 68.45 MB (1.6% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])          : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
		('object', [])       : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('object', ['text']) : 1 | ['nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 7 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('category', ['text_as_category']) : 1 | ['nearest_mrt_name']
		('float', [])                      : 6 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', 'monthly_target_lag', ...]
		('int', [])                        : 4 | ['approval_date_num', 'approval_month', 'YEAR_COMPLETED', 'MAX_FLOOR']
	0.2s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 10.24 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 0.24s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=24, upper=500, 'num_iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'min_data_in_leaf': Int: lower=20, upper=250, 'feature_fraction': Real: lower=0.7, upper=1.0, 'bagging_fraction': Real: lower=0.7, upper=1.0, 'bagging_freq': 1, 'lambda_l1': Real: lower=0.0001, upper=20.0, 'lambda_l2': Real: lower=0.0001, upper=20.0}],
	'CAT': [{'depth': Int: lower=5, upper=10, 'iterations': Int: lower=100, upper=1000, 'learning_rate': Real: lower=0.01, upper=0.12, 'l2_leaf_reg': Real: lower=1.0, upper=30.0, 'random_strength': Real: lower=0.001, upper=10.0, 'bagging_temperature': Real: lower=0.0, upper=1.5}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 809.89s of the 1799.76s of remaining time.
100%|██████████| 30/30 [02:05<00:00,  4.17s/it]
Fitted model: LightGBM/T1 ...
	-620.1437	 = Validation score   (-root_mean_squared_error)
	0.55s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-559.6792	 = Validation score   (-root_mean_squared_error)
	6.7s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-560.0018	 = Validation score   (-root_mean_squared_error)
	2.85s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-560.2012	 = Validation score   (-root_mean_squared_error)
	4.82s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-562.1119	 = Validation score   (-root_mean_squared_error)
	8.59s	 = Training   runtime
	0.13s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-562.7131	 = Validation score   (-root_mean_squared_error)
	3.07s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-558.5643	 = Validation score   (-root_mean_squared_error)
	2.12s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-560.7935	 = Validation score   (-root_mean_squared_error)
	4.38s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-561.3384	 = Validation score   (-root_mean_squared_error)
	11.27s	 = Training   runtime
	0.19s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-557.9505	 = Validation score   (-root_mean_squared_error)
	8.07s	 = Training   runtime
	0.12s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-560.4252	 = Validation score   (-root_mean_squared_error)
	1.53s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-560.9329	 = Validation score   (-root_mean_squared_error)
	3.92s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T13 ...
	-562.8375	 = Validation score   (-root_mean_squared_error)
	1.83s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T14 ...
	-560.8519	 = Validation score   (-root_mean_squared_error)
	2.38s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T15 ...
	-562.2561	 = Validation score   (-root_mean_squared_error)
	4.92s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: LightGBM/T16 ...
	-561.3395	 = Validation score   (-root_mean_squared_error)
	1.72s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T17 ...
	-562.729	 = Validation score   (-root_mean_squared_error)
	1.11s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T18 ...
	-562.977	 = Validation score   (-root_mean_squared_error)
	4.5s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T19 ...
	-562.0251	 = Validation score   (-root_mean_squared_error)
	1.47s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T20 ...
	-564.197	 = Validation score   (-root_mean_squared_error)
	3.47s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T21 ...
	-558.7295	 = Validation score   (-root_mean_squared_error)
	6.14s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T22 ...
	-557.026	 = Validation score   (-root_mean_squared_error)
	4.85s	 = Training   runtime
	0.29s	 = Validation runtime
Fitted model: LightGBM/T23 ...
	-563.6548	 = Validation score   (-root_mean_squared_error)
	2.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T24 ...
	-561.63	 = Validation score   (-root_mean_squared_error)
	3.16s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T25 ...
	-558.417	 = Validation score   (-root_mean_squared_error)
	7.73s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: LightGBM/T26 ...
	-562.2942	 = Validation score   (-root_mean_squared_error)
	3.95s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T27 ...
	-560.5112	 = Validation score   (-root_mean_squared_error)
	3.84s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: LightGBM/T28 ...
	-556.4455	 = Validation score   (-root_mean_squared_error)
	6.21s	 = Training   runtime
	0.11s	 = Validation runtime
Fitted model: LightGBM/T29 ...
	-563.9183	 = Validation score   (-root_mean_squared_error)
	3.6s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T30 ...
	-559.0664	 = Validation score   (-root_mean_squared_error)
	2.11s	 = Training   runtime
	0.08s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 809.89s of the 1674.45s of remaining time.
100%|██████████| 30/30 [08:10<00:00, 16.36s/it]
Fitted model: CatBoost/T1 ...
	-623.1076	 = Validation score   (-root_mean_squared_error)
	0.68s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-548.8315	 = Validation score   (-root_mean_squared_error)
	15.52s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-548.0342	 = Validation score   (-root_mean_squared_error)
	17.57s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-555.2431	 = Validation score   (-root_mean_squared_error)
	16.23s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-555.9474	 = Validation score   (-root_mean_squared_error)
	25.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-549.2201	 = Validation score   (-root_mean_squared_error)
	23.82s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-549.8819	 = Validation score   (-root_mean_squared_error)
	12.05s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-546.8303	 = Validation score   (-root_mean_squared_error)
	37.25s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-552.5285	 = Validation score   (-root_mean_squared_error)
	8.21s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-555.9729	 = Validation score   (-root_mean_squared_error)
	1.4s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-549.2742	 = Validation score   (-root_mean_squared_error)
	22.99s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-549.3053	 = Validation score   (-root_mean_squared_error)
	8.17s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T13 ...
	-547.2364	 = Validation score   (-root_mean_squared_error)
	22.36s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T14 ...
	-551.2849	 = Validation score   (-root_mean_squared_error)
	18.74s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T15 ...
	-551.1679	 = Validation score   (-root_mean_squared_error)
	18.07s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T16 ...
	-554.4257	 = Validation score   (-root_mean_squared_error)
	9.61s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T17 ...
	-546.9538	 = Validation score   (-root_mean_squared_error)
	16.59s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T18 ...
	-553.5015	 = Validation score   (-root_mean_squared_error)
	31.53s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: CatBoost/T19 ...
	-547.0477	 = Validation score   (-root_mean_squared_error)
	18.02s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T20 ...
	-547.7555	 = Validation score   (-root_mean_squared_error)
	13.85s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T21 ...
	-552.0849	 = Validation score   (-root_mean_squared_error)
	2.47s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T22 ...
	-559.8919	 = Validation score   (-root_mean_squared_error)
	9.81s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T23 ...
	-548.9763	 = Validation score   (-root_mean_squared_error)
	18.55s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T24 ...
	-549.643	 = Validation score   (-root_mean_squared_error)
	5.19s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T25 ...
	-547.0011	 = Validation score   (-root_mean_squared_error)
	30.76s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T26 ...
	-549.8902	 = Validation score   (-root_mean_squared_error)
	17.71s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T27 ...
	-549.2276	 = Validation score   (-root_mean_squared_error)
	8.89s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T28 ...
	-553.0482	 = Validation score   (-root_mean_squared_error)
	2.24s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T29 ...
	-554.3375	 = Validation score   (-root_mean_squared_error)
	41.57s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: CatBoost/T30 ...
	-546.9226	 = Validation score   (-root_mean_squared_error)
	13.99s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 1180.00s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/3.5 GB
	Ensemble Weights: {'CatBoost/T30': 0.273, 'CatBoost/T25': 0.227, 'CatBoost/T17': 0.136, 'CatBoost/T19': 0.136, 'LightGBM/T22': 0.091, 'CatBoost/T13': 0.091, 'CatBoost/T8': 0.045}
	-545.6946	 = Validation score   (-root_mean_squared_error)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 620.04s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 47229.8 rows/s (23870 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/base/final")
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM/T22_FULL ...
	Fitting with cpus=10, gpus=0, mem=0.1/3.5 GB
	6.46s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T8_FULL ...
	Fitting with cpus=10, gpus=0
	37.03s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T13_FULL ...
	Fitting with cpus=10, gpus=0
	17.64s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T17_FULL ...
	Fitting with cpus=10, gpus=0
	12.44s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T19_FULL ...
	Fitting with cpus=10, gpus=0
	13.14s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T25_FULL ...
	Fitting with cpus=10, gpus=0
	31.52s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost/T30_FULL ...
	Fitting with cpus=10, gpus=0
	10.82s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'CatBoost/T30': 0.273, 'CatBoost/T25': 0.227, 'CatBoost/T17': 0.136, 'CatBoost/T19': 0.136, 'LightGBM/T22': 0.091, 'CatBoost/T13': 0.091, 'CatBoost/T8': 0.045}
	0.02s	 = Training   runtime
Updated best model to "WeightedEnsemble_L2_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "WeightedEnsemble_L2_FULL" for predict() and predict_proba().
Refit complete, total runtime = 129.29s ... Best model: "WeightedEnsemble_L2_FULL"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       3.86 GB / 16.00 GB (24.1%)
Disk Space Avail:   171.18 GB / 460.38 GB (37.2%)
===================================================
Presets specified: ['medium_quality', 'ignore_text']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 1800s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp_17_two_residual_hpt/20261020_123932/residual_1/final"
Train Data Rows:    68339
Train Data Columns: 18
Tuning Data Rows:    18084
Tuning Data Columns: 18
Label Column:       residual_1_target
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    3998.89 MB
	Train Data (Original)  Memory Usage: 50.17 MB (1.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])        : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])          : 2 | ['approval_date_num', 'approval_month']
		('object', [])       : 6 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'nearest_tourist_attraction_name', ...]
		('object', ['text']) : 2 | ['STREET', 'nearest_mrt_name']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])                   : 6 | ['TOWN', 'BLOCK', 'FLAT_TYPE', 'FLAT_MODEL', 'nearest_tourist_attraction_name', ...]
		('category', ['text_as_category']) : 2 | ['STREET', 'nearest_mrt_name']
		('float', [])                      : 8 | ['FLOOR_AREA_SQM', 'coe_quota_premium_mean', 'YEAR_COMPLETED', 'MAX_FLOOR', 'mrt_dist_nearest_km', ...]
		('int', [])                        : 2 | ['approval_date_num', 'approval_month']
	0.3s = Fit runtime
	18 features in original data used to generate 18 features in processed data.
	Train Data (Processed) Memory Usage: 7.50 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 0.29s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{

                         model        RMSE         MAE        R2
0           HPO base AutoGluon  470.231716  343.270955  0.487725
1  + residual 1 (weight=0.956)  474.426051  341.801835  0.478545
2  + residual 2 (weight=0.000)  474.426051  341.801835  0.478545

Best validation stage: HPO base AutoGluon; RMSE=470.231716

## Diagnostics and saved validation artifacts

The leaderboard for each final layer shows which HPO trials and ensemble won. Validation predictions and metrics are saved so that the exact Exp. 17 result remains available for the report.

In [14]:
for name, predictor in {
    'base': base_model,
    'residual_1': residual_1_model,
    'residual_2': residual_2_model,
}.items():
    print(f'\n{name} leaderboard')
    display(predictor.leaderboard(silent=True).head(15))

validation_predictions = pd.DataFrame({
    'row_index': raw_valid.index,
    'period': raw_valid['period'].astype(str).to_numpy(),
    'actual': actual,
    'base_prediction': base_prediction,
    'residual_1_prediction': residual_1_prediction,
    'residual_1_weight': weight_1,
    'residual_2_prediction': residual_2_prediction,
    'residual_2_weight': weight_2,
    'final_prediction': stage_2_prediction,
})
prediction_path = experiment_dir / 'exp_17_two_residual_hpt_validation_predictions.csv'
metrics_path = experiment_dir / 'exp_17_two_residual_hpt_metrics.csv'
validation_predictions.to_csv(prediction_path, index=False)
comparison.to_csv(metrics_path, index=False)
print(f'Saved validation predictions to {prediction_path}')
print(f'Saved metrics to {metrics_path}')

base leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-545.694574,root_mean_squared_error,0.505401,143.838038,0.000323,0.019623,2,True,61
1,CatBoost/T8,-546.830310,root_mean_squared_error,0.038583,37.252125,0.038583,37.252125,1,True,38
2,CatBoost/T30,-546.922640,root_mean_squared_error,0.031512,13.993539,0.031512,13.993539,1,True,60
3,CatBoost/T17,-546.953843,root_mean_squared_error,0.032575,16.590916,0.032575,16.590916,1,True,47
4,CatBoost/T25,-547.001147,root_mean_squared_error,0.044638,30.755488,0.044638,30.755488,1,True,55
5,CatBoost/T19,-547.047734,root_mean_squared_error,0.031056,18.016730,0.031056,18.016730,1,True,49
6,CatBoost/T13,-547.236356,root_mean_squared_error,0.034004,22.362415,0.034004,22.362415,1,True,43
7,CatBoost/T20,-547.755500,root_mean_squared_error,0.033873,13.852401,0.033873,13.852401,1,True,50
8,CatBoost/T3,-548.034237,root_mean_squared_error,0.031175,17.567194,0.031175,17.567194,1,True,33
9,CatBoost/T2,-548.831542,root_mean_squared_error,0.028713,15.516624,0.028713,15.516624,1,True,32
10,CatBoost/T23,-548.976275,root_mean_squared_error,0.033266,18.548461,0.033266,18.548461,1,True,53
11,CatBoost/T6,-549.220107,root_mean_squared_error,0.033318,23.821438,0.033318,23.821438,1,True,36
12,CatBoost/T27,-549.227634,root_mean_squared_error,0.029030,8.887463,0.029030,8.887463,1,True,57
13,CatBoost/T11,-549.274238,root_mean_squared_error,0.031809,22.992459,0.031809,22.992459,1,True,41
14,CatBoost/T12,-549.305255,root_mean_squared_error,0.023801,8.165056,0.023801,8.165056,1,True,42

residual_1 leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-547.190075,root_mean_squared_error,0.114931,17.110331,0.000225,0.012334,2,True,61
1,CatBoost/T10,-549.756057,root_mean_squared_error,0.014700,1.026058,0.014700,1.026058,1,True,40
2,CatBoost/T7,-550.890887,root_mean_squared_error,0.023934,8.503511,0.023934,8.503511,1,True,37
3,CatBoost/T15,-551.183891,root_mean_squared_error,0.021806,11.718625,0.021806,11.718625,1,True,45
4,CatBoost/T13,-551.378988,root_mean_squared_error,0.027143,12.311048,0.027143,12.311048,1,True,43
5,CatBoost/T9,-551.697455,root_mean_squared_error,0.018536,5.396468,0.018536,5.396468,1,True,39
6,LightGBM/T18,-551.774986,root_mean_squared_error,0.015492,4.001491,0.015492,4.001491,1,True,18
7,LightGBM/T5,-551.817534,root_mean_squared_error,0.076072,7.568428,0.076072,7.568428,1,True,5
8,LightGBM/T23,-552.269013,root_mean_squared_error,0.008338,2.062579,0.008338,2.062579,1,True,23
9,CatBoost/T4,-552.271403,root_mean_squared_error,0.019540,11.558334,0.019540,11.558334,1,True,34
10,CatBoost/T20,-552.415038,root_mean_squared_error,0.021225,4.860115,0.021225,4.860115,1,True,50
11,CatBoost/T21,-552.865574,root_mean_squared_error,0.014574,1.731137,0.014574,1.731137,1,True,51
12,CatBoost/T18,-553.554680,root_mean_squared_error,0.045421,21.136452,0.045421,21.136452,1,True,48
13,CatBoost/T30,-553.570542,root_mean_squared_error,0.023504,5.877739,0.023504,5.877739,1,True,60
14,CatBoost/T16,-553.891962,root_mean_squared_error,0.019745,5.255149,0.019745,5.255149,1,True,46

residual_2 leaderboard

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L2,-534.591665,root_mean_squared_error,0.045662,23.573821,0.000152,0.007368,2,True,61
1,LightGBM/T8,-536.222275,root_mean_squared_error,0.005770,2.383398,0.005770,2.383398,1,True,8
2,LightGBM/T15,-536.320481,root_mean_squared_error,0.008774,3.133070,0.008774,3.133070,1,True,15
3,CatBoost/T18,-536.349994,root_mean_squared_error,0.026507,15.390705,0.026507,15.390705,1,True,48
4,LightGBM/T27,-536.379269,root_mean_squared_error,0.008187,2.310156,0.008187,2.310156,1,True,27
5,LightGBM/T18,-536.406019,root_mean_squared_error,0.004459,2.659280,0.004459,2.659280,1,True,18
6,LightGBM/T29,-536.498609,root_mean_squared_error,0.003974,1.717057,0.003974,1.717057,1,True,29
7,LightGBM/T23,-536.586198,root_mean_squared_error,0.003201,1.491458,0.003201,1.491458,1,True,23
8,LightGBM/T20,-536.622523,root_mean_squared_error,0.004442,1.907518,0.004442,1.907518,1,True,20
9,LightGBM/T9,-536.650042,root_mean_squared_error,0.016597,2.311385,0.016597,2.311385,1,True,9
10,LightGBM/T6,-536.698903,root_mean_squared_error,0.004569,1.916455,0.004569,1.916455,1,True,6
11,LightGBM/T30,-536.728773,root_mean_squared_error,0.006044,0.624454,0.006044,0.624454,1,True,30
12,CatBoost/T6,-536.793435,root_mean_squared_error,0.024342,12.104004,0.024342,12.104004,1,True,36
13,CatBoost/T29,-536.927524,root_mean_squared_error,0.038327,18.730359,0.038327,18.730359,1,True,59
14,LightGBM/T2,-536.969346,root_mean_squared_error,0.010884,4.432152,0.010884,4.432152,1,True,2

Saved validation predictions to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_17_two_residual_hpt_validation_predictions.csv
Saved metrics to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_17_two_residual_hpt_metrics.csv

## Runtime guidance

The defaults are intended for a serious final run: 12 trials per model family in each OOF fit and 30 per family in each final layer. With three folds and three layers, this can take several hours. For a smoke test, set `EXP17_OOF_TRIALS_PER_MODEL=2`, `EXP17_FINAL_TRIALS_PER_MODEL=3`, `EXP17_OOF_TIME_LIMIT=120`, and `EXP17_FINAL_TIME_LIMIT=300` before starting the kernel. The smoke-test score must not be reported as the final Exp. 17 result.