# Experiment 6: AutoGluon time-series market trend + tabular residuals

Tree ensembles are strong at property-level interpolation but are not reliable trend extrapolators. This experiment forecasts a dense monthly market series for each `TOWN × FLAT_TYPE` segment, then uses AutoGluon Tabular to model each listing's log-rent relative to that forecast. The final prediction is `market forecast × exp(property residual)`.

The validation split is chronological: the last 12 labelled months are held out. The final forecast origin is the first test month, so no labelled rents from the forecast horizon are used by the market model.

In [1]:
# If needed: pip install autogluon.timeseries autogluon.tabular
from pathlib import Path
import os
import sys
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

configured_root = os.environ.get('KDDM_PROJECT_ROOT')
candidate_roots = ([Path(configured_root)] if configured_root else []) + [
    Path.cwd(), *Path.cwd().parents, Path('/content/KDDM-project'),
    Path('/content/drive/MyDrive/KDDM-project'),
]
project_root = next((p for p in candidate_roots if (p / 'exploration/metul/preprocessing.py').exists()), None)
if project_root is None:
    raise FileNotFoundError('Set KDDM_PROJECT_ROOT to the project directory.')
experiment_dir = project_root / 'exploration' / 'metul'
sys.path.insert(0, str(experiment_dir))

from autogluon.common import space
from autogluon.tabular import TabularPredictor
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
from preprocessing import RentalPreprocessor, load_datasets

RANDOM_STATE = 42
TARGET = 'MONTHLY_RENT'
VALIDATION_HORIZON = 12
MIN_HISTORY_MONTHS = 24
HPO_TRIALS = 25
TS_TRIAL_TIME_LIMIT = int(os.environ.get('EXP6_TS_TRIAL_TIME_LIMIT', '120'))
TS_FINAL_TIME_LIMIT = int(os.environ.get('EXP6_TS_FINAL_TIME_LIMIT', '600'))
TABULAR_HPO_TIME_LIMIT = int(os.environ.get('EXP6_TABULAR_HPO_TIME_LIMIT', '3600'))
TABULAR_FINAL_TIME_LIMIT = int(os.environ.get('EXP6_TABULAR_FINAL_TIME_LIMIT', '3600'))
HPO_KWARGS = {'num_trials': HPO_TRIALS, 'scheduler': 'local', 'searcher': 'random'}

In [2]:
def canonical_flat_type(values):
    """Make `3 room` (train) and `3-room` (test) the same segment."""
    clean = values.fillna('unknown').astype(str).str.lower().str.replace(r'[^a-z0-9]+', '', regex=True)
    return clean.replace({'multigeneration': 'multigeneration'})

def add_segment_and_period(frame):
    result = frame.copy()
    result['period'] = pd.to_datetime(result['RENT_APPROVAL_DATE'] + '-01')
    town = result['TOWN'].fillna('unknown').astype(str).str.strip().str.lower()
    result['market_segment'] = town + ' | ' + canonical_flat_type(result['FLAT_TYPE'])
    return result

data_dir, datasets = load_datasets(project_root / 'data')
raw_train = add_segment_and_period(datasets['train'])
raw_test = add_segment_and_period(datasets['test'])
forecast_origin = raw_test['period'].min()
available_train = raw_train[raw_train['period'] < forecast_origin].copy()
if available_train.empty:
    raise ValueError('No labelled months precede the first test month.')

all_train_periods = np.sort(available_train['period'].unique())
validation_start = pd.Timestamp(all_train_periods[-VALIDATION_HORIZON])
history_raw = available_train[available_train['period'] < validation_start].copy()
validation_raw = available_train[available_train['period'] >= validation_start].copy()

print(f'All labelled history used for final forecast: {available_train.period.min():%Y-%m} to {available_train.period.max():%Y-%m}')
print(f'Forecast origin: {forecast_origin:%Y-%m}; test horizon ends: {raw_test.period.max():%Y-%m}')
print(f'Validation: train through {(validation_start - pd.offsets.MonthBegin(1)):%Y-%m}; holdout from {validation_start:%Y-%m}')

All labelled history used for final forecast: 2021-01 to 2025-02
Forecast origin: 2025-03; test horizon ends: 2026-07
Validation: train through 2024-02; holdout from 2024-03

In [3]:
# Candidate covariates must be present for *every* forecast month.
# COE values and stock values are supplied in the project auxiliary files through 2026-07.
def build_monthly_covariates(datasets):
    month_number = {name: number for number, name in enumerate(
        ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'], 1
    )}
    coe = datasets['coe'].copy()
    coe['period'] = pd.to_datetime(dict(
        year=coe['YEAR'], month=coe['MONTH'].str.lower().map(month_number), day=1
    ))
    for column in ['QUOTA_PREMIUM', 'PREVAILING_QUOTA_PREMIUM', 'QUOTA', 'BIDS_RECEIVED']:
        coe[column] = pd.to_numeric(
            coe[column].astype(str).str.replace('$', '', regex=False).str.replace(',', '', regex=False),
            errors='coerce',
        )
    coe_monthly = coe.groupby('period', as_index=False).agg(
        coe_quota_premium_mean=('QUOTA_PREMIUM', 'mean'),
        coe_prevailing_quota_premium_mean=('PREVAILING_QUOTA_PREMIUM', 'mean'),
        coe_quota_mean=('QUOTA', 'mean'),
        coe_bids_mean=('BIDS_RECEIVED', 'mean'),
    )
    stock = datasets['stock'].copy()
    stock['period'] = pd.to_datetime(stock['DATE']).dt.to_period('M').dt.to_timestamp()
    stock_monthly = stock.groupby('period', as_index=False).agg(
        stock_close_mean=('CLOSE', 'mean'),
        stock_close_median=('CLOSE', 'median'),
        stock_volume_mean=('VOLUME', 'mean'),
    )
    result = coe_monthly.merge(stock_monthly, on='period', how='outer').sort_values('period')
    result['month_sin'] = np.sin(2 * np.pi * result['period'].dt.month / 12)
    result['month_cos'] = np.cos(2 * np.pi * result['period'].dt.month / 12)
    return result

monthly_covariates = build_monthly_covariates(datasets)
candidate_covariates = [
    'coe_quota_premium_mean', 'coe_prevailing_quota_premium_mean', 'coe_quota_mean', 'coe_bids_mean',
    'stock_close_mean', 'stock_close_median', 'stock_volume_mean',
]
market_for_analysis = available_train.groupby('period', as_index=False)[TARGET].mean().rename(columns={TARGET: 'market_rent'})
correlation_base = market_for_analysis.merge(monthly_covariates, on='period', how='left').sort_values('period')
correlation_base['log_market_rent'] = np.log(correlation_base['market_rent'])
correlation_base['monthly_log_rent_change'] = correlation_base['log_market_rent'].diff()
correlation_rows = []
for feature in candidate_covariates:
    for lag_months in (0, 1, 3, 6):
        values = correlation_base[feature].shift(lag_months)
        paired = pd.DataFrame({
            'log_market_rent': correlation_base['log_market_rent'],
            'monthly_log_rent_change': correlation_base['monthly_log_rent_change'],
            feature: values,
        }).dropna()
        correlation_rows.append({
            'feature': feature, 'lag_months': lag_months, 'n_months': len(paired),
            'level_correlation': paired['log_market_rent'].corr(paired[feature]),
            'change_correlation': paired['monthly_log_rent_change'].corr(paired[feature]),
        })
correlation_report = pd.DataFrame(correlation_rows).sort_values('change_correlation', key=lambda s: s.abs(), ascending=False)
correlation_path = experiment_dir / 'exp_6_covariate_correlations.csv'
correlation_report.to_csv(correlation_path, index=False)
display(correlation_report)
print(f'Saved covariate correlations to {correlation_path}')

# Selection after checking the report: bids predicts monthly changes, premium is a useful level proxy,
# and sin/cos expose calendar seasonality. Quota is excluded because it is nearly collinear with bids;
# stock aggregates are excluded because their change correlations are weak and unstable.
KNOWN_COVARIATES = ['coe_bids_mean', 'coe_quota_premium_mean', 'month_sin', 'month_cos']
required_periods = pd.date_range(available_train['period'].min(), raw_test['period'].max(), freq='MS')
covariate_coverage = monthly_covariates.set_index('period').reindex(required_periods)[KNOWN_COVARIATES]
if covariate_coverage.isna().any().any():
    raise ValueError(f'Missing known-covariate values: {covariate_coverage.isna().sum().to_dict()}')
print('Selected known covariates:', KNOWN_COVARIATES)

,feature,lag_months,n_months,level_correlation,change_correlation
12,coe_bids_mean,0,49,-0.013767,-0.419916
8,coe_quota_mean,0,49,-0.115834,-0.407143
7,coe_prevailing_quota_premium_mean,6,44,0.946004,-0.390066
13,coe_bids_mean,1,49,-0.151219,-0.369908
9,coe_quota_mean,1,49,-0.258741,-0.364655
3,coe_quota_premium_mean,6,44,0.930753,-0.351106
6,coe_prevailing_quota_premium_mean,3,47,0.961676,-0.319496
22,stock_close_median,3,47,0.195332,0.279248
20,stock_close_median,0,49,0.007782,0.259783
14,coe_bids_mean,3,47,-0.254031,-0.258512
10,coe_quota_mean,3,47,-0.372295,-0.241389
2,coe_quota_premium_mean,3,47,0.934703,-0.219682
5,coe_prevailing_quota_premium_mean,1,49,0.964924,-0.208828
21,stock_close_median,1,49,0.091727,0.204207
27,stock_volume_mean,6,44,-0.434204,0.191955
18,stock_close_mean,3,47,-0.004235,0.180583
15,coe_bids_mean,6,44,-0.394707,-0.179863
4,coe_prevailing_quota_premium_mean,0,49,0.959776,-0.164245
11,coe_quota_mean,6,44,-0.539400,-0.150902
26,stock_volume_mean,3,47,-0.386753,0.133353
25,stock_volume_mean,1,49,-0.416061,0.113548
16,stock_close_mean,0,49,-0.042019,-0.104382
24,stock_volume_mean,0,49,-0.367538,0.097091
1,coe_quota_premium_mean,1,49,0.921791,-0.096602
19,stock_close_mean,6,44,-0.003597,0.092362
23,stock_close_median,6,44,0.333089,0.087152
0,coe_quota_premium_mean,0,49,0.903492,-0.083515
17,stock_close_mean,1,49,-0.026947,0.009624

Saved covariate correlations to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_6_covariate_correlations.csv
Selected known covariates: ['coe_bids_mean', 'coe_quota_premium_mean', 'month_sin', 'month_cos']

In [4]:
def monthly_market(frame):
    monthly = (frame.groupby(['market_segment', 'period'], as_index=False)[TARGET].mean()
        .rename(columns={'market_segment': 'item_id', 'period': 'timestamp', TARGET: 'target'})
        .sort_values(['item_id', 'timestamp']))
    eligible = monthly.groupby('item_id')['target'].count()
    monthly = monthly[monthly['item_id'].isin(eligible[eligible >= MIN_HISTORY_MONTHS].index)]
    return monthly.merge(monthly_covariates[['period', *KNOWN_COVARIATES]], left_on='timestamp', right_on='period', how='left').drop(columns='period')

def as_ts(frame):
    return TimeSeriesDataFrame.from_data_frame(frame, id_column='item_id', timestamp_column='timestamp')

def market_actual(frame):
    return (frame.groupby(['market_segment', 'period'], as_index=False)[TARGET].mean()
        .rename(columns={TARGET: 'actual_market_rent'}))

def make_future_known_covariates(predictor, history_ts):
    future = predictor.make_future_data_frame(history_ts).reset_index()
    future = future.merge(monthly_covariates[['period', *KNOWN_COVARIATES]], left_on='timestamp', right_on='period', how='left').drop(columns='period')
    if future[KNOWN_COVARIATES].isna().any().any():
        raise ValueError('A selected known covariate is unavailable in the forecast horizon.')
    return as_ts(future[['item_id', 'timestamp', *KNOWN_COVARIATES]])

def sample_ts_params(rng):
    return {
        'num_leaves': int(rng.integers(16, 129)),
        'num_boost_round': int(rng.integers(200, 1501)),
        'max_depth': int(rng.integers(3, 11)),
        'learning_rate': float(10 ** rng.uniform(np.log10(0.01), np.log10(0.20))),
        'min_data_in_leaf': int(rng.integers(10, 151)),
        'feature_fraction': float(rng.uniform(0.60, 1.00)),
        'bagging_fraction': float(rng.uniform(0.60, 1.00)),
    }

def ts_hyperparameters(params):
    # Recursive/Direct Tabular use LightGBM internally. num_boost_round is the iteration count.
    return {
        'RecursiveTabular': {'model_name': 'GBM', 'model_hyperparameters': dict(params)},
        'DirectTabular': {'model_name': 'GBM', 'model_hyperparameters': dict(params)},
        'Theta': {},
        'ETS': {},
    }

def fit_market_model(history, prediction_length, model_path, params, time_limit):
    history_ts = as_ts(monthly_market(history))
    predictor = TimeSeriesPredictor(
        target='target', prediction_length=prediction_length, freq='MS', eval_metric='RMSE',
        known_covariates_names=KNOWN_COVARIATES, path=str(model_path),
    )
    predictor.fit(
        train_data=history_ts, hyperparameters=ts_hyperparameters(params),
        enable_ensemble=True, num_val_windows=2, time_limit=time_limit,
        random_seed=RANDOM_STATE, verbosity=2,
    )
    return predictor, predictor.predict(history_ts, known_covariates=make_future_known_covariates(predictor, history_ts))

def score_market_forecast(forecast, actual_rows):
    predicted = forecast.reset_index()[['item_id', 'timestamp', 'mean']].rename(
        columns={'item_id': 'market_segment', 'timestamp': 'period', 'mean': 'market_rent_forecast'}
    )
    scored = market_actual(actual_rows).merge(predicted, on=['market_segment', 'period'], how='inner')
    return mean_squared_error(scored['actual_market_rent'], scored['market_rent_forecast']) ** 0.5

# Manual outer-loop HPO gives each of the 25 configurations the same future 12-month backtest.
# It avoids relying on nested search-space support in TimeSeriesPredictor.
rng = np.random.default_rng(RANDOM_STATE)
ts_hpo_rows = []
for trial in range(1, HPO_TRIALS + 1):
    params = sample_ts_params(rng)
    _, trial_forecast = fit_market_model(
        history_raw, VALIDATION_HORIZON, experiment_dir / 'ag_exp6_ts_hpo' / f'trial_{trial:02d}',
        params, TS_TRIAL_TIME_LIMIT,
    )
    ts_hpo_rows.append({'trial': trial, 'market_RMSE': score_market_forecast(trial_forecast, validation_raw), **params})
ts_hpo_results = pd.DataFrame(ts_hpo_rows).sort_values('market_RMSE').reset_index(drop=True)
ts_hpo_path = experiment_dir / 'exp_6_timeseries_hpo_results.csv'
ts_hpo_results.to_csv(ts_hpo_path, index=False)
display(ts_hpo_results.head(10))
print(f'Saved {len(ts_hpo_results)} time-series trials to {ts_hpo_path}')
BEST_TS_PARAMS = ts_hpo_results.iloc[0].drop(labels=['trial', 'market_RMSE']).to_dict()
BEST_TS_PARAMS = {key: int(value) if key in {'num_leaves', 'num_boost_round', 'max_depth', 'min_data_in_leaf'} else float(value) for key, value in BEST_TS_PARAMS.items()}

validation_ts_predictor, validation_market_forecast = fit_market_model(
    history_raw, VALIDATION_HORIZON, experiment_dir / 'ag_exp6_ts_validation_hpo',
    BEST_TS_PARAMS, TS_FINAL_TIME_LIMIT,
)
display(validation_ts_predictor.leaderboard(silent=True))

validation_market = validation_market_forecast.reset_index()[['item_id', 'timestamp', 'mean']].rename(
    columns={'item_id': 'market_segment', 'timestamp': 'period', 'mean': 'market_rent_forecast'}
)
validation_with_market = validation_raw.merge(validation_market, on=['market_segment', 'period'], how='left')
print('Validation listings covered by a market forecast:', validation_with_market.market_rent_forecast.notna().mean())

Beginning AutoGluon training... Time limit = 120s
AutoGluon will save models to '/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_ts_hpo/trial_01'
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.90 GB / 16.00 GB (30.6%)
Disk Space Avail:   197.27 GB / 460.38 GB (42.8%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': RMSE,
 'freq': 'MS',
 'hyperparameters': {'DirectTabular': {'model_hyperparameters': {'bagging_fraction': 0.6376709391550598,
                                                                 'feature_fraction': 0.8789472116237456,
                                                                 'learning_rate': 0.130936777431576,
                                                                 'max_depth': 8,
                                                                 'min_data_in_leaf': 71,
                                                                 'num_boost_round': 1206,
                                                                 'num_leaves': 26},
                                       'model_name': 'GBM'},
                     'ETS': {},
                     'RecursiveTabular': {'model_hyperparameters': {'bagging_fraction': 0.6376709391550598,
                                                                    'feature_fraction': 0.8789472116237456,
                                                                    'learning_rate': 0.130936777431576,
                                                                    'max_depth': 8,
                                                                    'min_data_in_leaf': 71,
                                                                    'num_boost_round': 1206,
                                                                    'num_leaves': 26},
                                          'model_name': 'GBM'},
                     'Theta': {}},
 'known_covariates_names': ['coe_bids_mean',
                            'coe_quota_premium_mean',
                            'month_sin',
                            'month_cos'],
 'num_val_windows': 2,
 'prediction_length': 12,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 42,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'time_limit': 120,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'MS'.
Provided train_data has 4325 rows (NaN fraction=3.1%), 114 time series. Median time series length is 38 (min=36, max=38).
	Removing 2 short time series from train_data. Only series with length >= 37 will be used for training.
	After filtering, train_data has 4253 rows (NaN fraction=2.7%), 112 time series. Median time series length is 38 (min=37, max=38).

Provided data contains following columns:
	target: 'target'
	known_covariates:
		categorical:        []
		continuous (float): ['coe_bids_mean', 'coe_quota_premium_mean', 'month_sin', 'month_cos']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-09-22 11:33:49
Models that will be trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model RecursiveTabular. Training for up to 23.5s of the 117.5s of remaining time.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-452.9109     = Validation score (-RMSE)
	0.76    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 29.2s of the 116.7s of remaining time.
	-801.6295     = Validation score (-RMSE)
	1.74    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 38.3s of the 115.0s of remaining time.
	-519.1526     = Validation score (-RMSE)
	2.12    s     = Training runtime
	0.16    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 56.3s of the 112.7s of remaining time.
	-409.9331     = Validation score (-RMSE)
	0.05    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 112.6s.
	Ensemble weights: {'RecursiveTabular': 0.25, 'Theta': 0.75}
	-403.1580     = Validation score (-RMSE)
	0.10    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training complete. Models trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 5.49 s
Best model: WeightedEnsemble
Best model score: -403.1580
data with frequency 'IRREG' has been resampled to frequency 'MS'.
data with frequency 'IRREG' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
Beginning AutoGluon training... Time limit = 120s
AutoGluon will save models to '/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_ts_hpo/trial_02'
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.36 GB / 16.00 GB (27.2%)
Disk Space Avail:   197.26 GB / 460.38 GB (42.8%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': RMSE,
 'freq': 'MS',
 'hyperparameters': {'DirectTabular': {'model_hyperparameters': {'bagging_fraction': 0.7801543751582268,
                                                                 'feature_fraction': 0.6512454530702183,
                                                                 'learning_rate': 0.10536424018957688,
                                                                 'max_depth': 8,
                                                                 'min_data_in_leaf': 117,
                                                                 'num_boost_round': 1469,
                                                                 'num_leaves': 75},
                                       'model_name': 'GBM'},
                     'ETS': {},
                     'RecursiveTabular': {'model_hyperparameters': {'bagging_fraction': 0.7801543751582268,
                                                                    'feature_fraction': 0.6512454530702183,
                                                                    'learning_rate': 0.10536424018957688,
                                                                    'max_depth': 8,
                                                                    'min_data_in_leaf': 117,
                                                                    'num_boost_round': 1469,
                                                                    'num_leaves': 75},
                                          'model_name': 'GBM'},
                     'Theta': {}},
 'known_covariates_names': ['coe_bids_mean',
                            'coe_quota_premium_mean',
                            'month_sin',
                            'month_cos'],
 'num_val_windows': 2,
 'prediction_length': 12,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 42,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'time_limit': 120,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'MS'.
Provided train_data has 4325 rows (NaN fraction=3.1%), 114 time series. Median time series length is 38 (min=36, max=38).
	Removing 2 short time series from train_data. Only series with length >= 37 will be used for training.
	After filtering, train_data has 4253 rows (NaN fraction=2.7%), 112 time series. Median time series length is 38 (min=37, max=38).

Provided data contains following columns:
	target: 'target'
	known_covariates:
		categorical:        []
		continuous (float): ['coe_bids_mean', 'coe_quota_premium_mean', 'month_sin', 'month_cos']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-09-22 11:33:55
Models that will be trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model RecursiveTabular. Training for up to 24.0s of the 119.9s of remaining time.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-453.8793     = Validation score (-RMSE)
	0.49    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 29.8s of the 119.4s of remaining time.
	-794.2583     = Validation score (-RMSE)
	1.20    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 39.4s of the 118.2s of remaining time.
	-519.1526     = Validation score (-RMSE)
	0.05    s     = Training runtime
	0.16    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 59.0s of the 118.0s of remaining time.
	-409.9331     = Validation score (-RMSE)
	0.05    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 117.9s.
	Ensemble weights: {'RecursiveTabular': 0.25, 'Theta': 0.75}
	-402.5621     = Validation score (-RMSE)
	0.10    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training complete. Models trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 2.16 s
Best model: WeightedEnsemble
Best model score: -402.5621
data with frequency 'IRREG' has been resampled to frequency 'MS'.
data with frequency 'IRREG' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
Beginning AutoGluon training... Time limit = 120s
AutoGluon will save models to '/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_ts_hpo/trial_03'
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.30 GB / 16.00 GB (26.9%)
Disk Space Avail:   197.26 GB / 460.38 GB (42.8%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': RMSE,
 'freq': 'MS',
 'hyperparameters': {'DirectTabular': {'model_hyperparameters': {'bagging_fraction': 0.7773656795309324,
                                                                 'feature_fraction': 0.929104645308332,
                                                                 'learning_rate': 0.0688157479270427,
                                                                 'max_depth': 4,
                                                                 'min_data_in_leaf': 140,
                                                                 'num_boost_round': 682,
                                                                 'num_leaves': 72},
                                       'model_name': 'GBM'},
                     'ETS': {},
                     'RecursiveTabular': {'model_hyperparameters': {'bagging_fraction': 0.7773656795309324,
                                                                    'feature_fraction': 0.929104645308332,
                                                                    'learning_rate': 0.0688157479270427,
                                                                    'max_depth': 4,
                                                                    'min_data_in_leaf': 140,
                                                                    'num_boost_round': 682,
                                                                    'num_leaves': 72},
                                          'model_name': 'GBM'},
                     'Theta': {}},
 'known_covariates_names': ['coe_bids_mean',
                            'coe_quota_premium_mean',
                            'month_sin',
                            'month_cos'],
 'num_val_windows': 2,
 'prediction_length': 12,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 42,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'time_limit': 120,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'MS'.
Provided train_data has 4325 rows (NaN fraction=3.1%), 114 time series. Median time series length is 38 (min=36, max=38).
	Removing 2 short time series from train_data. Only series with length >= 37 will be used for training.
	After filtering, train_data has 4253 rows (NaN fraction=2.7%), 112 time series. Median time series length is 38 (min=37, max=38).

Provided data contains following columns:
	target: 'target'
	known_covariates:
		categorical:        []
		continuous (float): ['coe_bids_mean', 'coe_quota_premium_mean', 'month_sin', 'month_cos']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-09-22 11:33:57
Models that will be trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model RecursiveTabular. Training for up to 24.0s of the 119.9s of remaining time.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].
	-472.4365     = Validation score (-RMSE)
	0.48    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 29.9s of the 119.4s of remaining time.
	-797.3358     = Validation score (-RMSE)
	0.91    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 39.5s of the 118.5s of remaining time.
	-519.1526     = Validation score (-RMSE)
	0.05    s     = Training runtime
	0.16    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 59.1s of the 118.3s of remaining time.
	-409.9331     = Validation score (-RMSE)
	0.05    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 118.2s.
	Ensemble weights: {'RecursiveTabular': 0.17, 'Theta': 0.83}
	-406.3883     = Validation score (-RMSE)
	0.10    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training complete. Models trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 1.88 s
Best model: WeightedEnsemble
Best model score: -406.3883
data with frequency 'IRREG' has been resampled to frequency 'MS'.
data with frequency 'IRREG' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
Beginning AutoGluon training... Time limit = 120s
AutoGluon will save models to '/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_ts_hpo/trial_04'
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.25 GB / 16.00 GB (26.6%)
Disk Space Avail:   197.26 GB / 460.38 GB (42.8%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': RMSE,
 'freq': 'MS',
 'hyperparameters': {'DirectTabular': {'model_hyperparameters': {'bagging_fraction': 0.852665759648826,
                                                                 'feature_fraction': 0.9310524687970329,
                                                                 'learning_rate': 0.012106766445987188,
                                                                 'max_depth': 3,
                                                                 'min_data_in_leaf': 88,
                                                                 'num_boost_round': 495,
                                                                 'num_leaves': 66},
                                       'model_name': 'GBM'},
                     'ETS': {},
                     'RecursiveTabular': {'model_hyperparameters': {'bagging_fraction': 0.852665759648826,
                                                                    'feature_fraction': 0.9310524687970329,
                                                                    'learning_rate': 0.012106766445987188,
                                                                    'max_depth': 3,
                                                                    'min_data_in_leaf': 88,
                                                                    'num_boost_round': 495,
                                                                    'num_leaves': 66},
                                          'model_name': 'GBM'},
                     'Theta': {}},
 'known_covariates_names': ['coe_bids_mean',
                            'coe_quota_premium_mean',
                            'month_sin',
                            'month_cos'],
 'num_val_windows': 2,
 'prediction_length': 12,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 42,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'time_limit': 120,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'MS'.

,trial,market_RMSE,num_leaves,num_boost_round,max_depth,learning_rate,min_data_in_leaf,feature_fraction,bagging_fraction
0,23,273.239648,30,792,8,0.025007,38,0.831688,0.670709
1,3,273.280502,72,682,4,0.068816,140,0.929105,0.777366
2,7,273.639107,120,1168,5,0.026540,146,0.748184,0.787822
3,4,273.711508,66,495,3,0.012107,88,0.931052,0.852666
4,5,273.838858,34,1186,8,0.183192,59,0.957248,0.911353
5,11,274.096465,110,460,9,0.105636,11,0.865940,0.882066
6,16,274.107157,112,566,10,0.072640,51,0.822813,0.913559
7,17,274.511769,128,1064,6,0.114568,67,0.666789,0.609085
8,10,274.851048,65,1246,9,0.023720,64,0.872998,0.655901
9,1,275.367054,26,1206,8,0.130937,71,0.878947,0.637671

Beginning AutoGluon training... Time limit = 600s
AutoGluon will save models to '/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_ts_validation_hpo'
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.23 GB / 16.00 GB (26.4%)
Disk Space Avail:   197.22 GB / 460.38 GB (42.8%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': RMSE,
 'freq': 'MS',
 'hyperparameters': {'DirectTabular': {'model_hyperparameters': {'bagging_fraction': 0.6707091131756927,
                                                                 'feature_fraction': 0.8316878275767584,
                                                                 'learning_rate': 0.025006835969478818,
                                                                 'max_depth': 8,
                                                                 'min_data_in_leaf': 38,
                                                                 'num_boost_round': 792,
                                                                 'num_leaves': 30},
                                       'model_name': 'GBM'},
                     'ETS': {},
                     'RecursiveTabular': {'model_hyperparameters': {'bagging_fraction': 0.6707091131756927,
                                                                    'feature_fraction': 0.8316878275767584,
                                                                    'learning_rate': 0.025006835969478818,
                                                                    'max_depth': 8,
                                                                    'min_data_in_leaf': 38,
                                                                    'num_boost_round': 792,
                                                                    'num_leaves': 30},
                                          'model_name': 'GBM'},
                     'Theta': {}},
 'known_covariates_names': ['coe_bids_mean',
                            'coe_quota_premium_mean',
                            'month_sin',
                            'month_cos'],
 'num_val_windows': 2,
 'prediction_length': 12,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 42,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'time_limit': 600,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'MS'.
Provided train_data has 4325 rows (NaN fraction=3.1%), 114 time series. Median time series length is 38 (min=36, max=38).
	Removing 2 short time series from train_data. Only series with length >= 37 will be used for training.
	After filtering, train_data has 4253 rows (NaN fraction=2.7%), 112 time series. Median time series length is 38 (min=37, max=38).

Provided data contains following columns:
	target: 'target'
	known_covariates:
		categorical:        []
		continuous (float): ['coe_bids_mean', 'coe_quota_premium_mean', 'month_sin', 'month_cos']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-09-22 11:35:02
Models that will be trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model RecursiveTabular. Training for up to 120.0s of the 599.9s of remaining time.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].

Saved 25 time-series trials to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_6_timeseries_hpo_results.csv

	-458.1650     = Validation score (-RMSE)
	1.12    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 149.7s of the 598.7s of remaining time.
	-802.9600     = Validation score (-RMSE)
	1.32    s     = Training runtime
	0.02    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 199.1s of the 597.4s of remaining time.
	-519.1526     = Validation score (-RMSE)
	0.05    s     = Training runtime
	0.17    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 298.6s of the 597.2s of remaining time.
	-409.9331     = Validation score (-RMSE)
	0.06    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 597.1s.
	Ensemble weights: {'RecursiveTabular': 0.23, 'Theta': 0.77}
	-404.2505     = Validation score (-RMSE)
	0.11    s     = Training runtime
	0.06    s     = Validation (prediction) runtime
Training complete. Models trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 2.95 s
Best model: WeightedEnsemble
Best model score: -404.2505
data with frequency 'IRREG' has been resampled to frequency 'MS'.
data with frequency 'IRREG' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

              model   score_val  pred_time_val  fit_time_marginal  fit_order
0  WeightedEnsemble -404.250545       0.060942           0.108194          5
1             Theta -409.933106       0.039860           0.056015          4
2  RecursiveTabular -458.164971       0.020686           1.122381          1
3               ETS -519.152596       0.171024           0.051750          3
4     DirectTabular -802.960007       0.017151           1.319275          2

Validation listings covered by a market forecast: 0.99708297932597

In [5]:
def attach_observed_market_residual(frame, market_source):
    market = (market_source.groupby(['market_segment', 'period'], as_index=False)[TARGET].mean()
        .rename(columns={TARGET: 'observed_market_rent'}))
    result = frame.merge(market, on=['market_segment', 'period'], how='left')
    result['LOG_RENT_RESIDUAL'] = np.log(result[TARGET]) - np.log(result['observed_market_rent'])
    return result

def prepare_tabular_features(frame):
    result = frame.drop(columns=[TARGET, 'LOG_RENT_RESIDUAL', 'observed_market_rent', 'market_segment', 'period'], errors='ignore').copy()
    result['RENT_APPROVAL_DATE'] = pd.to_datetime(result['RENT_APPROVAL_DATE'] + '-01')
    return result

# The residual labels are relative to the observed market at training time.
# At inference, the observed market is replaced by the time-series forecast.
residual_train_raw = attach_observed_market_residual(history_raw, history_raw)
residual_valid_raw = attach_observed_market_residual(validation_raw, validation_raw)

validation_preprocessor = RentalPreprocessor(datasets)
residual_train = validation_preprocessor.fit_transform(residual_train_raw)
residual_valid = validation_preprocessor.transform(residual_valid_raw)
X_residual_train = prepare_tabular_features(residual_train)
X_residual_valid = prepare_tabular_features(residual_valid)

# 25 random-search trials per model family. The GBM search tunes leaves, boosting rounds
# (iterations), tree depth and learning rate; CatBoost provides a complementary tree family.
TABULAR_HYPERPARAMETERS = {
    'GBM': {
        'num_leaves': space.Int(16, 128),
        'num_boost_round': space.Int(200, 1500),
        'max_depth': space.Int(3, 12),
        'learning_rate': space.Real(0.01, 0.20, log=True),
        'min_data_in_leaf': space.Int(10, 150),
        'feature_fraction': space.Real(0.60, 1.00),
        'bagging_fraction': space.Real(0.60, 1.00),
    },
    'CAT': {
        'iterations': space.Int(200, 1500),
        'depth': space.Int(4, 10),
        'learning_rate': space.Real(0.01, 0.20, log=True),
        'l2_leaf_reg': space.Real(1.0, 30.0, log=True),
    },
}

residual_predictor = TabularPredictor(
    label='LOG_RENT_RESIDUAL', problem_type='regression', eval_metric='root_mean_squared_error',
    path=str(experiment_dir / 'ag_exp6_residual_validation'),
).fit(
    train_data=X_residual_train.assign(LOG_RENT_RESIDUAL=residual_train['LOG_RENT_RESIDUAL'].to_numpy()),
    tuning_data=X_residual_valid.assign(LOG_RENT_RESIDUAL=residual_valid['LOG_RENT_RESIDUAL'].to_numpy()),
    hyperparameters=TABULAR_HYPERPARAMETERS, hyperparameter_tune_kwargs=HPO_KWARGS,
    presets='medium_quality', time_limit=TABULAR_HPO_TIME_LIMIT, verbosity=2,
)
display(residual_predictor.leaderboard(silent=True, extra_info=True))

valid_residual_prediction = residual_predictor.predict(X_residual_valid).to_numpy()
validation_with_market['residual_prediction'] = valid_residual_prediction
validation_with_market['prediction'] = (
    validation_with_market['market_rent_forecast'] * np.exp(validation_with_market['residual_prediction'])
)
scored = validation_with_market.dropna(subset=['prediction'])
display(pd.DataFrame([{
    'RMSE': mean_squared_error(scored[TARGET], scored['prediction']) ** 0.5,
    'MAE': mean_absolute_error(scored[TARGET], scored['prediction']),
    'R2': r2_score(scored[TARGET], scored['prediction']),
    'Scored listings': len(scored),
}]))

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_residual_validation"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.14 GB / 16.00 GB (25.9%)
Disk Space Avail:   197.22 GB / 460.38 GB (42.8%)
===================================================
Presets specified: ['medium_quality']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 3600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_residual_validation"
Train Data Rows:    111658
Train Data Columns: 33
Tuning Data Rows:    35310
Tuning Data Columns: 33
Label Column:       LOG_RENT_RESIDUAL
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4322.95 MB
	Train Data (Original)  Memory Usage: 85.81 MB (2.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 2): ['FURNISHED', 'FEE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('datetime', []) :  1 | ['RENT_APPROVAL_DATE']
		('float', [])    : 12 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'MAX_FLOOR', 'YEAR_COMPLETED', ...]
		('int', [])      : 12 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('object', [])   :  6 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])             :  6 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('float', [])                : 12 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'MAX_FLOOR', 'YEAR_COMPLETED', ...]
		('int', [])                  : 12 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('int', ['datetime_as_int']) :  2 | ['RENT_APPROVAL_DATE', 'RENT_APPROVAL_DATE.dayofweek']
	0.3s = Fit runtime
	31 features in original data used to generate 32 features in processed data.
	Train Data (Processed) Memory Usage: 30.28 MB (0.7% of available memory)
Data preprocessing and feature engineering runtime = 0.31s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=16, upper=128, 'num_boost_round': Int: lower=200, upper=1500, 'max_depth': Int: lower=3, upper=12, 'learning_rate': Real: lower=0.01, upper=0.2, 'min_data_in_leaf': Int: lower=10, upper=150, 'feature_fraction': Real: lower=0.6, upper=1.0, 'bagging_fraction': Real: lower=0.6, upper=1.0}],
	'CAT': [{'iterations': Int: lower=200, upper=1500, 'depth': Int: lower=4, upper=10, 'learning_rate': Real: lower=0.01, upper=0.2, 'l2_leaf_reg': Real: lower=1.0, upper=30.0}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 1619.86s of the 3599.69s of remaining time.
/Users/metul/Desktop/KDDM-project/venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
 36%|███▌      | 9/25 [00:11<00:23,  1.50s/it]

[1000]	valid_set's rmse: 0.181323

 56%|█████▌    | 14/25 [00:30<00:35,  3.19s/it]

[1000]	valid_set's rmse: 0.181426

100%|██████████| 25/25 [01:04<00:00,  2.57s/it]
Fitted model: LightGBM/T1 ...
	-0.1835	 = Validation score   (-root_mean_squared_error)
	0.52s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-0.1814	 = Validation score   (-root_mean_squared_error)
	1.15s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-0.1814	 = Validation score   (-root_mean_squared_error)
	0.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-0.1813	 = Validation score   (-root_mean_squared_error)
	1.9s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-0.1818	 = Validation score   (-root_mean_squared_error)
	0.71s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-0.1813	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-0.1814	 = Validation score   (-root_mean_squared_error)
	2.37s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-0.1814	 = Validation score   (-root_mean_squared_error)
	1.18s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-0.1815	 = Validation score   (-root_mean_squared_error)
	1.45s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-0.1813	 = Validation score   (-root_mean_squared_error)
	6.27s	 = Training   runtime
	0.24s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-0.1813	 = Validation score   (-root_mean_squared_error)
	4.48s	 = Training   runtime
	0.16s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-0.1811	 = Validation score   (-root_mean_squared_error)
	1.71s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T13 ...
	-0.1815	 = Validation score   (-root_mean_squared_error)
	1.54s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: LightGBM/T14 ...
	-0.1812	 = Validation score   (-root_mean_squared_error)
	4.34s	 = Training   runtime
	0.19s	 = Validation runtime
Fitted model: LightGBM/T15 ...
	-0.1814	 = Validation score   (-root_mean_squared_error)
	4.46s	 = Training   runtime
	0.2s	 = Validation runtime
Fitted model: LightGBM/T16 ...
	-0.1815	 = Validation score   (-root_mean_squared_error)
	1.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T17 ...
	-0.181	 = Validation score   (-root_mean_squared_error)
	3.33s	 = Training   runtime
	0.09s	 = Validation runtime
Fitted model: LightGBM/T18 ...
	-0.1813	 = Validation score   (-root_mean_squared_error)
	2.7s	 = Training   runtime
	0.12s	 = Validation runtime
Fitted model: LightGBM/T19 ...
	-0.1817	 = Validation score   (-root_mean_squared_error)
	1.23s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T20 ...
	-0.1817	 = Validation score   (-root_mean_squared_error)
	1.9s	 = Training   runtime
	0.12s	 = Validation runtime
Fitted model: LightGBM/T21 ...
	-0.1812	 = Validation score   (-root_mean_squared_error)
	1.85s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T22 ...
	-0.1813	 = Validation score   (-root_mean_squared_error)
	0.89s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T23 ...
	-0.1811	 = Validation score   (-root_mean_squared_error)
	7.88s	 = Training   runtime
	0.21s	 = Validation runtime
Fitted model: LightGBM/T24 ...
	-0.1812	 = Validation score   (-root_mean_squared_error)
	3.29s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: LightGBM/T25 ...
	-0.1812	 = Validation score   (-root_mean_squared_error)
	2.95s	 = Training   runtime
	0.11s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 1619.86s of the 3535.39s of remaining time.
100%|██████████| 25/25 [07:48<00:00, 18.73s/it]
Fitted model: CatBoost/T1 ...
	-0.1831	 = Validation score   (-root_mean_squared_error)
	1.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-0.1804	 = Validation score   (-root_mean_squared_error)
	17.6s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-0.1804	 = Validation score   (-root_mean_squared_error)
	25.05s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-0.1805	 = Validation score   (-root_mean_squared_error)
	32.64s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-0.1806	 = Validation score   (-root_mean_squared_error)
	40.89s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-0.1806	 = Validation score   (-root_mean_squared_error)
	4.87s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-0.1805	 = Validation score   (-root_mean_squared_error)
	12.8s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-0.1805	 = Validation score   (-root_mean_squared_error)
	22.99s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-0.1804	 = Validation score   (-root_mean_squared_error)
	23.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-0.1812	 = Validation score   (-root_mean_squared_error)
	8.19s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-0.1807	 = Validation score   (-root_mean_squared_error)
	27.55s	 = Training   runtime
	0.06s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-0.1805	 = Validation score   (-root_mean_squared_error)
	36.13s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: CatBoost/T13 ...
	-0.1809	 = Validation score   (-root_mean_squared_error)
	8.1s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T14 ...
	-0.1818	 = Validation score   (-root_mean_squared_error)
	5.37s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T15 ...
	-0.1804	 = Validation score   (-root_mean_squared_error)
	31.66s	 = Training   runtime
	0.07s	 = Validation runtime
Fitted model: CatBoost/T16 ...
	-0.1811	 = Validation score   (-root_mean_squared_error)
	7.37s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T17 ...
	-0.1807	 = Validation score   (-root_mean_squared_error)
	5.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T18 ...
	-0.1804	 = Validation score   (-root_mean_squared_error)
	37.57s	 = Training   runtime
	0.08s	 = Validation runtime
Fitted model: CatBoost/T19 ...
	-0.1805	 = Validation score   (-root_mean_squared_error)
	29.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T20 ...
	-0.1808	 = Validation score   (-root_mean_squared_error)
	18.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitted model: CatBoost/T21 ...
	-0.1809	 = Validation score   (-root_mean_squared_error)
	20.29s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T22 ...
	-0.1806	 = Validation score   (-root_mean_squared_error)
	19.88s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T23 ...
	-0.1806	 = Validation score   (-root_mean_squared_error)
	13.0s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: CatBoost/T24 ...
	-0.1812	 = Validation score   (-root_mean_squared_error)
	7.38s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: CatBoost/T25 ...
	-0.1807	 = Validation score   (-root_mean_squared_error)
	8.32s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 3062.97s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.0 GB
	Ensemble Weights: {'CatBoost/T9': 0.333, 'LightGBM/T18': 0.111, 'LightGBM/T21': 0.111, 'CatBoost/T8': 0.111, 'CatBoost/T19': 0.111, 'LightGBM/T23': 0.056, 'LightGBM/T24': 0.056, 'CatBoost/T4': 0.056, 'CatBoost/T18': 0.056}
	-0.1799	 = Validation score   (-root_mean_squared_error)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 537.09s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 50433.8 rows/s (35310 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_residual_validation")

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order,...,hyperparameters,hyperparameters_fit,ag_args_fit,features,compile_time,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
0,WeightedEnsemble_L2,-0.179918,root_mean_squared_error,0.700126,162.078636,0.000345,0.035074,2,True,51,...,"{'use_orig_features': False, 'valid_stacker': ...",{},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[CatBoost/T8, LightGBM/T21, CatBoost/T18, Ligh...",None,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 18},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[CatBoost/T8, LightGBM/T21, CatBoost/T18, Ligh...",[]
1,CatBoost/T9,-0.180353,root_mean_squared_error,0.046356,23.489505,0.046356,23.489505,1,True,34,...,"{'iterations': 1489, 'learning_rate': 0.097046...",{'iterations': 1114},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
2,CatBoost/T18,-0.180376,root_mean_squared_error,0.076837,37.573131,0.076837,37.573131,1,True,43,...,"{'iterations': 1355, 'learning_rate': 0.057148...",{'iterations': 1339},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
3,CatBoost/T2,-0.180399,root_mean_squared_error,0.042024,17.598876,0.042024,17.598876,1,True,27,...,"{'iterations': 759, 'learning_rate': 0.0608433...",{'iterations': 706},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
4,CatBoost/T15,-0.180413,root_mean_squared_error,0.065444,31.661095,0.065444,31.661095,1,True,40,...,"{'iterations': 1343, 'learning_rate': 0.029239...",{'iterations': 1343},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
5,CatBoost/T3,-0.180419,root_mean_squared_error,0.056052,25.050864,0.056052,25.050864,1,True,28,...,"{'iterations': 1233, 'learning_rate': 0.031629...",{'iterations': 1233},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
6,CatBoost/T12,-0.180458,root_mean_squared_error,0.074365,36.128035,0.074365,36.128035,1,True,37,...,"{'iterations': 1277, 'learning_rate': 0.019464...",{'iterations': 1274},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
7,CatBoost/T8,-0.180464,root_mean_squared_error,0.045856,22.987587,0.045856,22.987587,1,True,33,...,"{'iterations': 859, 'learning_rate': 0.0866093...",{'iterations': 500},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
8,CatBoost/T4,-0.180474,root_mean_squared_error,0.055904,32.635080,0.055904,32.635080,1,True,29,...,"{'iterations': 800, 'learning_rate': 0.0418269...",{'iterations': 735},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
9,CatBoost/T19,-0.180498,root_mean_squared_error,0.046845,29.637695,0.046845,29.637695,1,True,44,...,"{'iterations': 1367, 'learning_rate': 0.064744...",{'iterations': 474},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
10,CatBoost/T7,-0.180521,root_mean_squared_error,0.036951,12.799440,0.036951,12.799440,1,True,32,...,"{'iterations': 1050, 'learning_rate': 0.110156...",{'iterations': 1029},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
11,CatBoost/T23,-0.180550,root_mean_squared_error,0.035949,13.002666,0.035949,13.002666,1,True,48,...,"{'iterations': 568, 'learning_rate': 0.0915807...",{'iterations': 274},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
12,CatBoost/T22,-0.180561,root_mean_squared_error,0.043998,19.878840,0.043998,19.878840,1,True,47,...,"{'iterations': 1016, 'learning_rate': 0.040712...",{'iterations': 1014},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
13,CatBoost/T5,-0.180603,root_mean_squared_error,0.073006,40.885287,0.073006,40.885287,1,True,30,...,"{'iterations': 1049, 'learning_rate': 0.012371...",{'iterations': 1044},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
14,CatBoost/T6,-0.180646,root_mean_squared_error,0.025491,4.871392,0.025491,4.871392,1,True,31,...,"{'iterations': 315, 'learning_rate': 0.1759088...",{'iterations': 311},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
15,CatBoost/T17,-0.180672,root_mean_squared_error,0.026593,5.486820,0.026593,5.486820,1,True,42,...,"{'iterations': 284, 'learning_rate': 0.1768568...",{'iterations': 284},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
16,CatBoost/T11,-0.180689,root_mean_squared_error,0.056333,27.550572,0.056333,27.550572,1,True,36,...,"{'iterations': 1407, 'learning_rate': 0.014994...",{'iterations': 1407},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
17,CatBoost/T25,-0.180741,root_mean_squared_error,0.030741,8.322320,0.030741,8.322320,1,True,50,...,"{'iterations': 330, 'learning_rate': 0.1398059...",{'iterations': 323},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
18,CatBoost/T20,-0.180802,root_mean_squared_error,0.045801,18.541922,0.045801,18.541922,1,True,45,...,"{'iterations': 573, 'learning_rate': 0.0151279...",{'iterations': 573},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
19,CatBoost/T21,-0.180924,root_mean_squared_error,0.043144,20.289444,0.043144,20.289444,1,True,46,...,"{'iterations': 1319, 'learning_rate': 0.013376...",{'iterations': 1317},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
20,CatBoost/T13,-0.180943,root_mean_squared_error,0.027659,8.096745,0.027659,8.096745,1,True,38,...,"{'iterations': 535, 'learning_rate': 0.0384944...",{'iterations': 535},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
21,LightGBM/T17,-0.180999,root_mean_squared_error,0.091296,3.331173,0.091296,3.331173,1,True,17,...,"{'learning_rate': 0.02297842081277621, 'num_le...",{'num_boost_round': 215},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
22,LightGBM/T12,-0.181088,root_mean_squared_error,0.042349,1.711513,0.042349,1.711513,1,True,12,...,"{'learning_rate': 0.04145679169093252, 'num_le...",{'num_boost_round': 110},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
23,LightGBM/T23,-0.181129,root_mean_squared_error,0.206899,7.880096,0.206899,7.880096,1,True,23,...,"{'learning_rate': 0.010591828171692784, 'num_l...",{'num_boost_round': 576},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
24,CatBoost/T16,-0.181141,root_mean_squared_error,0.026928,7.372914,0.026928,7.372914,1,True,41,...,"{'iterations': 598, 'learning_rate': 0.0264786...",{'iterations': 598},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
25,LightGBM/T14,-0.181152,root_mean_squared_error,0.194992,4.337077,0.194992,4.337077,1,True,14,...,"{'learning_rate': 0.011816435472502053, 'num_l...",{'num_boost_round': 566},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
26,CatBoost/T24,-0.181160,root_mean_squared_error,0.027865,7.377407,0.027865,7.377407,1,True,49,...,"{'iterations': 570, 'learning_rate': 0.0293526...",{'iterations': 570},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
27,LightGBM/T21,-0.181195,root_mean_squared_error,0.054469,1.848286,0.054469,1.848286,1,True,21,...,"{'learning_rate': 0.032799397210704205, 'num_l...",{'num_boost_round': 142},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
28,CatBoost/T10,-0.181219,root_mean_squared_error,0.029356,8.185370,0.029356,8.185370,1,True,35,...,"{'iterations': 444, 'learning_rate': 0.0174752...",{'iterations': 444},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
29,LightGBM/T25,-0.181231,root_mean_squared_error,0.109523,2.948606,0.109523,2.948606,1,True,25,...,"{'learning_rate': 0.011059799535949847, 'num_l...",{'num_boost_round': 224},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
30,LightGBM/T24,-0.181243,root_mean_squared_error,0.048538,3.294296,0.048538,3.294296,1,True,24,...,"{'learning_rate': 0.03612775217504794, 'num_le...",{'num_boost_round': 136},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
31,LightGBM/T11,-0.181267,root_mean_squared_error,0.158103,4.476261,0.158103,4.476261,1,True,11,...,"{'learning_rate': 0.013575735243004695, 'num_l...",{'num_boost_round': 525},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
32,LightGBM/T18,-0.181285,root_mean_squared_error,0.118076,2.697886,0.118076,2.697886,1,True,18,...,"{'learning_rate': 0.022101506860254506, 'num_l...",{'num_boost_round': 486},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[WeightedEnsemble_L2]
33,LightGBM/T6,-0.181291,root_mean_squared_error,0.023698,1.327281,0.023698,1.327281,1,True,6,...,"{'learning_rate': 0.0764262643436005, 'num_lea...",{'num_boost_round': 65},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
34,LightGBM/T10,-0.181300,root_mean_squared_error,0.238450,6.268378,0.238450,6.268378,1,True,10,...,"{'learning_rate': 0.014714211033798401, 'num_l...",{'num_boost_round': 865},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
35,LightGBM/T4,-0.181303,root_mean_squared_error,0.030802,1.896308,0.030802,1.896308,1,True,4,...,"{'learning_rate': 0.05483312693790952, 'num_le...",{'num_boost_round': 105},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
36,LightGBM/T22,-0.181342,root_mean_squared_error,0.014454,0.887692,0.014454,0.887692,1,True,22,...,"{'learning_rate': 0.0878167929116211, 'num_lea...",{'num_boost_round': 46},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
37,LightGBM/T2,-0.181352,root_mean_squared_error,0.031164,1.153712,0.031164,1.153712,1,True,2,...,"{'learning_rate': 0.060843366042818384, 'num_l...",{'num_boost_round': 142},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
38,LightGBM/T7,-0.181375,root_mean_squared_error,0.077700,2.366071,0.077700,2.366071,1,True,7,...,"{'learning_rate': 0.034632801362530156, 'num_l...",{'num_boost_round': 345},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
39,LightGBM/T8,-0.181403,root_mean_squared_error,0.041007,1.176223,0.041007,1.176223,1,True,8,...,"{'learning_rate': 0.06361540670994398, 'num_le...",{'num_boost_round': 162},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
40,LightGBM/T15,-0.181413,root_mean_squared_error,0.198257,4.463421,0.198257,4.463421,1,True,15,...,"{'learning_rate': 0.014271457340253242, 'num_l...",{'num_boost_round': 895},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
41,LightGBM/T3,-0.181423,root_mean_squared_error,0.013235,0.733076,0.013235,0.733076,1,True,3,...,"{'learning_rate': 0.14461835703563009, 'num_le...",{'num_boost_round': 31},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
42,LightGBM/T16,-0.181478,root_mean_squared_error,0.051294,1.450669,0.051294,1.450669,1,True,16,...,"{'learning_rate': 0.054596586124474676, 'num_l...",{'num_boost_round': 357},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
43,LightGBM/T13,-0.181479,root_mean_squared_error,0.075782,1.539879,0.075782,1.539879,1,True,13,...,"{'learning_rate': 0.07277250537261028, 'num_le...",{'num_boost_round': 570},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
44,LightGBM/T9,-0.181527,root_mean_squared_error,0.073009,1.450991,0.073009,1.450991,1,True,9,...,"{'learning_rate': 0.03703323754998522, 'num_le...",{'num_boost_round': 491},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
45,LightGBM/T19,-0.181670,root_mean_squared_error,0.052058,1.227086,0.052058,1.227086,1,True,19,...,"{'learning_rate': 0.09047101764422108, 'num_le...",{'num_boost_round': 446},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
46,LightGBM/T20,-0.181712,root_mean_squared_error,0.121636,1.902913,0.121636,1.902913,1,True,20,...,"{'learning_rate': 0.019509039836980442, 'num_l...",{'num_boost_round': 921},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
47,CatBoost/T14,-0.181804,root_mean_squared_error,0.022605,5.374053,0.022605,5.374053,1,True,39,...,"{'iterations': 457, 'learning_rate': 0.0119771...",{'iterations': 457},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
48,LightGBM/T5,-0.181805,root_mean_squared_error,0.034571,0.705624,0.034571,0.705624,1,True,5,...,"{'learning_rate': 0.12113325685093146, 'num_le...",{'num_boost_round': 299},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
49,CatBoost/T1,-0.183148,root_mean_squared_error,0.014153,1.917106,0.014153,1.917106,1,True,26,...,"{'iterations': 200, 'learning_rate': 0.01, 'al...",{'iterations': 200},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]
50,LightGBM/T1,-0.183499,root_mean_squared_error,0.022536,0.523526,0.022536,0.523526,1,True,1,...,"{'learning_rate': 0.01, 'num_leaves': 16, 'num...",{'num_boost_round': 200},"{'max_memory_usage_ratio': 1.0, 'max_gpu_memor...","[FLOOR_AREA_SQM, LEASE_COMMENCE_DATE, approval...",None,None,None,None,[],[]

         RMSE         MAE        R2  Scored listings
0  486.051843  352.387857  0.461511            35207

In [6]:
# Refit on every labelled month strictly before the first test month.
final_preprocessor = RentalPreprocessor(datasets)
final_train_raw = attach_observed_market_residual(available_train, available_train)
final_train = final_preprocessor.fit_transform(final_train_raw)
final_test = final_preprocessor.transform(raw_test)

X_final_train = prepare_tabular_features(final_train)
X_final_test = prepare_tabular_features(final_test)
final_residual_predictor = TabularPredictor(
    label='LOG_RENT_RESIDUAL', problem_type='regression', eval_metric='root_mean_squared_error',
    path=str(experiment_dir / 'ag_exp6_residual_final'),
).fit(
    train_data=X_final_train.assign(LOG_RENT_RESIDUAL=final_train['LOG_RENT_RESIDUAL'].to_numpy()),
    hyperparameters=TABULAR_HYPERPARAMETERS, hyperparameter_tune_kwargs=HPO_KWARGS,
    presets='medium_quality', time_limit=TABULAR_FINAL_TIME_LIMIT, verbosity=2,
)

test_periods = pd.date_range(forecast_origin, raw_test['period'].max(), freq='MS')
final_ts_predictor, final_market_forecast = fit_market_model(
    available_train, len(test_periods), experiment_dir / 'ag_exp6_ts_final_hpo',
    BEST_TS_PARAMS, TS_FINAL_TIME_LIMIT,
)
test_market = final_market_forecast.reset_index()[['item_id', 'timestamp', 'mean']].rename(
    columns={'item_id': 'market_segment', 'timestamp': 'period', 'mean': 'market_rent_forecast'}
)
test_with_market = raw_test.merge(test_market, on=['market_segment', 'period'], how='left')
test_residual_prediction = final_residual_predictor.predict(X_final_test).to_numpy()
test_with_market['PREDICTED_MONTHLY_RENT'] = (
    test_with_market['market_rent_forecast'] * np.exp(test_residual_prediction)
)

# A new town/type segment cannot be forecast; use the prior global market mean.
fallback = available_train[TARGET].mean()
test_with_market['PREDICTED_MONTHLY_RENT'] = test_with_market['PREDICTED_MONTHLY_RENT'].fillna(fallback).clip(lower=0)
submission = test_with_market.drop(columns=['period', 'market_segment', 'market_rent_forecast'])
output_path = experiment_dir / 'exp_6_autogluon_timeseries_predictions.csv'
submission.to_csv(output_path, index=False)
print(f'Saved {len(submission):,} predictions to {output_path}')
display(submission[['RENT_APPROVAL_DATE', 'TOWN', 'FLAT_TYPE', 'PREDICTED_MONTHLY_RENT']].head())

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_residual_final"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.40 GB / 16.00 GB (27.5%)
Disk Space Avail:   195.41 GB / 460.38 GB (42.4%)
===================================================
Presets specified: ['medium_quality']
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Beginning AutoGluon training ... Time limit = 3600s
AutoGluon will save models to "/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_residual_final"
Train Data Rows:    146968
Train Data Columns: 33
Label Column:       LOG_RENT_RESIDUAL
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    4601.55 MB
	Train Data (Original)  Memory Usage: 85.81 MB (1.9% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Useless Original Features (Count: 2): ['FURNISHED', 'FEE']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('datetime', []) :  1 | ['RENT_APPROVAL_DATE']
		('float', [])    : 10 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', ...]
		('int', [])      : 14 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('object', [])   :  6 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])             :  6 | ['TOWN', 'BLOCK', 'STREET', 'FLAT_TYPE', 'FLAT_MODEL', ...]
		('float', [])                : 10 | ['FLOOR_AREA_SQM', 'LATITUDE', 'LONGITUDE', 'mrt_dist_nearest_km', 'mall_dist_nearest_km', ...]
		('int', [])                  : 14 | ['LEASE_COMMENCE_DATE', 'approval_year', 'approval_month', 'approval_date_num', 'lease_age', ...]
		('int', ['datetime_as_int']) :  2 | ['RENT_APPROVAL_DATE', 'RENT_APPROVAL_DATE.dayofweek']
	0.2s = Fit runtime
	31 features in original data used to generate 32 features in processed data.
	Train Data (Processed) Memory Usage: 30.28 MB (0.7% of available memory)
Data preprocessing and feature engineering runtime = 0.27s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.034, Train Rows: 141971, Val Rows: 4997
User-specified model hyperparameters to be fit:
{
	'GBM': [{'num_leaves': Int: lower=16, upper=128, 'num_boost_round': Int: lower=200, upper=1500, 'max_depth': Int: lower=3, upper=12, 'learning_rate': Real: lower=0.01, upper=0.2, 'min_data_in_leaf': Int: lower=10, upper=150, 'feature_fraction': Real: lower=0.6, upper=1.0, 'bagging_fraction': Real: lower=0.6, upper=1.0}],
	'CAT': [{'iterations': Int: lower=200, upper=1500, 'depth': Int: lower=4, upper=10, 'learning_rate': Real: lower=0.01, upper=0.2, 'l2_leaf_reg': Real: lower=1.0, upper=30.0}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Hyperparameter tuning model: LightGBM ... Tuning model for up to 1619.88s of the 3599.73s of remaining time.
 56%|█████▌    | 14/25 [00:32<00:38,  3.48s/it]

[1000]	valid_set's rmse: 0.185816

100%|██████████| 25/25 [01:08<00:00,  2.76s/it]
Fitted model: LightGBM/T1 ...
	-0.1881	 = Validation score   (-root_mean_squared_error)
	0.55s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T2 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	1.37s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T3 ...
	-0.1856	 = Validation score   (-root_mean_squared_error)
	0.81s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T4 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	1.88s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T5 ...
	-0.1859	 = Validation score   (-root_mean_squared_error)
	0.79s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T6 ...
	-0.1856	 = Validation score   (-root_mean_squared_error)
	1.25s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T7 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	1.91s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T8 ...
	-0.1858	 = Validation score   (-root_mean_squared_error)
	1.43s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T9 ...
	-0.1859	 = Validation score   (-root_mean_squared_error)
	1.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T10 ...
	-0.1859	 = Validation score   (-root_mean_squared_error)
	5.5s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T11 ...
	-0.1856	 = Validation score   (-root_mean_squared_error)
	6.08s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T12 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	1.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T13 ...
	-0.1858	 = Validation score   (-root_mean_squared_error)
	1.59s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T14 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	5.25s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T15 ...
	-0.1858	 = Validation score   (-root_mean_squared_error)
	5.06s	 = Training   runtime
	0.04s	 = Validation runtime
Fitted model: LightGBM/T16 ...
	-0.1859	 = Validation score   (-root_mean_squared_error)
	1.12s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T17 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	3.81s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T18 ...
	-0.1856	 = Validation score   (-root_mean_squared_error)
	3.05s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T19 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	1.59s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T20 ...
	-0.186	 = Validation score   (-root_mean_squared_error)
	2.22s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: LightGBM/T21 ...
	-0.1856	 = Validation score   (-root_mean_squared_error)
	2.07s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T22 ...
	-0.1856	 = Validation score   (-root_mean_squared_error)
	1.16s	 = Training   runtime
	0.0s	 = Validation runtime
Fitted model: LightGBM/T23 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	8.81s	 = Training   runtime
	0.03s	 = Validation runtime
Fitted model: LightGBM/T24 ...
	-0.1859	 = Validation score   (-root_mean_squared_error)
	4.22s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: LightGBM/T25 ...
	-0.1857	 = Validation score   (-root_mean_squared_error)
	3.25s	 = Training   runtime
	0.02s	 = Validation runtime
Hyperparameter tuning model: CatBoost ... Tuning model for up to 1619.88s of the 3530.65s of remaining time.
100%|██████████| 25/25 [09:28<00:00, 22.75s/it]
Fitted model: CatBoost/T1 ...
	-0.1873	 = Validation score   (-root_mean_squared_error)
	2.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T2 ...
	-0.1842	 = Validation score   (-root_mean_squared_error)
	25.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T3 ...
	-0.1844	 = Validation score   (-root_mean_squared_error)
	34.2s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T4 ...
	-0.1844	 = Validation score   (-root_mean_squared_error)
	44.61s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T5 ...
	-0.1845	 = Validation score   (-root_mean_squared_error)
	53.49s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T6 ...
	-0.1845	 = Validation score   (-root_mean_squared_error)
	5.97s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T7 ...
	-0.1845	 = Validation score   (-root_mean_squared_error)
	15.81s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T8 ...
	-0.1843	 = Validation score   (-root_mean_squared_error)
	28.39s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T9 ...
	-0.1846	 = Validation score   (-root_mean_squared_error)
	24.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T10 ...
	-0.1852	 = Validation score   (-root_mean_squared_error)
	9.93s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T11 ...
	-0.1847	 = Validation score   (-root_mean_squared_error)
	32.8s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T12 ...
	-0.1844	 = Validation score   (-root_mean_squared_error)
	43.05s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T13 ...
	-0.1849	 = Validation score   (-root_mean_squared_error)
	9.56s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T14 ...
	-0.1859	 = Validation score   (-root_mean_squared_error)
	6.36s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T15 ...
	-0.1844	 = Validation score   (-root_mean_squared_error)
	36.93s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T16 ...
	-0.1851	 = Validation score   (-root_mean_squared_error)
	8.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T17 ...
	-0.1846	 = Validation score   (-root_mean_squared_error)
	6.5s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T18 ...
	-0.1841	 = Validation score   (-root_mean_squared_error)
	43.06s	 = Training   runtime
	0.02s	 = Validation runtime
Fitted model: CatBoost/T19 ...
	-0.1844	 = Validation score   (-root_mean_squared_error)
	26.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T20 ...
	-0.1848	 = Validation score   (-root_mean_squared_error)
	21.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T21 ...
	-0.1849	 = Validation score   (-root_mean_squared_error)
	23.66s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T22 ...
	-0.1846	 = Validation score   (-root_mean_squared_error)
	22.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T23 ...
	-0.1846	 = Validation score   (-root_mean_squared_error)
	23.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T24 ...
	-0.1851	 = Validation score   (-root_mean_squared_error)
	8.85s	 = Training   runtime
	0.01s	 = Validation runtime
Fitted model: CatBoost/T25 ...
	-0.1846	 = Validation score   (-root_mean_squared_error)
	9.66s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 2960.96s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/4.4 GB
	Ensemble Weights: {'CatBoost/T18': 0.667, 'LightGBM/T11': 0.167, 'CatBoost/T2': 0.167}
	-0.184	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 639.07s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 78216.7 rows/s (4997 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_residual_final")
Beginning AutoGluon training... Time limit = 600s
AutoGluon will save models to '/Users/metul/Desktop/KDDM-project/exploration/metul/ag_exp6_ts_final_hpo'
=================== System Info ===================
AutoGluon Version:  1.6.2
Python Version:     3.12.14
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.6.0: Fri Jul 31 19:16:20 PDT 2026; root:xnu-12377.161.14~5/RELEASE_ARM64_T8142
CPU Count:          10
Pytorch Version:    2.10.0
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       4.39 GB / 16.00 GB (27.4%)
Disk Space Avail:   194.99 GB / 460.38 GB (42.4%)
===================================================

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': RMSE,
 'freq': 'MS',
 'hyperparameters': {'DirectTabular': {'model_hyperparameters': {'bagging_fraction': 0.6707091131756927,
                                                                 'feature_fraction': 0.8316878275767584,
                                                                 'learning_rate': 0.025006835969478818,
                                                                 'max_depth': 8,
                                                                 'min_data_in_leaf': 38,
                                                                 'num_boost_round': 792,
                                                                 'num_leaves': 30},
                                       'model_name': 'GBM'},
                     'ETS': {},
                     'RecursiveTabular': {'model_hyperparameters': {'bagging_fraction': 0.6707091131756927,
                                                                    'feature_fraction': 0.8316878275767584,
                                                                    'learning_rate': 0.025006835969478818,
                                                                    'max_depth': 8,
                                                                    'min_data_in_leaf': 38,
                                                                    'num_boost_round': 792,
                                                                    'num_leaves': 30},
                                          'model_name': 'GBM'},
                     'Theta': {}},
 'known_covariates_names': ['coe_bids_mean',
                            'coe_quota_premium_mean',
                            'month_sin',
                            'month_cos'],
 'num_val_windows': 2,
 'prediction_length': 17,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 42,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'time_limit': 600,
 'verbosity': 2}

train_data with frequency 'IRREG' has been resampled to frequency 'MS'.
Provided train_data has 6035 rows (NaN fraction=5.2%), 121 time series. Median time series length is 50 (min=46, max=50).
Time series in train_data are too short for chosen num_val_windows=(2,). Reducing num_val_windows to 1 total windows.

Provided data contains following columns:
	target: 'target'
	known_covariates:
		categorical:        []
		continuous (float): ['coe_bids_mean', 'coe_quota_premium_mean', 'month_sin', 'month_cos']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'RMSE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2026-09-22 11:54:49
Models that will be trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta']
Training timeseries model RecursiveTabular. Training for up to 119.7s of the 598.4s of remaining time.
	-829.1354     = Validation score (-RMSE)
	0.77    s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model DirectTabular. Training for up to 149.4s of the 597.6s of remaining time.
	-1007.9745    = Validation score (-RMSE)
	1.74    s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Training timeseries model ETS. Training for up to 198.6s of the 595.8s of remaining time.
	-508.7481     = Validation score (-RMSE)
	0.01    s     = Training runtime
	3.28    s     = Validation (prediction) runtime
Training timeseries model Theta. Training for up to 296.2s of the 592.5s of remaining time.
	-335.4700     = Validation score (-RMSE)
	0.01    s     = Training runtime
	0.10    s     = Validation (prediction) runtime
Fitting 1 ensemble(s), in 1 layers.
Training ensemble model WeightedEnsemble. Training for up to 592.3s.
	Ensemble weights: {'DirectTabular': 0.2, 'ETS': 0.04, 'RecursiveTabular': 0.09, 'Theta': 0.67}
	-282.5691     = Validation score (-RMSE)
	0.10    s     = Training runtime
	3.45    s     = Validation (prediction) runtime
Training complete. Models trained: ['RecursiveTabular', 'DirectTabular', 'ETS', 'Theta', 'WeightedEnsemble']
Total runtime: 6.16 s
Best model: WeightedEnsemble
Best model score: -282.5691
data with frequency 'IRREG' has been resampled to frequency 'MS'.
data with frequency 'IRREG' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

Saved 50,000 predictions to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_6_autogluon_timeseries_predictions.csv

  RENT_APPROVAL_DATE             TOWN FLAT_TYPE  PREDICTED_MONTHLY_RENT
0            2025-03  kallang/whampoa    3-room             2597.509690
1            2025-03      bukit timah    4-room             3219.667855
2            2025-03        pasir ris    4-room             3051.873320
3            2025-03          punggol    4-room             3064.971929
4            2025-03         tampines    4-room             3231.460298

In [7]:
# Competition submission format: one prediction per original test row.
# Run this after the preceding cell has created `test_with_market`.
competition_submission = pd.DataFrame({
    'Id': raw_test.index.to_numpy(),
    'Predicted': test_with_market['PREDICTED_MONTHLY_RENT'].to_numpy(),
})
assert competition_submission['Id'].is_unique
assert len(competition_submission) == len(raw_test)
assert competition_submission['Predicted'].notna().all()

competition_output_path = experiment_dir / 'exp_6_autogluon_timeseries_submission.csv'
competition_submission.to_csv(competition_output_path, index=False)
print(f'Saved {len(competition_submission):,} competition-format predictions to {competition_output_path}')
display(competition_submission.head())

Saved 50,000 competition-format predictions to /Users/metul/Desktop/KDDM-project/exploration/metul/exp_6_autogluon_timeseries_submission.csv

   Id    Predicted
0   0  2597.509690
1   1  3219.667855
2   2  3051.873320
3   3  3064.971929
4   4  3231.460298